Repository WebKit/WebKit, pull requests merged in 2022-05, with the labels that each got.

#543 [ iOS Release ] fast/css-custom-paint/animate-repaint.html is a flaky failure
  LayoutTests/ChangeLog
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, New Bugs, WebKit Nightly Build

#655 [ iOS ] imported/w3c/web-platform-tests/html/browsers/browsing-the-web/unloading-documents/004.html is a flaky timeout
  LayoutTests/ChangeLog
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, New Bugs, WebKit Nightly Build

#758 git webkit setup ignores configured editor (Part 2)
  Tools/Scripts/libraries/webkitscmpy/setup.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/mocks/local/git.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/setup_unittest.py
Labels: unsafe-merge-queue, Tools / Tests, WebKit Nightly Build

#991 [ iOS & MacOS Release ]TestWebKitAPI.WebpagePreferences.WebsitePoliciesAutoplayQuirksAsyncPolicyDelegate is a flaky timeout
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebsitePolicies.mm
Labels: unsafe-merge-queue

#1192 Add Nikita Vasilyev's GitHub username to contributors.json
  metadata/contributors.json
Labels: unsafe-merge-queue
