Repository WebKit/WebKit, pull requests merged in 2025-08, with the labels that each got.

#48811 [WPE] Unskip fast/dom/HTMLAnchorElement layout tests
  LayoutTests/platform/glib/TestExpectations
  LayoutTests/platform/glib/fast/dom/HTMLAnchorElement/anchor-file-blob-convert-to-download-async-delegate-expected.txt
  LayoutTests/platform/glib/fast/dom/HTMLAnchorElement/anchor-file-blob-convert-to-download-expected.txt
  LayoutTests/platform/glib/fast/dom/HTMLAnchorElement/anchor-file-blob-download-includes-backslash-expected.txt
  LayoutTests/platform/glib/fast/dom/HTMLAnchorElement/anchor-file-blob-download-includes-doublequote-expected.txt
  LayoutTests/platform/glib/fast/dom/HTMLAnchorElement/anchor-file-blob-download-includes-slashes-expected.txt
  LayoutTests/platform/gtk/TestExpectations
  LayoutTests/platform/wpe/TestExpectations
Labels: unsafe-merge-queue, WPE WebKit

#48786 Make BaselineSynthesisEdge and FontBaseline enum classes
  Source/WebCore/layout/formattingContexts/inline/InlineLineBox.h
  Source/WebCore/layout/formattingContexts/inline/InlineLineBoxBuilder.cpp
  Source/WebCore/layout/formattingContexts/inline/display/InlineDisplayLine.h
  Source/WebCore/platform/graphics/FontBaseline.h
  Source/WebCore/platform/graphics/FontMetrics.h
  Source/WebCore/platform/graphics/coretext/DrawGlyphsRecorder.cpp
  Source/WebCore/platform/graphics/coretext/FontCascadeCoreText.cpp
  Source/WebCore/rendering/LegacyInlineFlowBox.h
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/RenderFlexibleBox.cpp
  Source/WebCore/rendering/RenderGrid.cpp
Labels: unsafe-merge-queue, Layout and Rendering

#48810 REGRESSION(298070@main): [iOS]: Multiple tests in imported/w3c/web-platform-tests/content-security-policy are failing
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/form-action/form-action-src-blocked.sub-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.http-rp/script-src-self/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.http-rp/script-src-wildcard/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.http-rp/worker-src-self/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.http-rp/worker-src-wildcard/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.meta/script-src-self/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.meta/script-src-wildcard/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.meta/worker-src-self/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/gen/top.meta/worker-src-wildcard/sharedworker-import.http-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/img-src/img-src-host-partial-wildcard-allowed.sub-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/img-src/img-src-port-wildcard-allowed.sub-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/content-security-policy/worker-src/service-worker-src-child-fallback.https.sub-expected.txt
Labels: merge-queue, New Bugs

#48777 Fix recent Safer CPP regressions in WebCore
  Source/WebCore/SaferCPPExpectations/ForwardDeclCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebCore/accessibility/AccessibilityScrollView.cpp
  Source/WebCore/dom/SerializedNode.cpp
  Source/WebCore/layout/integration/LayoutIntegrationBoxGeometryUpdater.cpp
  Source/WebCore/rendering/svg/SVGTextLayoutEngineSpacing.cpp
  Source/WebCore/rendering/svg/SVGTextLayoutEngineSpacing.h
Labels: merge-queue, WebCore Misc.

#48770 REGRESSION(297498@main): [WPE] build broken when using API 1.1
  Source/WebKit/UIProcess/API/glib/WebKitJavascriptResult.cpp
Labels: unsafe-merge-queue, WPE WebKit

#48817 [JSC] WasmBindings.h header file includes itself
  Source/JavaScriptCore/wasm/WasmBinding.h
Labels: unsafe-merge-queue, WebKit Misc.

#48821 [WPE] WPE Platform: move GRefPtrWPE from WebKit to WPEPlatform
  Source/WebKit/Shared/wpe/GRefPtrWPE.h
  Source/WebKit/SourcesWPE.txt
  Source/WebKit/UIProcess/API/wpe/WPEWebViewPlatform.h
  Source/WebKit/UIProcess/Automation/libwpe/WebAutomationSessionWPE.cpp
  Source/WebKit/UIProcess/wpe/WebPasteboardProxyWPE.cpp
  Source/WebKit/WPEPlatform/wpe/GRefPtrWPE.h
  Source/WebKit/WPEPlatform/wpe/WPEClipboard.cpp
  Source/WebKit/WPEPlatform/wpe/drm/WPEDRMSeat.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEInputMethodContextWaylandV1.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEViewWayland.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEWaylandSeat.cpp
Labels: unsafe-merge-queue, WPE WebKit

#48703 [Navigation API] navigate.back doesn't work in main frame when preceded by navigate.back in child frame
  LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-methods/disambigaute-forward-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-methods/disambigaute-traverseTo-forward-multiple-expected.txt
  Source/WebCore/loader/HistoryController.cpp
  Source/WebCore/loader/NavigationScheduler.cpp
  Source/WebCore/page/Navigation.cpp
  Source/WebCore/page/Navigation.h
Labels: unsafe-merge-queue, New Bugs

#48816 WebEvent.h: remove useless inclusion to itself
  Source/WebKit/Shared/WebEvent.h
Labels: WebKit Misc.

#48708 [WPE] WPE Platform: add WPEDRMDevice
  Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp
  Source/WebKit/UIProcess/GPU/GPUProcessProxy.cpp
  Source/WebKit/UIProcess/glib/DRMDevice.cpp
  Source/WebKit/UIProcess/glib/DRMDevice.h
  Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp
  Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp
  Source/WebKit/UIProcess/wpe/WebPageProxyWPE.cpp
  Source/WebKit/WPEPlatform/CMakeLists.txt
  Source/WebKit/WPEPlatform/wpe/GRefPtrWPE.h
  Source/WebKit/WPEPlatform/wpe/WPEBufferDMABuf.cpp
  Source/WebKit/WPEPlatform/wpe/WPEBufferDMABufFormats.cpp
  Source/WebKit/WPEPlatform/wpe/WPEBufferDMABufFormats.h
  Source/WebKit/WPEPlatform/wpe/WPEDRMDevice.cpp
  Source/WebKit/WPEPlatform/wpe/WPEDRMDevice.h
  Source/WebKit/WPEPlatform/wpe/WPEDRMDevicePrivate.h
  Source/WebKit/WPEPlatform/wpe/WPEDisplay.cpp
  Source/WebKit/WPEPlatform/wpe/WPEDisplay.h
  Source/WebKit/WPEPlatform/wpe/WPEToplevel.cpp
  Source/WebKit/WPEPlatform/wpe/drm/WPEDisplayDRM.cpp
  Source/WebKit/WPEPlatform/wpe/drm/WPEDisplayDRMPrivate.h
  Source/WebKit/WPEPlatform/wpe/drm/WPEScreenDRM.cpp
  Source/WebKit/WPEPlatform/wpe/headless/WPEDisplayHeadless.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEDisplayWayland.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEToplevelWayland.cpp
  Source/WebKit/WPEPlatform/wpe/wpe-platform.h
  Tools/TestWebKitAPI/Tests/WPEPlatform/TestDisplay.cpp
  Tools/TestWebKitAPI/glib/WPEPlatform/mock/WPEDisplayMock.cpp
Labels: unsafe-merge-queue, WPE WebKit

#48820 [WPE] Support undo by using DefaultUndoController
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/editing/other/exec-command-with-text-editor.tentative-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/editing/run/undo-redo-expected.txt
  LayoutTests/platform/wpe/TestExpectations
  LayoutTests/platform/wpe/editing/inserting/redo-expected.txt
  LayoutTests/platform/wpe/editing/selection/directionality-after-undo-replace-expected.txt
  LayoutTests/platform/wpe/fast/css/relative-positioned-block-crash-expected.txt
  LayoutTests/platform/wpe/imported/w3c/web-platform-tests/editing/other/exec-command-with-text-editor.tentative-expected.txt
  LayoutTests/platform/wpe/imported/w3c/web-platform-tests/editing/other/exec-command-without-editable-element.tentative-expected.txt
  LayoutTests/platform/wpe/imported/w3c/web-platform-tests/editing/run/undo-redo-expected.txt
  Source/WebKit/UIProcess/API/wpe/PageClientImpl.cpp
  Source/WebKit/UIProcess/API/wpe/PageClientImpl.h
Labels: unsafe-merge-queue, WPE WebKit

#46761 [JSC] Implement `Array.prototype.flat` in C++
  JSTests/microbenchmarks/array-prototype-flat-depth-1-double.js
  JSTests/microbenchmarks/array-prototype-flat-depth-1-int32.js
  JSTests/microbenchmarks/array-prototype-flat-depth-1-mixed.js
  JSTests/microbenchmarks/array-prototype-flat-depth-1-string.js
  JSTests/microbenchmarks/array-prototype-flat-depth-2.js
  JSTests/microbenchmarks/array-prototype-flat-depth-3.js
  JSTests/microbenchmarks/array-prototype-flat-depth-infinity.js
  JSTests/microbenchmarks/array-prototype-flat-huge-arrays.js
  JSTests/microbenchmarks/array-prototype-flat-large-nested.js
  JSTests/microbenchmarks/array-prototype-flat-small-arrays.js
  JSTests/microbenchmarks/array-prototype-flat-sparse-array.js
  JSTests/stress/array-prototype-flat-hole.js
  JSTests/stress/array-prototype-flat-nested-proxy-array.js
  Source/JavaScriptCore/builtins/ArrayPrototype.js
  Source/JavaScriptCore/runtime/ArrayPrototype.cpp
  Source/JavaScriptCore/runtime/CommonIdentifiers.h
  Source/JavaScriptCore/runtime/JSArray.cpp
  Source/JavaScriptCore/runtime/JSArray.h
Labels: merge-queue, JavaScriptCore

#48434 Event Timing: event counting (https://w3c.github.io/event-timing)
  LayoutTests/TestExpectations
  LayoutTests/imported/w3c/web-platform-tests/event-timing/event-click-counts-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/event-timing/event-counts-zero-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/event-timing/idlharness.window-expected.txt
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk1/TestExpectations
  Source/WebCore/dom/Document.cpp
  Source/WebCore/dom/Document.h
  Source/WebCore/dom/EventDispatcher.cpp
  Source/WebCore/dom/EventNames.json
  Source/WebCore/dom/make-event-names.py
  Source/WebCore/page/EventCounts.cpp
  Source/WebCore/page/EventCounts.h
  Source/WebCore/page/LocalDOMWindow.cpp
  Source/WebCore/page/LocalDOMWindow.h
  Source/WebCore/page/Page.cpp
  Source/WebCore/page/Performance.cpp
  Source/WebCore/page/Performance.h
  Source/WebCore/platform/Logging.h
Labels: merge-queue

#48836 [GARDENING][ macOS wk2 Release, iOS Release ] imported/w3c/web-platform-tests/css/css-shapes/spec-examples/shape-outside-012.html is a flakey text failure
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#48837 [GARDENING][ macOS wk2 arm64 ] imported/w3c/web-platform-tests/css/css-view-transitions/rotated-cat-off-top-edge.html is a flakey image failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#48842 [ iOS Release ] TestWebKitAPI.WKWebsiteDataStoreConfiguration.TotalQuotaRatioWithPersistedDomain (api-tests) is a flaky timeout
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKWebsiteDatastore.mm
Labels: merge-queue, Website Storage

#48845 [GARDENING]REGRESSION (294307@main): [ Sequoia+ arm64 ] http/tests/webgpu/webgpu/shader/execution/expression/binary/f16_matrix_vector_multiplication.html is a consistent timeout
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#48705 Return non-null result from WKContentView.browsingContextController
  Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm
Labels: New Bugs

#48838 [Materials] Add support for the clear variant of glass
  Source/WebCore/css/CSSPrimitiveValueMappings.h
  Source/WebCore/css/CSSProperties.json
  Source/WebCore/css/CSSValueKeywords.in
  Source/WebCore/platform/cocoa/AppleVisualEffect.cpp
  Source/WebCore/platform/cocoa/AppleVisualEffect.h
  Source/WebKit/Platform/cocoa/WKMaterialHostingSupport.h
  Source/WebKit/Platform/cocoa/WKMaterialHostingSupport.swift
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerTreePropertyApplier.mm
  Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in
  Tools/TestWebKitAPI/Tests/WebKitCocoa/AppleVisualEffectTests.mm
Labels: unsafe-merge-queue, New Bugs

#48767 Annotate WebRTC IPC endpoints with PeerConnectionEnabled
  Source/WebCore/Modules/mediastream/RTCPeerConnection.cpp
  Source/WebKit/NetworkProcess/NetworkProcess.cpp
  Source/WebKit/NetworkProcess/webrtc/NetworkMDNSRegister.cpp
  Source/WebKit/NetworkProcess/webrtc/NetworkMDNSRegister.h
  Source/WebKit/NetworkProcess/webrtc/NetworkMDNSRegister.messages.in
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCMonitor.cpp
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCMonitor.h
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCMonitor.messages.in
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCProvider.cpp
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCProvider.h
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCProvider.messages.in
  Source/WebKit/NetworkProcess/webrtc/RTCDataChannelRemoteManagerProxy.cpp
  Source/WebKit/NetworkProcess/webrtc/RTCDataChannelRemoteManagerProxy.h
  Source/WebKit/NetworkProcess/webrtc/RTCDataChannelRemoteManagerProxy.messages.in
  Source/WebKit/WebProcess/Network/webrtc/LibWebRTCNetworkManager.cpp
Labels: merge-queue, New Bugs

#48833 [SaferCPP] Address issues in ComputePipeline.mm
  Source/WebGPU/WebGPU/ComputePipeline.mm
Labels: merge-queue, WebGPU

#48846 Add macOS 26 Tahoe, iOS26, tvOS26, watchos26, and visionOS 26 system images
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/IOS17.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/IOS17Simulator.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/IOS26.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/IOS26Simulator.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/Tahoe.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/TvOS26.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/TvOS26Simulator.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/Ventura.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/WatchOSSimulator26.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/visionOS26.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/visionOS26Simulator.png
  Tools/CISupport/build-webkit-org/public_html/dashboard/Images/watchOS26.png
Labels: merge-queue, Tools / Tests

#48848 [GARDENING][ iOS Release ] http/tests/webcodecs/audio-encoder-callbacks-do-not-leak.html is a flakey text failure
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#48844 [SaferCPP] Fix uncounted variable warning in RenderBundleEncoder
  Source/WebGPU/WebGPU/RenderBundleEncoder.mm
Labels: merge-queue, WebGPU

#48852 Unreviewed, reverting 298015@main (7f2645c0c68b)
  Source/WebCore/dom/Node.cpp
  Source/WebCore/dom/Node.h
  Source/WebCore/dom/NodeInlines.h
  Source/WebCore/dom/TreeScope.h
  Source/WebCore/dom/TreeScopeInlines.h
Labels: unsafe-merge-queue, New Bugs

#48855 [GARDENING][ iOS ] imported/w3c/web-platform-tests/css/css-contain/content-visibility/content-visibility-096.html is a flakey image failure
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#46639 TBA availability macros in downlevels do not fall back in Swift like they do in ObjC
  Source/WebKit/Configurations/Base.xcconfig
  Source/WebKit/Scripts/generate-swift-availability-macros
  Source/WebKit/Scripts/postprocess-header-rule
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Tools/TestWebKitAPI/Configurations/TestWebKitAPILibrary.xcconfig
Labels: merge-queue, Tools / Tests

#48853 Re-import html/editing/the-hidden-attribute WPT
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-infinite-loop-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-infinite-loop.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-001-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-002.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-004-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-005-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-005-ref.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-007-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/resources/container-ref.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/resources/spacer-and-container-ref.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/w3c-import.log
Labels: merge-queue, DOM

#48809 Add Storage Access API testRunner support for `test_driver.set_permission`
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess-cross-site-fetch.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess-cross-site-sibling-iframes.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess-dedicated-worker.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess-nested-same-origin-iframe.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess-web-socket.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/requestStorageAccess.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.BroadcastChannel.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.SharedWorker.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.blobStorage.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.caches.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.cookies.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.estimate.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.getDirectory.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.indexedDB.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.localStorage.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.locks.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.none.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.sessionStorage.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-beyond-cookies.unpartitioned.sub.https.window-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/storage-access-api/storage-access-headers.tentative.https.sub.window-expected.txt
  LayoutTests/resources/testdriver-vendor.js
  Source/WebKit/NetworkProcess/Classifier/ResourceLoadStatisticsStore.cpp
  Source/WebKit/NetworkProcess/Classifier/ResourceLoadStatisticsStore.h
  Source/WebKit/NetworkProcess/Classifier/WebResourceLoadStatisticsStore.cpp
  Source/WebKit/NetworkProcess/Classifier/WebResourceLoadStatisticsStore.h
  Source/WebKit/NetworkProcess/NetworkProcess.cpp
  Source/WebKit/NetworkProcess/NetworkProcess.h
  Source/WebKit/NetworkProcess/NetworkProcess.messages.in
  Source/WebKit/UIProcess/API/C/WKWebsiteDataStoreRef.cpp
  Source/WebKit/UIProcess/API/C/WKWebsiteDataStoreRef.h
  Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp
  Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.h
  Tools/WebKitTestRunner/InjectedBundle/Bindings/TestRunner.idl
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestController.cpp
Labels: unsafe-merge-queue, Tools / Tests

#48804 com.apple.WebKit.GPU at WebCore: WebCore::WebMParser::OnTrackEntry
  Source/WebCore/platform/graphics/cocoa/SourceBufferParserWebM.cpp
Labels: merge-queue, Media

#48859 Rename toRef that takes only JSValue
  Source/JavaScriptCore/API/APICast.h
  Source/JavaScriptCore/API/JSValueRef.cpp
  Source/WebKit/WebProcess/Inspector/WebInspectorUIExtensionController.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#48808 Switch to TextIndicator for DidReceiveEditDragSnapshot.
  Source/WebKit/UIProcess/PageClient.h
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/UIProcess/WebPageProxy.messages.in
  Source/WebKit/UIProcess/ios/DragDropInteractionState.h
  Source/WebKit/UIProcess/ios/DragDropInteractionState.mm
  Source/WebKit/UIProcess/ios/PageClientImplIOS.h
  Source/WebKit/UIProcess/ios/PageClientImplIOS.mm
  Source/WebKit/UIProcess/ios/WKContentViewInteraction.h
  Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm
  Source/WebKit/UIProcess/ios/WebPageProxyIOS.mm
  Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm
Labels: merge-queue, WebKit Misc.

#48840 Update details and hidden=until-found ancestor revealing algorithm
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-attribute-removal-001-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-attribute-removal-001.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-attribute-removal-002-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-attribute-removal-002.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-element-removal-001-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-element-removal-001.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-element-removal-002-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-element-removal-002.html
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/beforematch-infinite-loop-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-and-details-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/editing/the-hidden-attribute/hidden-until-found-and-details.html
  Source/WebCore/dom/FindRevealAlgorithms.cpp
  Source/WebCore/dom/FindRevealAlgorithms.h
Labels: DOM

#48861 Enable `hidden=until-found` by default
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: merge-queue, DOM

#48847 Crash when a video element is moved to a new document after calling `webkitShowPlaybackTargetPicker`
  LayoutTests/media/adopt-node-after-showing-picker-crash-expected.txt
  LayoutTests/media/adopt-node-after-showing-picker-crash.html
  LayoutTests/platform/glib/TestExpectations
  LayoutTests/platform/gtk/TestExpectations
  LayoutTests/platform/wpe/TestExpectations
  Source/WebCore/dom/Document.cpp
  Source/WebCore/dom/Document.h
  Source/WebCore/platform/audio/PlatformMediaSessionInterface.h
  Source/WebCore/platform/graphics/MediaPlaybackTargetClient.h
Labels: merge-queue, Media

#48860 Enable auto-expanding details element by default
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: DOM

#48854 [WTF] Modernize wtf/MathExtras.h
  Source/WTF/wtf/MathExtras.h
Labels: merge-queue

#48813 [JSC] Copy spread characters when rope fibers are same
  Source/JavaScriptCore/runtime/JSStringInlines.h
Labels: unsafe-merge-queue, JavaScriptCore

#47953 [WebIDL] Add WebIDL support for [Enumerated] extended attribute and related attributes [MissingValueDefault],[InvalidValueDefault]
  Source/WebCore/bindings/scripts/CodeGenerator.pm
  Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
  Source/WebCore/bindings/scripts/IDLAttributes.json
  Source/WebCore/bindings/scripts/test/JS/JSTestObj.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestObj.h
  Source/WebCore/bindings/scripts/test/TestObj.idl
  Source/WebCore/html/HTMLIFrameElement.cpp
  Source/WebCore/html/HTMLIFrameElement.h
  Source/WebCore/html/HTMLIFrameElement.idl
  Source/WebCore/html/HTMLImageElement.cpp
  Source/WebCore/html/HTMLImageElement.h
  Source/WebCore/html/HTMLImageElement.idl
Labels: merge-queue, Bindings

#48868 [JSC] Fix the macOS JSC Cmake build
  Source/bmalloc/CMakeLists.txt
  Source/bmalloc/PlatformJSCOnly.cmake
  Source/bmalloc/bmalloc/TZoneLog.cpp
  Source/cmake/WebKitFeatures.cmake
Labels: unsafe-merge-queue

#48862 [JSC] Use Butterfly::clearOptimalVectorLengthGap for JSArray::tryCreate's butterfly initialization
  Source/JavaScriptCore/generator/DSL.rb
  Source/JavaScriptCore/runtime/JSArray.h
Labels: unsafe-merge-queue, JavaScriptCore

#48872 Resync `html/rendering/widgets` from WPT upstream
  LayoutTests/imported/w3c/resources/resource-files.json
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/baseline-alignment-and-overflow.tentative-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/input-fragmentation-crash.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/scrollable-button-centering-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/scrollable-button-centering-ref.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/scrollable-button-centering.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/scrollbars-expected.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/scrollbars.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/button-layout/w3c-import.log
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/field-sizing-select-contain-size-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/field-sizing-select-contain-size.html
  LayoutTests/imported/w3c/web-platform-tests/html/rendering/widgets/w3c-import.log
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/html/rendering/widgets/field-sizing-select-contain-size-expected.txt
Labels: merge-queue, WebCore Misc.

#48881 [WPE] Unskip editing/undo layout tests
  LayoutTests/platform/glib/editing/undo/4063751-expected.png
  LayoutTests/platform/glib/editing/undo/4063751-expected.txt
  LayoutTests/platform/glib/editing/undo/5378473-expected.png
  LayoutTests/platform/glib/editing/undo/redo-typing-001-expected.png
  LayoutTests/platform/glib/editing/undo/redo-typing-001-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-combined-delete-boundary-expected.png
  LayoutTests/platform/glib/editing/undo/undo-combined-delete-boundary-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-combined-delete-expected.png
  LayoutTests/platform/glib/editing/undo/undo-combined-delete-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-delete-boundary-expected.png
  LayoutTests/platform/glib/editing/undo/undo-delete-boundary-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-delete-expected.png
  LayoutTests/platform/glib/editing/undo/undo-delete-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-forward-delete-boundary-expected.png
  LayoutTests/platform/glib/editing/undo/undo-forward-delete-boundary-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-forward-delete-expected.png
  LayoutTests/platform/glib/editing/undo/undo-forward-delete-expected.txt
  LayoutTests/platform/glib/editing/undo/undo-misspellings-expected.png
  LayoutTests/platform/glib/editing/undo/undo-typing-001-expected.png
  LayoutTests/platform/glib/editing/undo/undo-typing-001-expected.txt
  LayoutTests/platform/wpe/TestExpectations
Labels: unsafe-merge-queue, WPE WebKit

#48863 [macOS Tahoe] 8 css-ui/compute-kind-widget-generated/kind-of-widget-fallback-select-dropdown-box-border tests are a consistent failure
  LayoutTests/platform/mac/TestExpectations
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.mm
  Source/WebCore/rendering/mac/RenderThemeMac.mm
Labels: merge-queue, New Bugs

#48857 Storage Access API should not be usable in insecure contexts
  Source/WebCore/dom/DocumentStorageAccess.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ResourceLoadStatistics.mm
Labels: unsafe-merge-queue, Website Storage

#48884 Fix USE(CAIRO) build following 297898@main
  Source/WebCore/platform/graphics/cairo/ImageBufferCairoImageSurfaceBackend.cpp
Labels: unsafe-merge-queue, New Bugs

#48650 [WebXR][OpenXR] Export OpenXR textures to WebProcess for WebGL rendering
  LayoutTests/platform/glib/TestExpectations
  LayoutTests/platform/gtk/imported/w3c/web-platform-tests/webxr/webGLCanvasContext_create_xrcompatible.https-expected.txt
  Source/WebCore/Modules/webxr/WebXROpaqueFramebuffer.cpp
  Source/WebCore/Modules/webxr/WebXROpaqueFramebuffer.h
  Source/WebCore/platform/graphics/GraphicsContextGL.h
  Source/WebCore/platform/graphics/angle/GraphicsContextGLANGLE.cpp
  Source/WebCore/platform/graphics/gbm/GraphicsContextGLTextureMapperGBM.cpp
  Source/WebCore/platform/graphics/gbm/GraphicsContextGLTextureMapperGBM.h
  Source/WebCore/platform/xr/PlatformXR.h
  Source/WebCore/testing/WebFakeXRDevice.cpp
  Source/WebCore/testing/WebFakeXRDevice.h
  Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in
  Source/WebKit/Shared/XR/PlatformXR.serialization.in
  Source/WebKit/UIProcess/XR/PlatformXRSystem.cpp
  Source/WebKit/UIProcess/XR/openxr/OpenXRLayer.cpp
  Source/WebKit/UIProcess/XR/openxr/OpenXRLayer.h
  Source/WebKit/UIProcess/XR/openxr/PlatformXROpenXR.cpp
  Source/WebKit/UIProcess/XR/openxr/PlatformXROpenXR.h
Labels: merge-queue, WebXR

#48887 [WPE] Fix build with external holepunch enabled
  Source/WebCore/platform/graphics/holepunch/MediaPlayerPrivateHolePunch.cpp
Labels: unsafe-merge-queue, WPE WebKit

#48889 [ews] Retrying Apple internal builds do not update corresponding GitHub status-bubbles
  Tools/CISupport/ews-app/ews/common/util.py
Labels: unsafe-merge-queue, New Bugs

#48520 [WebGPU] Fix the WebGPU Swift build
  Source/WTF/wtf/EmbeddedFixedVector.h
  Source/WTF/wtf/FixedVector.h
  Source/WTF/wtf/HashIterators.h
  Source/WTF/wtf/HashMap.h
  Source/WTF/wtf/HashTable.h
  Source/WTF/wtf/SystemMalloc.h
  Source/WebGPU/WGSL/AST/ASTBuilder.h
  Source/WebGPU/WGSL/ConstantValue.h
  Source/WebGPU/WebGPU/Adapter.h
  Source/WebGPU/WebGPU/BindGroup.h
  Source/WebGPU/WebGPU/BindableResource.h
  Source/WebGPU/WebGPU/Buffer.h
  Source/WebGPU/WebGPU/CommandEncoder.h
  Source/WebGPU/WebGPU/CommandEncoder.swift
  Source/WebGPU/WebGPU/Device.h
  Source/WebGPU/WebGPU/Instance.h
  Source/WebGPU/WebGPU/Internal/WebGPUSwiftInternal.h
  Source/WebGPU/WebGPU/WebGPU.h
Labels: merge-queue, WebGPU

#48897 [Gardening]:REGRESSION ( 298022@main): [ Sonoma+ X86_64 WK2 ] 2X fast/webgpu/regression/repro tests are consistent crashes
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: New Bugs

#48871 [JSC] Use 1.5x growth factor for Butterfly
  Source/JavaScriptCore/runtime/JSObject.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#34541 [WTF] Add chunked scanning for codePointCompare
  JSTests/microbenchmarks/string-compare-less.js
  Source/WTF/wtf/text/StringImpl.h
Labels: unsafe-merge-queue, JavaScriptCore

#48901 Unreviewed. Fix non-unified build
  Source/WebKit/WebProcess/Network/webrtc/LibWebRTCNetworkManager.cpp
Labels: unsafe-merge-queue

#48893 Remove remnants of pushnotification event
  Source/WebCore/dom/EventNames.json
  Source/WebCore/workers/service/ServiceWorkerRegistration.cpp
  Source/WebCore/workers/service/context/ServiceWorkerThread.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebPushDaemon.mm
Labels: unsafe-merge-queue, DOM

#48902 Fix the non-JIT JavaScriptCore debug build
  Source/JavaScriptCore/bytecode/ArithProfile.h
Labels: unsafe-merge-queue, JavaScriptCore

#48870 [JSC] Extract CheckInBounds from StringCharCodeAt
  Source/JavaScriptCore/dfg/DFGIntegerRangeOptimizationPhase.cpp
  Source/JavaScriptCore/dfg/DFGSSALoweringPhase.cpp
  Source/JavaScriptCore/dfg/DFGStrengthReductionPhase.cpp
  Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#48807 `git-webkit setup` can fail to install python dependencies when run from a branch
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/setup_unittest.py
Labels: unsafe-merge-queue, Tools / Tests

#48911 [GARDENING]REGRESSION(298121@main): [ iOS, macOS wk2 ] 4x imported/w3c/web-platform-tests/navigation-api/ (layout-tests) tests are constant text failures
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#48923 [Gardening]: [macOS Debug arm64] fast/block/transparent-outline-with-and-without-border-radius.html is a flaky image only failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#48924 [REVERT GARDENING] [ macOS Tahoe ] 8 capability_checks/limits tests are a consistent failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, WebKit Misc.

#48930 [GARDENING][ macOS Sonoma wk2 x86_64 ] imported/w3c/web-platform-tests/css/filter-effects/filters-drop-shadow-002.html is a constant image failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#48484 Web Extensions: Add getSubTree(), getChildren(), and get()
  Source/WebKit/UIProcess/Extensions/Cocoa/API/WebExtensionContextAPIBookmarksCocoa.mm
  Source/WebKit/WebProcess/Extensions/API/Cocoa/WebExtensionAPIBookmarksCocoa.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKWebExtensionAPIBookmarks.mm
Labels: unsafe-merge-queue, WebKit Extensions

#48843 Refactor synthesizedBaseline to take in baseline type and writing mode for synthesis
  Source/WebCore/rendering/BaselineAlignment.cpp
  Source/WebCore/rendering/BaselineAlignment.h
  Source/WebCore/rendering/GridBaselineAlignment.cpp
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/RenderBox.h
  Source/WebCore/rendering/RenderFlexibleBox.cpp
  Source/WebCore/rendering/RenderGrid.cpp
Labels: merge-queue, Layout and Rendering

#48927 Unreviewed, reverting 298022@main (29b363550378)
  LayoutTests/platform/mac-wk2/TestExpectations
  Source/WebGPU/WebGPU/BindGroup.mm
  Source/WebGPU/WebGPU/MetalSPI.h
Labels: merge-queue, WebGPU

#48929 Fix Speedometer3 regression from 297895@main
  Source/WTF/wtf/TZoneMalloc.h
  Source/WebCore/dom/SerializedNode.cpp
  Source/WebCore/dom/SerializedNode.h
  Source/WebKit/Shared/JavaScriptEvaluationResult.cpp
  Source/WebKit/Shared/JavaScriptEvaluationResult.h
  Source/WebKit/Shared/JavaScriptEvaluationResult.mm
  Source/WebKit/Shared/JavaScriptEvaluationResult.serialization.in
  Source/WebKit/Shared/glib/JavaScriptEvaluationResultGLib.cpp
Labels: unsafe-merge-queue, WebKit API

#48900 [WebCore] Remove Self Inclusions
  Source/WebCore/Modules/WebGPU/InternalAPI/WebGPUXRProjectionLayer.h
  Source/WebCore/animation/AnimationEffect.h
  Tools/Scripts/webkitpy/style/checkers/cpp.py
Labels: merge-queue, WebCore Misc.

#48934 Unreviewed, reverting 298217@main (e5f31421894f)
  Source/WebGPU/WebGPU/BindGroup.mm
  Source/WebGPU/WebGPU/MetalSPI.h
Labels: merge-queue, WebGPU

#48905 ANGLE: Add support for WebKit memory profiling
  Source/ThirdParty/ANGLE/ANGLE.xcodeproj/project.pbxproj
  Source/ThirdParty/ANGLE/Configurations/BaseTarget.xcconfig
  Source/ThirdParty/ANGLE/src/common/PoolAlloc.cpp
  Source/ThirdParty/ANGLE/src/common/PoolAlloc.h
  Source/ThirdParty/ANGLE/src/common/PoolAlloc_unittest.cpp
Labels: merge-queue, ANGLE

#48888 [GTK][WPE] Simplify GRefPtr and the way to define specializations
  Source/WTF/wtf/glib/GRefPtr.cpp
  Source/WTF/wtf/glib/GRefPtr.h
  Source/WebCore/Modules/mediastream/gstreamer/GStreamerRtpReceiverTransformBackend.cpp
  Source/WebCore/Modules/mediastream/gstreamer/GStreamerRtpSenderTransformBackend.cpp
  Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h
  Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/WebKitMediaSourceGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/WebKitMediaSourceGStreamer.h
  Source/WebCore/platform/gtk/CursorGtk.cpp
  Source/WebCore/platform/gtk/GRefPtrGtk.cpp
  Source/WebCore/platform/gtk/GRefPtrGtk.h
  Source/WebKit/Shared/gtk/ArgumentCodersGtk.cpp
  Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
  Source/WebKit/UIProcess/API/wpe/WebKitWebViewBackend.cpp
  Source/WebKit/UIProcess/API/wpe/WebKitWebViewBackendPrivate.h
  Source/WebKit/WPEPlatform/wpe/GRefPtrWPE.h
  Tools/TestWebKitAPI/Tests/WTF/glib/GRefPtr.cpp
  Tools/TestWebKitAPI/Tests/WebKitGLib/TestDownloads.cpp
  Tools/TestWebKitAPI/Tests/WebKitGLib/TestResources.cpp
  Tools/TestWebKitAPI/Tests/WebKitGLib/TestSSL.cpp
  Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitPolicyClient.cpp
  Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitUserContentFilterStore.cpp
  Tools/TestWebKitAPI/Tests/WebKitGtk/TestWebKitAccessibility.cpp
  Tools/WebKitTestRunner/gtk/UIScriptControllerGtk.cpp
Labels: unsafe-merge-queue, WebKitGTK

#48876 Don't create fragmented blob made of other blobs with fetch data
  Source/WebCore/Modules/fetch/FetchBodyConsumer.cpp
  Source/WebCore/fileapi/Blob.cpp
  Source/WebCore/fileapi/Blob.h
  Source/WebCore/fileapi/BlobBuilder.cpp
  Source/WebCore/fileapi/BlobBuilder.h
  Source/WebCore/platform/network/BlobPart.h
  Source/WebCore/platform/network/BlobRegistryImpl.cpp
  Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in
Labels: merge-queue, WebCore Misc.

#48366 REGRESSION(296858@main?): Build fails with ENABLE_JOURNALD_LOG=OFF due to static assert in logging macros
  Source/WTF/wtf/Assertions.h
  Source/WTF/wtf/Logger.h
Labels: merge-queue, New Bugs

#48938 Edge corruption after IOSurface purging with lossless compression enabled
  Source/WebCore/platform/graphics/cg/ImageBufferIOSurfaceBackend.cpp
Labels: merge-queue, Compositing

#48955 fatal error: 'bmalloc/TZoneHeap.h' file not found
  Source/WebKit/Platform/IPC/Connection.h
  Source/WebKit/Platform/IPC/Decoder.h
Labels: merge-queue, WebKit2

#48962 Fix internal builds
  Source/WebKit/UIProcess/API/ios/WKWebViewIOS.mm
Labels: unsafe-merge-queue, New Bugs

#48835 [Win] Layout Tests gardening
  LayoutTests/platform/win/TestExpectations
  LayoutTests/platform/win/fast/forms/number/number-min-max-spinbutton-appearance-none-percentage-width-expected.txt
  LayoutTests/platform/win/fast/forms/range/slider-zoomed-expected.txt
  LayoutTests/platform/win/overflow/overflow-transform-perspective-expected.txt
Labels: merge-queue, Tools / Tests

#48963 [Gardening]: REGRESSION(298070@main): [macOS]: Multiple tests in imported/w3c/web-platform-tests/content-security-policy are failing
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#48958 [Style] Remove unused integer value support from Style::LengthWrapperData
  Source/WebCore/style/values/primitives/StyleLengthWrapperData.cpp
  Source/WebCore/style/values/primitives/StyleLengthWrapperData.h
  Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in
Labels: merge-queue, CSS

#48916 [libpas] Re-add PAS_PROFILE for pas_ensure_heap_slow
  Source/bmalloc/libpas/src/libpas/pas_heap_ref.c
Labels: merge-queue, New Bugs

#48968 [GARDENING][ macOS Release ] imported/w3c/web-platform-tests/html/dom/idlharness.worker.html is a flakey text failure
  LayoutTests/platform/mac/TestExpectations
Labels: unsafe-merge-queue

#48940 [JSC] LiteralParser Lexer should not do double-lookup for dispatch
  Source/JavaScriptCore/runtime/LiteralParser.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#48966 Add two new bots to the site-isolation queue
  Tools/CISupport/build-webkit-org/config.json
Labels: merge-queue

#48973 AX: Fix all `whitespace/end_of_line` code style violations
  Source/WebCore/accessibility/AXObjectCache.cpp
  Source/WebCore/accessibility/AXObjectCache.h
  Source/WebCore/accessibility/AXTextStateChangeIntent.h
  Source/WebCore/accessibility/AccessibilityAttachment.cpp
  Source/WebCore/accessibility/AccessibilityAttachment.h
  Source/WebCore/accessibility/AccessibilityImageMapLink.cpp
  Source/WebCore/accessibility/AccessibilityImageMapLink.h
  Source/WebCore/accessibility/AccessibilityLabel.cpp
  Source/WebCore/accessibility/AccessibilityList.cpp
  Source/WebCore/accessibility/AccessibilityList.h
  Source/WebCore/accessibility/AccessibilityListBox.cpp
  Source/WebCore/accessibility/AccessibilityListBox.h
  Source/WebCore/accessibility/AccessibilityListBoxOption.cpp
  Source/WebCore/accessibility/AccessibilityListBoxOption.h
  Source/WebCore/accessibility/AccessibilityMathMLElement.cpp
  Source/WebCore/accessibility/AccessibilityMediaObject.cpp
  Source/WebCore/accessibility/AccessibilityMediaObject.h
  Source/WebCore/accessibility/AccessibilityMenuListOption.cpp
  Source/WebCore/accessibility/AccessibilityMenuListPopup.cpp
  Source/WebCore/accessibility/AccessibilityMockObject.cpp
  Source/WebCore/accessibility/AccessibilityMockObject.h
  Source/WebCore/accessibility/AccessibilityNodeObject.h
  Source/WebCore/accessibility/AccessibilityObject.cpp
  Source/WebCore/accessibility/AccessibilityProgressIndicator.cpp
  Source/WebCore/accessibility/AccessibilityProgressIndicator.h
  Source/WebCore/accessibility/AccessibilityRenderObject.cpp
  Source/WebCore/accessibility/AccessibilityRenderObject.h
  Source/WebCore/accessibility/AccessibilityScrollView.cpp
  Source/WebCore/accessibility/AccessibilityScrollView.h
  Source/WebCore/accessibility/AccessibilityScrollbar.cpp
  Source/WebCore/accessibility/AccessibilityScrollbar.h
  Source/WebCore/accessibility/AccessibilitySlider.cpp
  Source/WebCore/accessibility/AccessibilitySlider.h
  Source/WebCore/accessibility/AccessibilitySpinButton.cpp
  Source/WebCore/accessibility/AccessibilityTable.cpp
  Source/WebCore/accessibility/AccessibilityTable.h
  Source/WebCore/accessibility/AccessibilityTableCell.cpp
  Source/WebCore/accessibility/AccessibilityTableCell.h
  Source/WebCore/accessibility/AccessibilityTableColumn.cpp
  Source/WebCore/accessibility/AccessibilityTableColumn.h
  Source/WebCore/accessibility/AccessibilityTableHeaderContainer.cpp
  Source/WebCore/accessibility/AccessibilityTableHeaderContainer.h
  Source/WebCore/accessibility/AccessibilityTableRow.cpp
  Source/WebCore/accessibility/AccessibilityTableRow.h
  Source/WebCore/accessibility/AccessibilityTree.cpp
  Source/WebCore/accessibility/AccessibilityTree.h
  Source/WebCore/accessibility/AccessibilityTreeItem.cpp
  Source/WebCore/accessibility/AccessibilityTreeItem.h
  Source/WebCore/accessibility/atspi/AccessibilityAtspi.cpp
  Source/WebCore/accessibility/atspi/AccessibilityObjectAtspi.h
  Source/WebCore/accessibility/ios/AccessibilityObjectIOS.mm
  Source/WebCore/accessibility/ios/WebAccessibilityObjectWrapperIOS.mm
  Source/WebCore/accessibility/isolatedtree/AXIsolatedObject.cpp
  Source/WebCore/accessibility/isolatedtree/AXIsolatedObject.h
  Source/WebCore/accessibility/mac/AccessibilityObjectMac.mm
  Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperBase.mm
  Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm
  Source/WebCore/accessibility/win/AXObjectCacheWin.cpp
  Source/WebCore/accessibility/win/AccessibilityObjectWrapperWin.h
Labels: merge-queue

#48980 [GARDENING[[ iOS Release, macOS wk2 ] imported/w3c/web-platform-tests/webrtc/RTCDataChannel-GC.html is a flakey text failure
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#48960 User installed fonts located outside of ~/Library/Fonts and /Library/Fonts are not rendered
  Source/WebCore/platform/LogMessages.in
  Source/WebKit/Scripts/process-entitlements.sh
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/com.apple.WebProcess.sb.in
Labels: unsafe-merge-queue, WebKit Process Model

#48988 [Gardening]: REGRESSION(298124@main): [MacOS x86_64] imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-denormals.https.window.html is a constant failure
  LayoutTests/platform/mac/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#48983 Add a feature flag for Largest Contentful Paint
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: merge-queue, Layout and Rendering

#48977 [Form Control Refresh] Disabled checkbox and submit controls may fail to repaint for window inactive state
  Source/WebCore/rendering/RenderTheme.cpp
  Source/WebCore/rendering/RenderTheme.h
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.h
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.mm
  Source/WebCore/rendering/mac/RenderThemeMac.mm
Labels: merge-queue, New Bugs

#48978 Increase FD limit for GPUProcess and NetworkProcess
  Source/WebKit/GPUProcess/cocoa/GPUProcessCocoa.mm
  Source/WebKit/NetworkProcess/cocoa/NetworkProcessCocoa.mm
  Source/WebKit/Resources/SandboxProfiles/ios/com.apple.WebKit.GPU.sb.in
  Source/WebKit/Shared/AuxiliaryProcess.h
  Source/WebKit/Shared/Cocoa/AuxiliaryProcessCocoa.mm
Labels: merge-queue, WebKit Misc.

#48994 [Win] Fix release build broken by AXObjectCache
  Source/WebCore/accessibility/AXObjectCache.cpp
Labels: unsafe-merge-queue

#48975 Pointer Lock API tests should run on iOS
  Source/WTF/wtf/PlatformEnableCocoa.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/UIDelegate.mm
Labels: unsafe-merge-queue, Platform

#48879 [WebIDL] Ensure [Reflect] extended attribute value is provided as a string when used with [Enumerated]
  Source/WebCore/bindings/scripts/CodeGenerator.pm
  Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
  Source/WebCore/bindings/scripts/test/JS/JSTestObj.cpp
  Source/WebCore/bindings/scripts/test/TestObj.idl
Labels: merge-queue, New Bugs

#48947 [WebXR] AR mode should support stereo rendering
  Source/WebCore/Modules/webxr/WebXRWebGLLayer.cpp
  Source/WebKit/Shared/XR/XRDeviceProxy.cpp
Labels: merge-queue, WebXR

#45692 [WPE] Extract common logic from EventSenderProxyClientWPE touch event handling
  Tools/WebKitTestRunner/wpe/EventSenderProxyClientWPE.cpp
  Tools/WebKitTestRunner/wpe/EventSenderProxyClientWPE.h
Labels: merge-queue, WPE WebKit

#49000 [iOS] Add test coverage for mouse availability based gating of pointer lock
  Tools/TestWebKitAPI/Tests/WebKitCocoa/UIDelegate.mm
Labels: unsafe-merge-queue, Platform

#49011 [GARDENING] [ iOS ] http/tests/local/blob/navigate-blob.html is a flakey text failure
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#49007 REGRESSION(298252@main): Introduced new clang warnings
  Source/WebCore/accessibility/AXLoggerBase.h
Labels: unsafe-merge-queue, Accessibility

#48953 [Site Isolation] Make tooltips work with site isolation.
  LayoutTests/http/tests/site-isolation/mouse-events/iframes-with-tooltips-expected.txt
  LayoutTests/http/tests/site-isolation/mouse-events/iframes-with-tooltips.html
  LayoutTests/http/tests/site-isolation/mouse-events/resources/tooltip-subframe-a.html
  LayoutTests/http/tests/site-isolation/mouse-events/resources/tooltip-subframe-b.html
  Source/WebCore/page/EventHandler.cpp
  Source/WebKit/Shared/WebHitTestResultData.cpp
  Source/WebKit/Shared/WebHitTestResultData.h
  Source/WebKit/Shared/WebHitTestResultData.serialization.in
  Source/WebKit/UIProcess/API/APIUIClient.h
  Source/WebKit/UIProcess/API/C/WKPage.cpp
  Source/WebKit/UIProcess/API/C/WKPageUIClient.h
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/mac/WebPageProxyMac.mm
  Tools/WebKitTestRunner/InjectedBundle/Bindings/TestRunner.idl
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestController.cpp
  Tools/WebKitTestRunner/TestController.h
  Tools/WebKitTestRunner/TestInvocation.cpp
  Tools/WebKitTestRunner/TestInvocation.h
Labels: merge-queue, WebKit Misc.

#49016 [GARDENING] [ iOS, macOS wk2 ] media/webaudio-background-playback.html is a flakey text failure
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue

#49013 EditingStyle: rename forceInline to forceDisplayInline
  Source/WebCore/editing/EditingStyle.cpp
  Source/WebCore/editing/EditingStyle.h
  Source/WebCore/editing/markup.cpp
Labels: HTML Editing

#49019 Add two new bots to the site-isolation queue
  Tools/CISupport/build-webkit-org/config.json
Labels: unsafe-merge-queue

#48756 [WebGPU] After 32 timestamp queries are created, subsequent query sets may fail to create
  Source/WebGPU/WebGPU/CommandEncoder.mm
  Source/WebGPU/WebGPU/QuerySet.h
  Source/WebGPU/WebGPU/QuerySet.mm
Labels: merge-queue, WebGPU

#48367 Annotate CookieStoreAPIEnabled endpoints with feature flag
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.messages.in
Labels: merge-queue, New Bugs

#48969 [Fuzzilli] Ignore static initializer linker errors when building JavaScriptCore.framework
  Configurations/Sanitizers.xcconfig
Labels: unsafe-merge-queue, JavaScriptCore

#49023 Clear sandbox extension cache on memory pressure
  Source/WebKit/UIProcess/WebProcessPool.cpp
Labels: unsafe-merge-queue, WebKit Process Model

#48586 [SVG] Use `currentViewBoxRect()` for intrinsic ratio calculation
  LayoutTests/TestExpectations
  Source/WebCore/rendering/svg/RenderSVGRoot.cpp
  Source/WebCore/rendering/svg/legacy/LegacyRenderSVGRoot.cpp
Labels: merge-queue, SVG

#49029 Fix SDK checks in WebGPU.h
  Source/WebGPU/WebGPU/WebGPU.h
Labels: unsafe-merge-queue, WebGPU

#48999 [Screen Time] Screen Time Website Data may not be cleared properly with multiple Safari profiles
  Source/WebKit/UIProcess/WebsiteData/Cocoa/ScreenTimeWebsiteDataSupport.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ScreenTime.mm
Labels: unsafe-merge-queue, WebKit Misc.

#48776 Protect Local/Session storage ipc endpoints
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/bindings/js/WebCoreBuiltinNames.h
  Source/WebCore/page/LocalDOMWindow.cpp
  Source/WebCore/page/WindowLocalStorage.idl
  Source/WebCore/page/WindowSessionStorage.idl
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.cpp
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.h
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.messages.in
Labels: merge-queue, New Bugs

#49035 [GARDENING][ iOS Release ] http/tests/app-privacy-report/app-attribution-beacon-isappinitiated.html is a flaky text failure
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#48997 document.caretPositionFromPoint returns null over SVG elements and elements with `-webkit-user-select: none`
  LayoutTests/fast/shadow-dom/cannot-hit-test-into-shadow-media-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/cssom/caretPositionFromPoint-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/cssom/caretPositionFromPoint.html
  Source/WebCore/accessibility/AccessibilityNodeObject.cpp
  Source/WebCore/accessibility/AccessibilityObject.cpp
  Source/WebCore/dom/Position.cpp
  Source/WebCore/dom/Position.h
  Source/WebCore/editing/Editing.cpp
  Source/WebCore/editing/FrameSelection.cpp
  Source/WebCore/editing/VisibleUnits.cpp
  Source/WebCore/editing/cocoa/DataDetection.mm
  Source/WebCore/page/EventHandler.cpp
  Source/WebCore/page/EventHandler.h
  Source/WebCore/page/LocalFrame.cpp
  Source/WebCore/rendering/RenderBlock.cpp
  Source/WebCore/rendering/RenderBlock.h
  Source/WebCore/rendering/RenderBlockFlow.cpp
  Source/WebCore/rendering/RenderBlockFlow.h
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/RenderBox.h
  Source/WebCore/rendering/RenderFileUploadControl.cpp
  Source/WebCore/rendering/RenderFileUploadControl.h
  Source/WebCore/rendering/RenderFragmentContainer.cpp
  Source/WebCore/rendering/RenderFragmentContainer.h
  Source/WebCore/rendering/RenderInline.cpp
  Source/WebCore/rendering/RenderInline.h
  Source/WebCore/rendering/RenderLineBreak.cpp
  Source/WebCore/rendering/RenderLineBreak.h
  Source/WebCore/rendering/RenderMultiColumnSet.cpp
  Source/WebCore/rendering/RenderMultiColumnSet.h
  Source/WebCore/rendering/RenderObject.cpp
  Source/WebCore/rendering/RenderObject.h
  Source/WebCore/rendering/RenderReplaced.cpp
  Source/WebCore/rendering/RenderReplaced.h
  Source/WebCore/rendering/RenderText.cpp
  Source/WebCore/rendering/RenderText.h
  Source/WebCore/rendering/svg/RenderSVGInlineText.cpp
  Source/WebCore/rendering/svg/RenderSVGInlineText.h
  Source/WebCore/rendering/svg/RenderSVGText.cpp
  Source/WebCore/rendering/svg/RenderSVGText.h
  Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm
Labels: unsafe-merge-queue, DOM

#49025 Refactor EditingStyle::removeStyleFromRulesAndContext into 3 parts
  Source/WebCore/editing/EditingStyle.cpp
  Source/WebCore/editing/EditingStyle.h
Labels: merge-queue, HTML Editing

#48659 [JSC] Implement `Set.prototype.union` in C++
  JSTests/microbenchmarks/set-prototype-union-large-other.js
  JSTests/microbenchmarks/set-prototype-union-large-this.js
  JSTests/microbenchmarks/set-prototype-union.js
  JSTests/stress/array-prototype-slice-to-number-error.js
  JSTests/stress/set-prototype-union-empty-sets.js
  JSTests/stress/set-prototype-union-generic-object.js
  JSTests/stress/set-prototype-union-iterator-effects.js
  JSTests/stress/set-union-cursor-reference.js
  JSTests/stress/set-union-iteration-reference.js
  JSTests/stress/set-union-reference.js
  Source/JavaScriptCore/builtins/SetPrototype.js
  Source/JavaScriptCore/runtime/SetPrototype.cpp
Labels: merge-queue, JavaScriptCore

#48944 [Form Control Refresh] `accent-color` should preserve control legibility
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-checkbox-radio-do-not-disappear-dark-mode-expected-mismatch.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-checkbox-radio-do-not-disappear-dark-mode.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-checkbox-radio-do-not-disappear-light-mode-expected-mismatch.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-checkbox-radio-do-not-disappear-light-mode.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-does-not-affect-inactive-window-dark-mode-expected.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-does-not-affect-inactive-window-dark-mode.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-does-not-affect-inactive-window-light-mode-expected.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-does-not-affect-inactive-window-light-mode.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-submit-does-not-disappear-expected-mismatch.html
  LayoutTests/fast/forms/form-control-refresh/accent-color-contrast-submit-does-not-disappear.html
  Source/WebCore/rendering/RenderTheme.h
  Source/WebCore/rendering/TextPaintStyle.cpp
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.h
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.mm
  Source/WebCore/rendering/style/RenderStyle.cpp
  Source/WebCore/rendering/style/RenderStyle.h
  Source/WebCore/rendering/style/RenderStyleInlines.h
  Source/WebCore/rendering/style/RenderStyleSetters.h
  Source/WebCore/rendering/style/StyleRareInheritedData.cpp
  Source/WebCore/rendering/style/StyleRareInheritedData.h
Labels: unsafe-merge-queue, CSS

#49041 JSON modules should always be loaded as UTF-8
  LayoutTests/imported/w3c/web-platform-tests/html/semantics/scripting-1/the-script-element/json-module/charset-bom.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/semantics/scripting-1/the-script-element/json-module/charset-bom.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/semantics/scripting-1/the-script-element/json-module/charset-bom.any.worker-expected.txt
  Source/JavaScriptCore/parser/SourceProvider.h
  Source/WebCore/bindings/js/CachedScriptSourceProvider.h
  Source/WebCore/bindings/js/WorkerModuleScriptLoader.cpp
  Source/WebCore/workers/WorkerScriptLoader.cpp
  Source/WebCore/workers/WorkerScriptLoader.h
Labels: unsafe-merge-queue, New Bugs

#49040 WebKit doesn't resize SVG element in response to viewBox change (with height specified and width unspecified)
  LayoutTests/imported/w3c/web-platform-tests/svg/coordinate-systems/outer-svg-intrinsic-size-001-expected.txt
  Source/WebCore/svg/SVGSVGElement.cpp
Labels: merge-queue, SVG

#49051 StabilityTracer: com.apple.WebKit.GPU at WebCore: void std::__1::map<std::__1::pair<WTF::MediaTime, WTF::MediaTime>, WTF::Ref<WebCore::MediaSample, WTF::RawPtrTraits<WebCore::MediaSample>,
  Source/WebCore/Modules/mediasource/SampleMap.cpp
  Source/WebCore/Modules/mediasource/SampleMap.h
  Source/WebCore/platform/graphics/SourceBufferPrivate.cpp
  Tools/TestWebKitAPI/Tests/WebCore/SampleMap.cpp
Labels: merge-queue, Media

#48957 Move implementation for methods using inline-declared methods out from headers
  Source/WebCore/Modules/WebGPU/GPUDevice.cpp
  Source/WebCore/Modules/WebGPU/GPUDevice.h
  Source/WebCore/Modules/mediasource/SourceBuffer.cpp
  Source/WebCore/Modules/mediasource/SourceBuffer.h
  Source/WebCore/Modules/mediastream/MediaDevices.cpp
  Source/WebCore/Modules/mediastream/MediaDevices.h
  Source/WebCore/Modules/mediastream/MediaStream.cpp
  Source/WebCore/Modules/mediastream/MediaStream.h
  Source/WebCore/Modules/mediastream/RTCDataChannel.cpp
  Source/WebCore/Modules/mediastream/RTCDataChannel.h
  Source/WebCore/Modules/mediastream/RTCDtlsTransport.cpp
  Source/WebCore/Modules/mediastream/RTCDtlsTransport.h
  Source/WebCore/Modules/mediastream/RTCRtpSFrameTransform.cpp
  Source/WebCore/Modules/mediastream/RTCRtpSFrameTransform.h
  Source/WebCore/Modules/webcodecs/WebCodecsBase.cpp
  Source/WebCore/Modules/webcodecs/WebCodecsBase.h
  Source/WebCore/Modules/webdatabase/DatabaseContext.cpp
  Source/WebCore/Modules/webdatabase/DatabaseContext.h
  Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunction.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunction.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionGenerateIsReachable.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionGenerateIsReachable.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithThisObject.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithThisObject.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithTypedefs.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithTypedefs.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithVariadic.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackFunctionWithVariadic.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackInterface.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackInterface.h
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackWithFunctionOrDict.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestCallbackWithFunctionOrDict.h
  Source/WebCore/bindings/scripts/test/JS/JSTestVoidCallbackFunction.cpp
  Source/WebCore/bindings/scripts/test/JS/JSTestVoidCallbackFunction.h
  Source/WebCore/dom/ViewTransition.cpp
  Source/WebCore/dom/ViewTransition.h
  Source/WebCore/html/MediaController.cpp
  Source/WebCore/html/MediaController.h
  Source/WebCore/html/track/TrackListBase.cpp
  Source/WebCore/html/track/TrackListBase.h
  Source/WebCore/page/IntersectionObserver.cpp
  Source/WebCore/page/IntersectionObserver.h
  Source/WebCore/rendering/LegacyInlineBox.cpp
  Source/WebCore/rendering/LegacyInlineBox.h
  Source/WebCore/rendering/mathml/RenderMathMLFraction.cpp
  Source/WebCore/rendering/mathml/RenderMathMLFraction.h
  Source/WebCore/rendering/mathml/RenderMathMLSpace.cpp
  Source/WebCore/rendering/mathml/RenderMathMLSpace.h
  Source/WebCore/workers/service/background-fetch/BackgroundFetchRegistration.cpp
  Source/WebCore/workers/service/background-fetch/BackgroundFetchRegistration.h
  Source/WebCore/xml/XMLHttpRequestProgressEventThrottle.cpp
  Source/WebCore/xml/XMLHttpRequestProgressEventThrottle.h
Labels: merge-queue, WebCore Misc.

#48996 SharedBufferBuilder copy constructor should not take reference of original FragmentedSharedBuffer
  Source/WebCore/bindings/js/ScriptBufferSourceProvider.h
  Source/WebCore/bindings/js/WebAssemblyScriptBufferSourceProvider.h
  Source/WebCore/platform/SharedBuffer.cpp
  Source/WebCore/platform/SharedBuffer.h
  Source/WebCore/workers/ScriptBuffer.cpp
  Source/WebCore/workers/ScriptBuffer.h
  Source/WebCore/workers/service/server/SWScriptStorage.cpp
Labels: merge-queue, WebCore Misc.

#47564 [MSE][GStreamer] don't push samples while seeking
  Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/MediaSourcePrivateGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/MediaSourcePrivateGStreamer.h
  Source/WebCore/platform/graphics/gstreamer/mse/SourceBufferPrivateGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/SourceBufferPrivateGStreamer.h
Labels: merge-queue, New Bugs

#49008 [CSS] Use a function to visit simple selectors
  Source/WebCore/css/CSSSelector.cpp
  Source/WebCore/css/CSSSelector.h
Labels: merge-queue, New Bugs

#49024 Unreviewed warnings fix
  Tools/TestWebKitAPI/Tests/WebKitGtk/InspectorTestServer.cpp
Labels: merge-queue, JavaScriptCore

#47843 Add performJITMemcpyAtomic and simplify jit copying code.
  Source/JavaScriptCore/assembler/ARM64Assembler.h
  Source/JavaScriptCore/assembler/ARMv7Assembler.h
  Source/JavaScriptCore/assembler/AbstractMacroAssembler.h
  Source/JavaScriptCore/assembler/AssemblerCommon.h
  Source/JavaScriptCore/assembler/LinkBuffer.cpp
  Source/JavaScriptCore/assembler/MacroAssemblerARM64.h
  Source/JavaScriptCore/assembler/MacroAssemblerARMv7.h
  Source/JavaScriptCore/assembler/RISCV64Assembler.h
  Source/JavaScriptCore/assembler/X86Assembler.h
  Source/JavaScriptCore/jit/ExecutableAllocator.cpp
  Source/JavaScriptCore/jit/ExecutableAllocator.h
  Source/JavaScriptCore/runtime/OptionsList.h
  Source/WTF/wtf/OptionSet.h
  Source/WTF/wtf/StdLibExtras.h
Labels: merge-queue, JavaScriptCore

#49061 ews151 is failing buildbot unit-tests on Services-EWS due to missing packages
  Tools/Scripts/webkitpy/autoinstalled/buildbot.py
Labels: unsafe-merge-queue

#49062 [GARDENING][iOS] fast/events/ios/rotation/basic-rotation.html is flaky failing
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, UI Events

#48338 [build.webkit.org] Convert CompileWebKit to new style buildstep
  Tools/CISupport/build-webkit-org/steps.py
  Tools/CISupport/build-webkit-org/steps_unittest.py
Labels: New Bugs

#49057 [build.webkit.org] Stop silencing old-style build step deprecation warnings
  Tools/CISupport/build-webkit-org/master.cfg
Labels: unsafe-merge-queue, New Bugs

#49042 Remove unused RenderSVGTextPath::m_layoutPath
  Source/WebCore/rendering/svg/RenderSVGTextPath.h
Labels: merge-queue, SVG

#49001 Restrict location.protocol setter to HTTP(S) schemes
  LayoutTests/TestExpectations
  LayoutTests/imported/w3c/resources/resource-files.json
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/assign-replace-from-top-to-nested-iframe.html
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/location_hash_set_empty_string-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/location_hash_set_empty_string.html
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/location_hashchange_infinite_loop-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/location_hashchange_infinite_loop.html
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/resources/w3c-import.log
  LayoutTests/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/w3c-import.log
  Source/WebCore/page/Location.cpp
Labels: merge-queue, WebCore Misc.

#49036 Switch to TextIndicator for DragDropInteractionState.
  Source/WebKit/UIProcess/ios/DragDropInteractionState.h
  Source/WebKit/UIProcess/ios/DragDropInteractionState.mm
  Source/WebKit/UIProcess/ios/WKContentViewInteraction.h
  Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm
Labels: merge-queue, WebKit Misc.

#49063 Fonts located in application bundles should not be registered in the WebContent process
  Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
Labels: unsafe-merge-queue, WebKit Process Model

#49052 [OpenXR] The XrInstance is not needed inside OpenXRSwapchain
  Source/WebKit/UIProcess/XR/openxr/OpenXRSwapchain.cpp
  Source/WebKit/UIProcess/XR/openxr/OpenXRSwapchain.h
  Source/WebKit/UIProcess/XR/openxr/PlatformXROpenXR.cpp
Labels: merge-queue, WebXR

#49078 [GARDENING][ iOS, macOS ] fast/forms/state-restore-form-associated-custom-elements.html is a flaky timeout
  LayoutTests/platform/mac/TestExpectations
Labels: unsafe-merge-queue

#49030 Add Anthony Tarbinian to contributor list
  metadata/contributors.json
Labels: merge-queue, Tools / Tests

#49076 [Win] Skip crashing interaction-count-tap test
  LayoutTests/platform/win/TestExpectations
Labels: unsafe-merge-queue

#49069 Condense option flags for revealSelection.
  Source/WebCore/dom/Element.cpp
  Source/WebCore/editing/Editor.cpp
  Source/WebCore/editing/FrameSelection.cpp
  Source/WebCore/editing/FrameSelection.h
  Source/WebCore/page/ContextMenuController.cpp
  Source/WebCore/page/Page.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/ios/FindControllerIOS.mm
  Source/WebKitLegacy/mac/WebView/WebFrame.mm
  Source/WebKitLegacy/mac/WebView/WebHTMLView.mm
Labels: merge-queue, WebKit Misc., safe-merge-queue

#49032 [Safer CPP] Address issues in ExternalTexture
  Source/WebGPU/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebGPU/SaferCPPExpectations/UnretainedLocalVarsCheckerExpectations
  Source/WebGPU/WebGPU/ExternalTexture.mm
Labels: merge-queue, New Bugs

#48789 Annotate endpoints using StorageAccessAPIEnabled
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/dom/Document+StorageAccess.idl
  Source/WebCore/dom/DocumentStorageAccess.cpp
  Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.messages.in
  Source/WebKit/WebProcess/WebCoreSupport/WebLocalFrameLoaderClient.cpp
  Source/WebKit/WebProcess/WebCoreSupport/WebResourceLoadObserver.cpp
Labels: merge-queue, New Bugs

#49046 [JSC] Remove ExpressionErrorClassifier
  JSTests/stress/destructuring-assignment-syntax.js
  JSTests/test262/expectations.yaml
  LayoutTests/js/parser-syntax-check-expected.txt
  Source/JavaScriptCore/parser/Parser.cpp
  Source/JavaScriptCore/parser/Parser.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKWebViewEvaluateJavaScript.mm
Labels: unsafe-merge-queue, JavaScriptCore

#49088 [Gardening]: [macOS Debug arm64] fast/parser/entity-comment-in-style.html is flaky timeout
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#49084 [JSC] JSC should not depend on pas_lock.h
  Source/bmalloc/CMakeLists.txt
  Source/bmalloc/bmalloc.xcodeproj/project.pbxproj
  Source/bmalloc/libpas/src/libpas/pas_backtrace_metadata.h
  Source/bmalloc/libpas/src/libpas/pas_probabilistic_guard_malloc_allocator.h
  Source/bmalloc/libpas/src/libpas/pas_report_crash_pgm_report.h
Labels: merge-queue, WebKit Misc.

#49090 [GARDENING][ iOS ] http/tests/resourceLoadStatistics/exemptDomains/managed-domains-cookieEnabled.html is a flakey failure
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue

#49081 REGRESSION(298142@main): Web content may be temporarily offset during Safari View Controller presentation
  Source/WebKit/UIProcess/API/ios/WKWebViewIOS.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/AnimatedResize.mm
Labels: unsafe-merge-queue, New Bugs

#49075 Turn `WorkerAsynchronousURLErrorHandlingEnabled` on by default
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: merge-queue, New Bugs

#49026 Move Node inline functions from ShadowRoot.h to NodeInlines.h
  Source/WebCore/dom/Node.h
  Source/WebCore/dom/NodeInlines.h
  Source/WebCore/dom/ShadowRoot.h
  Source/WebCore/editing/FrameSelection.cpp
  Source/WebCore/editing/TextIterator.cpp
  Source/WebCore/editing/VisibleSelection.cpp
  Source/WebCore/editing/markup.cpp
  Source/WebCore/html/HTMLFrameOwnerElement.cpp
  Source/WebCore/inspector/agents/InspectorDOMAgent.cpp
  Source/WebCore/rendering/RenderTreeAsText.cpp
  Source/WebCore/svg/SVGElement.cpp
Labels: merge-queue, New Bugs

#49071 Web Inspector: Elements: Layout details sidebar shows up when selecting HTML comment nodes
  Source/WebInspectorUI/UserInterface/Views/LayoutDetailsSidebarPanel.js
Labels: unsafe-merge-queue, Web Inspector

#49114 error: call to non-‘constexpr’ function ‘double WebCore::DoubleSize::width() const’
  Source/WebCore/platform/graphics/DoubleSize.h
Labels: unsafe-merge-queue, WebCore Misc.

#49111 Minor correction to CSS Typed OM IDL
  Source/WebCore/css/typedom/CSSUnparsedValue.idl
  Source/WebCore/css/typedom/transform/CSSTransformValue.idl
Labels: unsafe-merge-queue, WebCore Misc.

#49115 [WPE] WPEViewWayland.cpp:602:15: warning: variable 'annotator' set but not used [-Wunused-but-set-variable]
  Source/WebKit/UIProcess/XR/openxr/OpenXRLayer.cpp
  Source/WebKit/WPEPlatform/wpe/wayland/WPEViewWayland.cpp
Labels: unsafe-merge-queue, WPE WebKit

#49056 [WebGPU] Fix the webGpuSwift build
  Source/WebGPU/Configurations/WebGPU.xcconfig
  Source/WebGPU/WebGPU/CommandEncoder.swift
  Source/WebGPU/WebGPU/QuerySet.h
  Source/WebGPU/WebGPU/QuerySet.mm
Labels: merge-queue, WebGPU
