Repository WebKit/WebKit, pull requests merged in 2025-10, with the labels that each got.

#51597 REGRESSION(297365@main): ASSERT(m_receivers.isEmpty()) when debugging Web process with show layer borders enabled
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerWithRemoteRenderingBackingStore.mm
Labels: merge-queue, WebKit2

#51532 [LCP] Implement LargestContentfulPaint for text
  LayoutTests/TestExpectations
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/element-only-when-fully-active-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/first-letter-background-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/first-paint-equals-lcp-text-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/image-full-viewport-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/larger-text-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/observe-css-generated-text-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/observe-mathml-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/observe-random-namespace-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/observe-text-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/text-with-display-style-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/toJSON-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/transparent-text-with-shadow-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/transparent-text-with-text-stroke-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/update-on-style-change-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/web-font-styled-text-resize-block-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/largest-contentful-paint/web-font-styled-text-resize-swap-smaller-expected.txt
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/requestidlecallback/requestidlecallback-deadline-shortened-by-rendering-update.html
  Source/WebCore/dom/Document.cpp
  Source/WebCore/dom/Document.h
  Source/WebCore/page/LargestContentfulPaint.cpp
  Source/WebCore/page/LargestContentfulPaint.h
  Source/WebCore/page/LargestContentfulPaintData.cpp
  Source/WebCore/page/LargestContentfulPaintData.h
  Source/WebCore/rendering/TextBoxPainter.cpp
  Source/WebCore/rendering/svg/SVGRenderSupport.cpp
Labels: merge-queue, DOM

#37238 Implement flushAndCollectHandles for in-process RemoteLayerBackingStores.
  Source/WebKit/GPUProcess/graphics/RemoteImageBufferSet.cpp
  Source/WebKit/GPUProcess/graphics/RemoteImageBufferSet.h
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.cpp
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.h
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.messages.in
  Source/WebKit/Scripts/webkit/messages.py
  Source/WebKit/Scripts/webkit/tests/MessageArgumentDescriptions.cpp
  Source/WebKit/Shared/ImageBufferSetIdentifier.h
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerBackingStore.h
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerBackingStore.mm
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerTree.serialization.in
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerWithInProcessRenderingBackingStore.h
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerWithInProcessRenderingBackingStore.mm
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerWithRemoteRenderingBackingStore.h
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerWithRemoteRenderingBackingStore.mm
  Source/WebKit/Shared/WTFArgumentCoders.serialization.in
  Source/WebKit/Shared/graphics/ImageBufferSet.h
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.h
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.messages.in
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.mm
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Source/WebKit/WebProcess/GPU/graphics/PrepareBackingStoreBuffersData.h
  Source/WebKit/WebProcess/GPU/graphics/PrepareBackingStoreBuffersData.serialization.in
  Source/WebKit/WebProcess/GPU/graphics/RemoteImageBufferSetProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteImageBufferSetProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.messages.in
  Source/WebKit/WebProcess/WebPage/RemoteLayerTree/RemoteLayerTreeDrawingArea.mm
Labels: WebKit2

#49869 Add a HUD overlay for showing slow rendering updates.
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.h
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.mm
  Source/WebKit/UIProcess/WebPageProxy.cpp
Labels: merge-queue, WebKit2

#51555 [JSC] Enable Fuzzilli build with CMake
  Source/JavaScriptCore/shell/CMakeLists.txt
  Source/cmake/OptionsJSCOnly.cmake
Labels: merge-queue, JavaScriptCore

#51449 [JSC] Support `Promise.race` in async stack trace
  JSTests/stress/async-stack-trace-promise-race-basic.js
  Source/JavaScriptCore/builtins/PromiseConstructor.js
  Source/JavaScriptCore/interpreter/Interpreter.cpp
Labels: merge-queue, JavaScriptCore

#51581 Move m_forceRepaint from testRunner.h to the UI Process
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.cpp
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.h
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundlePage.cpp
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundlePage.h
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestInvocation.cpp
  Tools/WebKitTestRunner/TestInvocation.h
Labels: merge-queue, Tools / Tests

#51547 Suppress some Safer CPP false positives in the UIProcess
  Source/WebKit/SaferCPPExpectations/RetainPtrCtorAdoptCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/Cocoa/ModelElementControllerCocoa.mm
  Source/WebKit/UIProcess/Cocoa/WebPageProxyCocoa.mm
  Source/WebKit/UIProcess/Gamepad/mac/UIGamepadProviderMac.mm
Labels: merge-queue, WebKit2

#50468 Temporal: Reimplement TemporalDuration::total() according to the spec
  JSTests/stress/temporal-duration.js
  JSTests/test262/config.yaml
  JSTests/test262/expectations.yaml
  Source/JavaScriptCore/Sources.txt
  Source/JavaScriptCore/runtime/FractionToDouble.cpp
  Source/JavaScriptCore/runtime/FractionToDouble.h
  Source/JavaScriptCore/runtime/ISO8601.cpp
  Source/JavaScriptCore/runtime/ISO8601.h
  Source/JavaScriptCore/runtime/TemporalDuration.cpp
  Source/JavaScriptCore/runtime/TemporalObject.cpp
  Source/JavaScriptCore/runtime/TemporalObject.h
Labels: unsafe-merge-queue, request-merge-queue

#51586 Add typed array constructor support for byte streams
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.worker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/patched-global.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/patched-global.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/patched-global.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/patched-global.any.worker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.worker-expected.txt
  Source/WebCore/Modules/streams/ReadableByteStreamController.cpp
Labels: merge-queue

#51587 ReadableStream constructor should rethrow start exceptions
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.worker-expected.txt
  Source/WebCore/Modules/streams/ReadableByteStreamController.cpp
Labels: merge-queue

#51534 [css-anchor-position-1] Rework re-generating position option when applying it changes scroll container size
  Source/WebCore/rendering/style/PositionTryFallback.cpp
  Source/WebCore/rendering/style/PositionTryFallback.h
  Source/WebCore/style/StyleExtractorConverter.h
  Source/WebCore/style/StyleExtractorSerializer.h
  Source/WebCore/style/StyleTreeResolver.cpp
  Source/WebCore/style/StyleTreeResolver.h
Labels: merge-queue, CSS

#51558 [OpenXR] khrSimpleControllerName and handInteractionProfileName are really paths not names
  Source/WebKit/UIProcess/XR/openxr/OpenXRInputMappings.h
  Source/WebKit/UIProcess/XR/openxr/OpenXRInputSource.cpp
Labels: merge-queue, WebXR

#51606 Address some Safer CPP warnings in Source/JavaScriptCore/inspector
  Source/JavaScriptCore/SaferCPPExpectations/RetainPtrCtorAdoptCheckerExpectations
  Source/JavaScriptCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/JavaScriptCore/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
  Source/JavaScriptCore/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/JavaScriptCore/SaferCPPExpectations/UnretainedLocalVarsCheckerExpectations
  Source/JavaScriptCore/inspector/InspectorBackendDispatcher.cpp
  Source/JavaScriptCore/inspector/JSGlobalObjectDebugger.cpp
  Source/JavaScriptCore/inspector/JSGlobalObjectDebugger.h
  Source/JavaScriptCore/inspector/agents/InspectorTargetAgent.cpp
  Source/JavaScriptCore/inspector/remote/RemoteConnectionToTarget.h
  Source/JavaScriptCore/inspector/remote/RemoteInspectionTarget.cpp
  Source/JavaScriptCore/inspector/remote/RemoteInspector.cpp
  Source/JavaScriptCore/inspector/remote/cocoa/RemoteConnectionToTargetCocoa.mm
  Source/JavaScriptCore/inspector/remote/cocoa/RemoteInspectorCocoa.mm
  Source/JavaScriptCore/inspector/remote/cocoa/RemoteInspectorXPCConnection.h
  Source/JavaScriptCore/inspector/remote/cocoa/RemoteInspectorXPCConnection.mm
Labels: merge-queue, Web Inspector

#51251 NativeImages are slow to create from remote contexts
  Source/WebCore/platform/graphics/Gradient.cpp
  Source/WebCore/platform/graphics/NativeImage.cpp
  Source/WebCore/platform/graphics/NativeImage.h
  Source/WebCore/platform/graphics/RenderingResource.h
  Source/WebCore/platform/graphics/cg/NativeImageCG.cpp
  Source/WebCore/platform/graphics/displaylists/DisplayList.cpp
  Source/WebCore/platform/graphics/filters/FilterFunction.cpp
  Source/WebKit/GPUProcess/graphics/RemoteImageBuffer.cpp
  Source/WebKit/GPUProcess/graphics/RemoteImageBuffer.h
  Source/WebKit/GPUProcess/graphics/RemoteImageBuffer.messages.in
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.cpp
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.h
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.messages.in
  Source/WebKit/GPUProcess/graphics/RemoteResourceCache.cpp
  Source/WebKit/GPUProcess/graphics/RemoteResourceCache.h
  Source/WebKit/Sources.txt
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Source/WebKit/WebProcess/GPU/graphics/RemoteImageBufferProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteImageBufferProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteNativeImageProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteNativeImageProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteResourceCacheProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteResourceCacheProxy.h
Labels: merge-queue, Canvas

#51588 Cancelling a readable locked byte stream should reject
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/templated.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/templated.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/templated.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/templated.any.worker-expected.txt
  Source/WebCore/Modules/streams/ReadableStream.cpp
Labels: merge-queue

#51589 When closed without enough data, ReadableByteStreamController should throw with a TypeError
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/general.any.worker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.serviceworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.sharedworker-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/streams/readable-byte-streams/read-min.any.worker-expected.txt
  Source/WebCore/Modules/streams/ReadableByteStreamController.cpp
Labels: merge-queue

#51615 [GTK3] Unreviewed fix build after 300786@main
  Source/WebKit/WebProcess/InjectedBundle/API/glib/DOM/DOMObjectCache.cpp
Labels: unsafe-merge-queue, WebCore Misc., WebKitGTK

#51494 Ignore subscriptshift/superscriptshift when MathML Core is enabled
  LayoutTests/TestExpectations
  LayoutTests/mathml/non-core/msub-subscriptshift-expected.txt
  LayoutTests/mathml/non-core/msub-subscriptshift.html
  LayoutTests/mathml/non-core/msubsup-subscriptshift-expected.txt
  LayoutTests/mathml/non-core/msubsup-subscriptshift.html
  LayoutTests/mathml/non-core/msubsup-superscriptshift-expected.txt
  LayoutTests/mathml/non-core/msubsup-superscriptshift.html
  LayoutTests/mathml/non-core/msup-superscriptshift-expected.txt
  LayoutTests/mathml/non-core/msup-superscriptshift.html
  LayoutTests/mathml/non-core/multiscript-subscriptshift-expected.txt
  LayoutTests/mathml/non-core/multiscript-subscriptshift.html
  LayoutTests/mathml/non-core/multiscript-superscriptshift-expected.txt
  LayoutTests/mathml/non-core/multiscript-superscriptshift.html
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac/TestExpectations
  Source/WebCore/mathml/MathMLScriptsElement.cpp
  Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp
Labels: merge-queue

#51467 Add AudioVideoRenderer::currentNativeImage API
  Source/WebCore/platform/graphics/AudioVideoRenderer.h
  Source/WebCore/platform/graphics/avfoundation/AudioVideoRendererAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/AudioVideoRendererAVFObjC.mm
  Source/WebCore/platform/graphics/cocoa/MediaPlayerPrivateWebM.h
  Source/WebCore/platform/graphics/cocoa/MediaPlayerPrivateWebM.mm
  Source/WebKit/WebProcess/GPU/media/AudioVideoRendererRemote.cpp
  Source/WebKit/WebProcess/GPU/media/AudioVideoRendererRemote.h
Labels: merge-queue, Media

#51580 Only one enforced CSP violation is reported for 'require-trusted-types-for'
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/should-sink-type-mismatch-violation-be-blocked-by-csp-001-expected.txt
  Source/WebCore/page/csp/ContentSecurityPolicy.cpp
Labels: merge-queue, New Bugs

#51608 [LCP] Change Largest Contentful Paint status to Preview
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: merge-queue, DOM

#51526 [WK1+Window] Remove dead keyboard event code
  Source/WebCore/platform/PlatformKeyboardEvent.h
  Source/WebCore/platform/win/KeyEventWin.cpp
Labels: merge-queue

#44767 Strip StoragePartition from cookies returned by WKHTTPCookieStore API
  Source/WebKit/UIProcess/API/APIHTTPCookieStore.cpp
  Source/WebKit/UIProcess/API/APIHTTPCookieStore.h
  Source/WebKit/UIProcess/API/Cocoa/WKHTTPCookieStore.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKHTTPCookieStore.mm
Labels: merge-queue, Website Storage

#51125 Remove postMessageWithAsyncReply from injectedBundle
  Source/WebKit/UIProcess/API/C/WKPageInjectedBundleClient.h
  Source/WebKit/UIProcess/WebPageInjectedBundleClient.cpp
  Source/WebKit/UIProcess/WebPageInjectedBundleClient.h
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/UIProcess/WebPageProxy.messages.in
  Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundlePage.cpp
  Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundlePage.h
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.h
  Tools/WebKitTestRunner/InjectedBundle/Bindings/EventSendingController.idl
  Tools/WebKitTestRunner/InjectedBundle/Bindings/TestRunner.idl
  Tools/WebKitTestRunner/InjectedBundle/EventSendingController.cpp
  Tools/WebKitTestRunner/InjectedBundle/EventSendingController.h
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.cpp
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.h
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestController.cpp
  Tools/WebKitTestRunner/TestController.h
Labels: merge-queue, Tools / Tests

#51573 Move m_isPrinting from testRunner.h to the UI Process
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.cpp
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.h
  Tools/WebKitTestRunner/InjectedBundle/InjectedBundlePage.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestInvocation.cpp
  Tools/WebKitTestRunner/TestInvocation.h
Labels: merge-queue, Tools / Tests

#51568 Add NetworkCache signposts
  Source/WTF/wtf/PlatformEnableCocoa.h
  Source/WTF/wtf/SystemTracing.h
  Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
  Source/WebKit/NetworkProcess/cache/NetworkCache.cpp
  Source/WebKit/NetworkProcess/cache/NetworkCache.h
Labels: merge-queue, WebKit Misc.

#48676 Refactor BackForward functionality out of WebPageProxy
  Source/WebKit/CMakeLists.txt
  Source/WebKit/DerivedSources-input.xcfilelist
  Source/WebKit/DerivedSources-output.xcfilelist
  Source/WebKit/DerivedSources.make
  Source/WebKit/SourcesCocoa.txt
  Source/WebKit/UIProcess/ProvisionalPageProxy.cpp
  Source/WebKit/UIProcess/RemotePageProxy.cpp
  Source/WebKit/UIProcess/SuspendedPageProxy.cpp
  Source/WebKit/UIProcess/SuspendedPageProxy.h
  Source/WebKit/UIProcess/WebBackForwardList.cpp
  Source/WebKit/UIProcess/WebBackForwardList.h
  Source/WebKit/UIProcess/WebBackForwardList.messages.in
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/UIProcess/WebPageProxy.messages.in
  Source/WebKit/UIProcess/WebPageProxyMessageReceiverRegistration.cpp
  Source/WebKit/UIProcess/WebPageProxyMessageReceiverRegistration.h
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Source/WebKit/WebProcess/WebPage/WebBackForwardListProxy.cpp
  Source/WebKit/WebProcess/WebPage/WebHistoryItemClient.cpp
Labels: merge-queue, New Bugs

#51612 [WebXR] Warn when accessing XRWebGLLayer framebuffer dimensions before first render
  Source/WebCore/Modules/webxr/WebXRWebGLLayer.cpp
  Source/WebCore/Modules/webxr/WebXRWebGLLayer.h
Labels: WebXR

#51658 Add align-self/justify-self dialog behavior to enable UA style for popovers
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/align-dialog-001-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/align-dialog-001.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/align-dialog-002-expected.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/align-dialog-002-ref.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/align-dialog-002.html
  Source/WebCore/css/CSSPrimitiveValueMappings.h
  Source/WebCore/css/CSSProperties.json
  Source/WebCore/css/CSSValueKeywords.in
  Source/WebCore/css/parser/CSSPropertyParserConsumer+Align.cpp
  Source/WebCore/rendering/PositionedLayoutConstraints.cpp
  Source/WebCore/rendering/RenderFlexibleBox.cpp
  Source/WebCore/rendering/RenderGrid.cpp
  Source/WebCore/rendering/style/RenderStyleConstants.cpp
  Source/WebCore/rendering/style/RenderStyleConstants.h
  Source/WebCore/rendering/style/StyleSelfAlignmentData.cpp
  Source/WebCore/rendering/style/StyleSelfAlignmentData.h
  Source/WebCore/style/StyleBuilderConverter.h
Labels: merge-queue, Layout and Rendering

#51315 New WebContent process variant for Enhanced Security
  LayoutTests/TestExpectations
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
  LayoutTests/security/cocoa/check-enhanced-security-disabled-expected.txt
  LayoutTests/security/cocoa/check-enhanced-security-disabled.html
  LayoutTests/security/cocoa/check-enhanced-security-enabled-expected.txt
  LayoutTests/security/cocoa/check-enhanced-security-enabled.html
  LayoutTests/security/cocoa/enhanced-security/check-enhanced-security-enabled-expected.txt
  LayoutTests/security/cocoa/enhanced-security/check-enhanced-security-enabled.html
  LayoutTests/security/cocoa/lockdown-mode/check-lockdown-mode-enabled-expected.txt
  LayoutTests/security/cocoa/lockdown-mode/check-lockdown-mode-enabled.html
  Source/WebCore/page/Page.h
  Source/WebCore/testing/Internals.cpp
  Source/WebCore/testing/Internals.h
  Source/WebCore/testing/Internals.idl
  Source/WebKit/Configurations/BaseXPCService.xcconfig
  Source/WebKit/Configurations/WebContentEnhancedSecurityExtension.xcconfig
  Source/WebKit/Configurations/WebContentService.EnhancedSecurity.xcconfig
  Source/WebKit/Configurations/WebContentService.xcconfig
  Source/WebKit/Resources/SandboxProfiles/ios/com.apple.WebKit.WebContent.sb.in
  Source/WebKit/Scripts/process-entitlements.sh
  Source/WebKit/Shared/AuxiliaryProcessExtensions/WebContentExtension-EnhancedSecurity-Info.plist
  Source/WebKit/Shared/Sandbox/iOS/webcontent-defines.sb
  Source/WebKit/UIProcess/API/Cocoa/WKWebViewPrivateForTesting.h
  Source/WebKit/UIProcess/API/Cocoa/WKWebViewTesting.mm
  Source/WebKit/UIProcess/Launcher/ProcessLauncher.h
  Source/WebKit/UIProcess/Launcher/cocoa/ProcessLauncherCocoa.mm
  Source/WebKit/UIProcess/WebProcessProxy.h
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/com.apple.WebProcess.sb.in
  Tools/Scripts/package-root
  Tools/TestRunnerShared/Scripts/install-extensions-rule.sh
  Tools/TestWebKitAPI/Tests/WebKitCocoa/EnhancedSecurity.mm
Labels: merge-queue, New Bugs

#51560 REGRESSION (273213@main): ImageBitmap fails to report memory cost
  LayoutTests/fast/images/imagebitmap-memory-expected.html
  LayoutTests/fast/images/imagebitmap-memory.html
  Source/WebCore/html/ImageBitmap.cpp
  Source/WebCore/html/ImageBitmap.h
Labels: merge-queue, Images

#51387 Align semantics and maction with MathML Core
  LayoutTests/accessibility/math-foreign-content.html
  LayoutTests/imported/w3c/resources/resource-files.json
  LayoutTests/imported/w3c/web-platform-tests/mathml/relations/html5-tree/maction-click-expected.html
  LayoutTests/imported/w3c/web-platform-tests/mathml/relations/html5-tree/maction-click-ref.html
  LayoutTests/imported/w3c/web-platform-tests/mathml/relations/html5-tree/maction-click.html
  LayoutTests/imported/w3c/web-platform-tests/mathml/relations/html5-tree/w3c-import.log
  LayoutTests/mathml/non-core/maction-dynamic-expected.html
  LayoutTests/mathml/non-core/maction-dynamic.html
  LayoutTests/mathml/non-core/maction-expected.html
  LayoutTests/mathml/non-core/maction-toggle-expected.html
  LayoutTests/mathml/non-core/maction-toggle-href-expected.html
  LayoutTests/mathml/non-core/maction-toggle-href.html
  LayoutTests/mathml/non-core/maction-toggle.html
  LayoutTests/mathml/non-core/maction.html
  LayoutTests/mathml/non-core/semantics-2-expected.html
  LayoutTests/mathml/non-core/semantics-2.html
  LayoutTests/mathml/non-core/semantics-3-expected.html
  LayoutTests/mathml/non-core/semantics-3.html
  LayoutTests/mathml/non-core/semantics-4-expected.html
  LayoutTests/mathml/non-core/semantics-4.html
  LayoutTests/mathml/non-core/semantics-expected.html
  LayoutTests/mathml/non-core/semantics.html
  LayoutTests/platform/glib/accessibility/math-foreign-content-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/html/syntax/parsing/html-integration-point-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/legacy-mrow-like-elements-001-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/css-styling/default-properties-on-semantics-and-maction-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/css-styling/ignored-properties-001-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/css-styling/writing-mode/writing-mode-002-expected.txt
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/html5-tree/dynamic-childlist-002-expected.txt
  LayoutTests/platform/glib/mathml/presentation/foreign-element-in-annotation-xml-expected.txt
  LayoutTests/platform/mac/accessibility/math-foreign-content-expected.txt
  LayoutTests/svg/outermost-svg-root.html
  Source/WebCore/CMakeLists.txt
  Source/WebCore/DerivedSources.make
  Source/WebCore/css/mathmlCoreExtras.css
  Source/WebCore/mathml/MathMLAnnotationElement.cpp
  Source/WebCore/mathml/MathMLSelectElement.cpp
  Source/WebCore/style/InspectorCSSOMWrappers.cpp
  Source/WebCore/style/UserAgentStyle.cpp
  Source/WebCore/style/UserAgentStyle.h
Labels: merge-queue, MathML

#51614 Address forward declaration Safer CPP warnings in worker code
  Source/WebCore/Modules/cookie-store/CookieStore.cpp
  Source/WebCore/Modules/permissions/Permissions.cpp
  Source/WebCore/Modules/storage/WorkerStorageConnection.cpp
  Source/WebCore/Modules/webaudio/AudioWorkletGlobalScope.cpp
  Source/WebCore/Modules/webaudio/AudioWorkletGlobalScope.h
  Source/WebCore/Modules/webaudio/AudioWorkletThread.h
  Source/WebCore/Modules/websockets/ThreadableWebSocketChannel.cpp
  Source/WebCore/Modules/websockets/WebSocket.cpp
  Source/WebCore/Modules/websockets/WorkerThreadableWebSocketChannel.cpp
  Source/WebCore/SaferCPPExpectations/ForwardDeclCheckerExpectations
  Source/WebCore/SaferCPPExpectations/MemoryUnsafeCastCheckerExpectations
  Source/WebCore/SaferCPPExpectations/NoUncountedMemberCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/bindings/js/JSWorkerGlobalScopeBase.cpp
  Source/WebCore/bindings/js/ScheduledAction.cpp
  Source/WebCore/dom/BroadcastChannel.cpp
  Source/WebCore/dom/Document.cpp
  Source/WebCore/dom/Document.h
  Source/WebCore/dom/messageports/WorkerMessagePortChannelProvider.cpp
  Source/WebCore/inspector/WorkerInspectorController.cpp
  Source/WebCore/inspector/WorkerToPageFrontendChannel.h
  Source/WebCore/inspector/agents/worker/WorkerNetworkAgent.cpp
  Source/WebCore/loader/WorkerThreadableLoader.cpp
  Source/WebCore/loader/cache/MemoryCache.cpp
  Source/WebCore/page/WorkerNavigator.cpp
  Source/WebCore/workers/DedicatedWorkerGlobalScope.cpp
  Source/WebCore/workers/DedicatedWorkerGlobalScope.h
  Source/WebCore/workers/DedicatedWorkerThread.cpp
  Source/WebCore/workers/DedicatedWorkerThread.h
  Source/WebCore/workers/Worker.h
  Source/WebCore/workers/WorkerGlobalScope.cpp
  Source/WebCore/workers/WorkerGlobalScope.h
  Source/WebCore/workers/WorkerInspectorProxy.cpp
  Source/WebCore/workers/WorkerMessagingProxy.cpp
  Source/WebCore/workers/WorkerNotificationClient.cpp
  Source/WebCore/workers/WorkerOrWorkletGlobalScope.cpp
  Source/WebCore/workers/WorkerOrWorkletGlobalScope.h
  Source/WebCore/workers/WorkerOrWorkletThread.h
  Source/WebCore/workers/WorkerThread.h
  Source/WebCore/workers/service/ServiceWorker.cpp
  Source/WebCore/workers/service/ServiceWorkerClient.cpp
  Source/WebCore/workers/service/ServiceWorkerClients.cpp
  Source/WebCore/workers/service/ServiceWorkerContainer.cpp
  Source/WebCore/workers/service/ServiceWorkerGlobalScope.cpp
  Source/WebCore/workers/service/ServiceWorkerGlobalScope.h
  Source/WebCore/workers/service/ServiceWorkerWindowClient.cpp
  Source/WebCore/workers/service/context/ServiceWorkerFetch.cpp
  Source/WebCore/workers/service/context/ServiceWorkerInspectorProxy.cpp
  Source/WebCore/workers/service/context/ServiceWorkerThread.cpp
  Source/WebCore/workers/service/context/ServiceWorkerThread.h
  Source/WebCore/workers/shared/SharedWorkerGlobalScope.cpp
  Source/WebCore/workers/shared/SharedWorkerGlobalScope.h
  Source/WebCore/workers/shared/context/SharedWorkerThread.cpp
  Source/WebCore/workers/shared/context/SharedWorkerThread.h
  Source/WebCore/workers/shared/context/SharedWorkerThreadProxy.cpp
Labels: merge-queue, WebCore Misc.

#51043 [World Leaks] Investigate leaks in LayoutTests/imported/w3c/web-platform-tests/webvtt/
  LayoutTests/media/track/track-cue-css.html
  LayoutTests/media/track/webvtt-parser-does-not-leak-expected.txt
  LayoutTests/media/track/webvtt-parser-does-not-leak.html
  Source/WebCore/html/track/WebVTTParser.cpp
  Source/WebCore/html/track/WebVTTParser.h
Labels: merge-queue

#51684 Fix wrong ref in WPT exit-fullscreen-scroll-to-unscrollable-area-overflow-x-hidden test
  LayoutTests/imported/w3c/web-platform-tests/fullscreen/rendering/exit-fullscreen-scroll-to-unscrollable-area-overflow-x-hidden.html
Labels: unsafe-merge-queue, Tools / Tests

#51647 REGRESSION(300757@main): TestWebKitAPI.UnifiedPDF.PasswordFormShouldDismissAfterNavigation broke
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/animation/WebAnimation.cpp
  Source/WebCore/dom/CustomElementReactionQueue.cpp
  Source/WebCore/dom/DocumentStorageAccess.cpp
  Source/WebCore/dom/EventLoop.cpp
  Source/WebCore/dom/EventLoop.h
  Source/WebCore/dom/Microtasks.cpp
  Source/WebCore/dom/MutationObserver.cpp
  Source/WebCore/dom/WindowEventLoop.cpp
  Source/WebCore/dom/WindowEventLoop.h
  Source/WebCore/html/canvas/EXTDisjointTimerQuery.cpp
  Source/WebCore/html/canvas/EXTDisjointTimerQueryWebGL2.cpp
  Source/WebCore/html/canvas/WebGL2RenderingContext.cpp
  Source/WebCore/inspector/agents/InspectorCanvasAgent.cpp
  Source/WebCore/page/Navigation.cpp
  Source/WebCore/testing/Internals.cpp
  Source/WebCore/workers/service/ExtendableEvent.cpp
Labels: unsafe-merge-queue, New Bugs

#51624 Conditional writes are incorrectly handled in Array allocation sinking
  JSTests/stress/array-allocation-sink-conditional-write-osr.js
  JSTests/stress/array-sink-materialize-conditional-write-argument-value.js
  JSTests/stress/array-sink-materialize-conditional-write.js
  Source/JavaScriptCore/dfg/DFGAbstractInterpreterInlines.h
  Source/JavaScriptCore/dfg/DFGObjectAllocationSinkingPhase.cpp
  Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
Labels: merge-queue, JavaScriptCore

#51657 Unreviewed, mark imported/w3c/web-platform-tests/css/css-anchor-position/anchor-position-multicol-colspan-003.html as passing
  LayoutTests/TestExpectations
Labels: merge-queue, CSS

#51625 Trusted Types incorrectly handles null or undefined policy values
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/policy-without-return-value.sub-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/policy-without-return-value.sub.html
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/trusted-types/policy-without-return-value.sub-expected.txt
  Source/WebCore/dom/TrustedTypePolicy.cpp
Labels: merge-queue, DOM

#51575 [GFC] Definite position checking and span sizing.
  Source/WebCore/layout/formattingContexts/grid/GridFormattingContext.cpp
  Source/WebCore/layout/formattingContexts/grid/GridLayout.cpp
  Source/WebCore/layout/formattingContexts/grid/GridLayout.h
  Source/WebCore/layout/formattingContexts/grid/ImplicitGrid.cpp
  Source/WebCore/layout/formattingContexts/grid/ImplicitGrid.h
  Source/WebCore/layout/formattingContexts/grid/UnplacedGridItem.cpp
  Source/WebCore/layout/formattingContexts/grid/UnplacedGridItem.h
Labels: merge-queue, Layout and Rendering

#51353 [Text Matching] Improve performance of Editor::countMatchesForText
  Source/WebCore/editing/Editor.cpp
  Source/WebCore/editing/TextIterator.cpp
  Source/WebCore/editing/TextIterator.h
Labels: unsafe-merge-queue, Layout and Rendering

#51687 [JSC] Remove Wasm string size limit
  JSTests/wasm/stress/large-string-constants.js
  Source/JavaScriptCore/wasm/WasmLimits.h
  Source/JavaScriptCore/wasm/WasmParser.h
Labels: merge-queue, WebAssembly

#51610 Assert the assumption that two VM fields are loadable as a pair
  Source/JavaScriptCore/interpreter/VMEntryRecord.h
  Source/JavaScriptCore/runtime/VM.h
Labels: merge-queue, JavaScriptCore

#51481 [ safaridriver ] dblclick not being issued
  Source/WebKit/UIProcess/Automation/WebAutomationSession.cpp
  Source/WebKit/UIProcess/Automation/WebAutomationSession.h
  Source/WebKit/UIProcess/Automation/mac/WebAutomationSessionMac.mm
Labels: merge-queue

#51645 [GFC] Add some initial logic for computing used margins
  Source/WebCore/layout/formattingContexts/grid/GridLayout.cpp
  Source/WebCore/layout/formattingContexts/grid/GridLayout.h
Labels: merge-queue, Layout and Rendering

#51667 Port WebExtensionContext Background and Inspector functions to C++
  Source/WebCore/en.lproj/Localizable.strings
  Source/WebKit/UIProcess/API/Cocoa/WKWebExtensionContext.mm
  Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionContextCocoa.mm
  Source/WebKit/UIProcess/Extensions/WebExtensionContext.cpp
  Source/WebKit/UIProcess/Extensions/WebExtensionContext.h
Labels: unsafe-merge-queue, WebKit Extensions

#51709 [Gardening]: REGRESSION(300617@main): [macOS wk1] imported/w3c/web-platform-tests/infrastructure/server/wpt-server-http.sub.html is failing
  LayoutTests/platform/mac-wk1/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#51711 Disable TestWebKitAPI.WebTransport.CSP on iOS
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm
Labels: unsafe-merge-queue, Tools / Tests

#51644 [LFC][Integration] Add ability to specify height constraint for layout
  Source/WebCore/layout/LayoutState.cpp
  Source/WebCore/layout/LayoutState.h
  Source/WebCore/layout/integration/LayoutIntegrationFormattingContextLayout.cpp
  Source/WebCore/layout/integration/LayoutIntegrationFormattingContextLayout.h
  Source/WebCore/layout/integration/LayoutIntegrationUtils.cpp
  Source/WebCore/layout/integration/LayoutIntegrationUtils.h
Labels: merge-queue, Layout and Rendering

#51652 [css-anchor-position-1] Adjust order of position option to try when a last successful position option is present
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-006-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-008-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-009-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-010-expected.txt
  Source/WebCore/style/StyleTreeResolver.cpp
Labels: merge-queue, CSS

#51635 [Style] Replace isZero/isNegative/isPositive functions inherited from WebCore::Length
  Source/WebCore/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebCore/css/values/CSSValueConcepts.h
  Source/WebCore/layout/formattingContexts/FormattingGeometry.cpp
  Source/WebCore/layout/formattingContexts/block/BlockMarginCollapse.cpp
  Source/WebCore/rendering/AutoTableLayout.cpp
  Source/WebCore/rendering/GridLayoutFunctions.cpp
  Source/WebCore/rendering/RenderBlock.cpp
  Source/WebCore/rendering/RenderBlockFlow.cpp
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/RenderElement.cpp
  Source/WebCore/rendering/RenderImage.cpp
  Source/WebCore/rendering/RenderMarquee.cpp
  Source/WebCore/rendering/RenderTable.cpp
  Source/WebCore/rendering/RenderTableSection.cpp
  Source/WebCore/rendering/cocoa/RenderThemeCocoa.mm
  Source/WebCore/rendering/style/BorderData.cpp
  Source/WebCore/rendering/style/BorderData.h
  Source/WebCore/rendering/style/RenderStyle.cpp
  Source/WebCore/rendering/style/RenderStyle.h
  Source/WebCore/rendering/style/RenderStyleInlines.h
  Source/WebCore/rendering/svg/RenderSVGEllipse.cpp
  Source/WebCore/rendering/svg/RenderSVGPath.cpp
  Source/WebCore/rendering/svg/RenderSVGRect.cpp
  Source/WebCore/rendering/svg/RenderSVGShape.cpp
  Source/WebCore/rendering/svg/SVGTextBoxPainter.cpp
  Source/WebCore/rendering/svg/legacy/LegacyRenderSVGEllipse.cpp
  Source/WebCore/rendering/svg/legacy/LegacyRenderSVGPath.cpp
  Source/WebCore/rendering/svg/legacy/LegacyRenderSVGRect.cpp
  Source/WebCore/rendering/svg/legacy/LegacyRenderSVGShape.cpp
  Source/WebCore/style/StyleExtractorCustom.h
  Source/WebCore/style/values/StyleValueTypes.h
  Source/WebCore/style/values/backgrounds/StyleBackgroundSize.h
  Source/WebCore/style/values/backgrounds/StyleFillLayers.h
  Source/WebCore/style/values/fill-stroke/StyleStrokeWidth.h
  Source/WebCore/style/values/primitives/StyleLengthWrapper+Blending.h
  Source/WebCore/style/values/primitives/StyleLengthWrapper.h
  Source/WebCore/style/values/primitives/StyleLengthWrapperData.h
  Source/WebCore/style/values/primitives/StylePrimitiveNumeric.h
  Source/WebCore/style/values/primitives/StylePrimitiveNumericTypes+Blending.h
  Source/WebCore/style/values/primitives/StylePrimitiveNumericTypes+Evaluation.h
  Source/WebCore/style/values/svg/StyleSVGStrokeDasharray.h
  Source/WebCore/style/values/svg/StyleSVGStrokeDashoffset.h
  Source/WebCore/style/values/transforms/StyleTransformFunction.cpp
  Source/WebCore/style/values/transforms/StyleTranslate.h
  Source/WebCore/style/values/transforms/functions/StyleTranslateTransformFunction.h
Labels: merge-queue, CSS

#51333 [libpas] Clean up unnecessary includes to improve build speeds
  Source/bmalloc/libpas/src/libpas/pas_dyld_state.c
  Source/bmalloc/libpas/src/libpas/pas_probabilistic_guard_malloc_allocator.c
  Source/bmalloc/libpas/src/libpas/pas_report_crash.c
  Source/bmalloc/libpas/src/libpas/pas_scavenger.c
Labels: merge-queue, New Bugs

#51637 [Temporal] Implement TemporalDuration::subtract() according to spec
  JSTests/stress/temporal-duration.js
  JSTests/test262/config.yaml
  JSTests/test262/expectations.yaml
  Source/JavaScriptCore/runtime/DateConstructor.cpp
  Source/JavaScriptCore/runtime/DateConstructor.h
  Source/JavaScriptCore/runtime/ISO8601.cpp
  Source/JavaScriptCore/runtime/ISO8601.h
  Source/JavaScriptCore/runtime/JSDateMath.h
  Source/JavaScriptCore/runtime/TemporalCalendar.cpp
  Source/JavaScriptCore/runtime/TemporalCalendar.h
  Source/JavaScriptCore/runtime/TemporalDuration.cpp
  Source/JavaScriptCore/runtime/TemporalDuration.h
  Source/JavaScriptCore/runtime/TemporalObject.h
Labels: unsafe-merge-queue, JavaScriptCore

#51342 [libpas] Improve build speeds further by cleaning up includes (part 2)
  Source/bmalloc/libpas/src/libpas/pas_segregated_directory.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_exclusive_view.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_heap.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_page.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_page_config.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_partial_view.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_shared_page_directory.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_shared_view.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_size_directory.c
  Source/bmalloc/libpas/src/libpas/pas_segregated_view.c
  Source/bmalloc/libpas/src/libpas/pas_shared_page_directory_by_size.c
  Source/bmalloc/libpas/src/libpas/pas_status_reporter.c
  Source/bmalloc/libpas/src/libpas/pas_string_stream.c
  Source/bmalloc/libpas/src/libpas/pas_thread_local_cache.c
  Source/bmalloc/libpas/src/libpas/pas_thread_local_cache_layout.c
  Source/bmalloc/libpas/src/libpas/pas_utility_heap.c
  Source/bmalloc/libpas/src/libpas/pas_utils.c
Labels: merge-queue, New Bugs

#51706 Implement WebTransportOptions.serverCertificateHashes
  Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm
  Tools/TestWebKitAPI/WebTransportServer.h
  Tools/TestWebKitAPI/WebTransportServer.mm
Labels: unsafe-merge-queue, WebKit Misc.

#51710 bsky.app: No highlight when navigating to text fragment link generated by Safari
  LayoutTests/http/tests/scroll-to-text-fragment/dynamic-content-is-found-expected.txt
  LayoutTests/http/tests/scroll-to-text-fragment/dynamic-content-is-found.html
  Source/WebCore/dom/FragmentDirectiveUtilities.cpp
  Source/WebCore/dom/FragmentDirectiveUtilities.h
  Source/WebCore/page/LocalFrameView.cpp
  Source/WebCore/page/LocalFrameView.h
Labels: merge-queue, WebKit Misc.

#51173 Deploy smart pointer in GtkVersioning
  Source/WebCore/platform/gtk/GtkVersioning.h
Labels: merge-queue, New Bugs

#51662 Address safer cpp warnings in SecItemShim.cpp
  Source/WebKit/NetworkProcess/mac/SecItemShim.mm
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCSharedMonitor.h
  Source/WebKit/NetworkProcess/webrtc/NetworkRTCUDPSocketCocoa.mm
  Source/WebKit/SaferCPPExpectations/RetainPtrCtorAdoptCheckerExpectations
  Source/WebKit/SourcesCocoa.txt
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
Labels: merge-queue, WebKit2

#49648 Adopt some more smart pointers in UIProcess
  Source/WebKit/SaferCPPExpectations/NoUnretainedMemberCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/mac/TiledCoreAnimationDrawingAreaProxy.mm
  Source/WebKit/UIProcess/mac/WKPrintingView.h
  Source/WebKit/UIProcess/mac/WKPrintingView.mm
  Source/WebKit/UIProcess/mac/WKRevealItemPresenter.mm
  Source/WebKit/UIProcess/mac/WebContextMenuProxyMac.mm
  Source/WebKit/UIProcess/mac/WebDataListSuggestionsDropdownMac.mm
  Source/WebKit/UIProcess/mac/WebDateTimePickerMac.mm
  Source/WebKit/UIProcess/mac/WebViewImpl.mm
Labels: merge-queue, New Bugs

#51732 Unreviewed build fix.
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm
Labels: unsafe-merge-queue

#51723 [Temporal] Implement addition for TemporalCalendar and TemporalDuration according to the spec
  JSTests/stress/temporal-duration.js
  JSTests/test262/config.yaml
  Source/JavaScriptCore/runtime/TemporalCalendar.cpp
  Source/JavaScriptCore/runtime/TemporalCalendarPrototype.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#51722 Address safer cpp warnings in PageClientImplCocoa.mm
  Source/WebKit/SaferCPPExpectations/RetainPtrCtorAdoptCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/Cocoa/PageClientImplCocoa.mm
Labels: merge-queue, WebKit2

#51739 Unreviewed, reverting 300874@main (ccac5c735ff6)
  Source/WebKit/NetworkProcess/PrivateClickMeasurement/PrivateClickMeasurementDatabase.cpp
  Source/WebKit/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
Labels: unsafe-merge-queue, WebKit2

#51720 Address Safer cpp warnings in ResourceLoadStatisticsStore.cpp
  Source/WebCore/Modules/indexeddb/server/SQLiteIDBBackingStore.cpp
  Source/WebCore/Modules/indexeddb/server/SQLiteIDBCursor.cpp
  Source/WebCore/Modules/push-api/PushDatabase.cpp
  Source/WebCore/loader/ResourceMonitorPersistence.cpp
  Source/WebCore/platform/network/curl/CookieJarDB.cpp
  Source/WebCore/platform/sql/SQLiteDatabase.cpp
  Source/WebCore/platform/sql/SQLiteDatabase.h
  Source/WebCore/platform/sql/SQLiteStatementAutoResetScope.cpp
  Source/WebCore/platform/sql/SQLiteStatementAutoResetScope.h
  Source/WebCore/platform/win/SearchPopupMenuDB.cpp
  Source/WebCore/workers/service/server/SWRegistrationDatabase.cpp
  Source/WebKit/NetworkProcess/Classifier/ResourceLoadStatisticsStore.cpp
  Source/WebKit/NetworkProcess/DatabaseUtilities.cpp
  Source/WebKit/NetworkProcess/storage/SQLiteStorageArea.cpp
  Source/WebKit/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/API/glib/IconDatabase.cpp
Labels: merge-queue, WebKit2

#51735 Resync `css/geometry` from WPT Upstream
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-001-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-001.html
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-002.html
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-003-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-003.html
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-invert-invertible.html
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix-invertSelf.html
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/DOMMatrix2DInit-validate-fixup-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/support/dommatrix-test-util.js
  LayoutTests/imported/w3c/web-platform-tests/css/geometry/w3c-import.log
Labels: merge-queue, CSS

#51736 Vorbis decoder can't be instantiated in the content process on Sonoma machines (and earlier)
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
  Source/WTF/wtf/PlatformEnableCocoa.h
  Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
Labels: merge-queue, Media

#51729 [Safer CPP] Unreviewed, unskip some files that are now passing on the bot
  Source/WebCore/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
Labels: unsafe-merge-queue, Tools / Tests

#51320 Reduce references to UChar and LChar
  Source/JavaScriptCore/API/tests/JSONParseTest.cpp
  Source/JavaScriptCore/builtins/BuiltinNames.cpp
  Source/JavaScriptCore/parser/Lexer.cpp
  Source/JavaScriptCore/parser/Lexer.h
  Source/JavaScriptCore/parser/ParserArena.h
  Source/JavaScriptCore/runtime/Identifier.h
  Source/JavaScriptCore/runtime/JSGlobalObjectFunctions.cpp
  Source/JavaScriptCore/wasm/js/WebAssemblyBuiltin.cpp
  Source/JavaScriptCore/yarr/YarrCanonicalize.h
  Source/JavaScriptCore/yarr/YarrCanonicalizeUCS2.cpp
  Source/JavaScriptCore/yarr/YarrCanonicalizeUCS2.js
  Source/JavaScriptCore/yarr/YarrInterpreter.cpp
  Source/JavaScriptCore/yarr/YarrJIT.cpp
  Source/JavaScriptCore/yarr/YarrPattern.cpp
  Source/JavaScriptCore/yarr/YarrPattern.h
  Source/WTF/wtf/FileSystem.cpp
  Source/WTF/wtf/URLParser.cpp
  Source/WTF/wtf/URLParser.h
  Source/WTF/wtf/text/AtomStringImpl.cpp
  Source/WTF/wtf/text/ParsingUtilities.h
  Source/WTF/wtf/text/StringBuilder.cpp
  Source/WTF/wtf/text/StringBuilder.h
  Source/WTF/wtf/text/StringCommon.h
  Source/WTF/wtf/text/StringImpl.cpp
  Source/WTF/wtf/text/StringImpl.h
  Source/WTF/wtf/text/StringView.h
  Source/WebCore/PAL/pal/text/TextCodecASCIIFastPath.h
  Source/WebCore/PAL/pal/text/TextCodecCJK.cpp
  Source/WebCore/PAL/pal/text/TextCodecICU.cpp
  Source/WebCore/html/NumberInputType.cpp
  Source/WebCore/html/parser/HTMLPreloadScanner.cpp
  Source/WebCore/html/track/VTTScanner.h
  Source/WebCore/inspector/agents/InspectorDOMAgent.cpp
  Source/WebCore/platform/graphics/ca/GraphicsLayerCA.cpp
  Source/WebCore/platform/win/ClipboardUtilitiesWin.cpp
  Tools/TestWebKitAPI/Tests/WTF/StringBuilder.cpp
  Tools/TestWebKitAPI/Tests/WTF/StringHasher.cpp
  Tools/TestWebKitAPI/Tests/WTF/SuperFastHash.cpp
  Tools/TestWebKitAPI/Tests/WTF/WTFString.cpp
  Tools/TestWebKitAPI/Tests/WTF/WYHash.cpp
  Tools/gdb/webkit.py
Labels: merge-queue, JavaScriptCore

#51741 Remove unused WebGPU field
  Source/WebGPU/WebGPU/DDMesh.h
Labels: merge-queue, WebGPU

#51670 WTF and bmalloc modulemaps system
  Source/WTF/Configurations/modulemap.toml
  Source/bmalloc/Configurations/module.modulemap
Labels: merge-queue, bmalloc

#51613 WTF modulemap to cplusplus20
  Source/WTF/Configurations/modulemap.toml
Labels: merge-queue, WebKit Misc.

#51702 Strip StoragePartition from cookies returned by WKHTTPCookieStore API
  Source/WebKit/Configurations/AllowedSPI.toml
  Source/WebKit/UIProcess/API/APIHTTPCookieStore.cpp
  Source/WebKit/UIProcess/API/APIHTTPCookieStore.h
  Source/WebKit/UIProcess/API/Cocoa/WKHTTPCookieStore.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKHTTPCookieStore.mm
Labels: merge-queue

#51721 Use WebCore::DataURLDecoder to decode data: urls in WebExtension
  Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
Labels: unsafe-merge-queue, WebKit Extensions

#51759 Make TestWebKitAPI.WebTransport.ServerCertificateHashes not time out
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm
Labels: unsafe-merge-queue, Tools / Tests

#51750 Address safer CPP warnings in UI process classes
  Source/WebKit/Platform/mac/MenuUtilities.h
  Source/WebKit/Platform/mac/MenuUtilities.mm
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/API/APIAttachment.h
  Source/WebKit/UIProcess/API/Cocoa/APIAttachmentCocoa.mm
  Source/WebKit/UIProcess/mac/WebContextMenuProxyMac.mm
  Source/WebKit/UIProcess/mac/WebPopupMenuProxyMac.mm
Labels: merge-queue, WebKit Misc.

#51677 [JSC] More explicit type conversions in OMG
  Source/JavaScriptCore/wasm/WasmOMGIRGenerator.cpp
  Source/JavaScriptCore/wasm/WasmOMGIRGenerator32_64.cpp
Labels: JavaScriptCore

#51764 REGRESSION(300786@main): Build error in UnifiedPDFPlugin.cpp: Undefined symbol "WebCore::Node::document() const"
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.mm
  Source/WebKit/WebProcess/WebPage/Cocoa/WebPageCocoa.mm
  Source/WebKit/WebProcess/WebPage/FindController.cpp
  Source/WebKit/WebProcess/WebPage/WebFoundTextRangeController.cpp
  Source/WebKit/WebProcess/WebPage/WebFrame.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm
  Source/WebKit/WebProcess/WebPage/mac/WebPageMac.mm
Labels: unsafe-merge-queue

#51707 [GFC] Add initial alignment support with start alignment.
  Source/WebCore/layout/formattingContexts/grid/GridFormattingContext.cpp
  Source/WebCore/layout/formattingContexts/grid/GridLayout.cpp
  Source/WebCore/layout/formattingContexts/grid/GridLayout.h
  Source/WebCore/layout/formattingContexts/grid/PlacedGridItem.cpp
  Source/WebCore/layout/formattingContexts/grid/PlacedGridItem.h
Labels: merge-queue, Layout and Rendering

#51703 [JSC] WASM IPInt SIMD: support GC types with v128 fields/elements
  Source/JavaScriptCore/llint/InPlaceInterpreter64.asm
  Source/JavaScriptCore/wasm/WasmIPIntSlowPaths.cpp
  Source/JavaScriptCore/wasm/WasmIPIntSlowPaths.h
  Source/JavaScriptCore/wasm/WasmOperationsInlines.h
  Source/JavaScriptCore/wasm/js/JSWebAssemblyArray.h
  Source/JavaScriptCore/wasm/js/JSWebAssemblyArrayInlines.h
  Source/JavaScriptCore/wasm/js/JSWebAssemblyStruct.cpp
  Source/JavaScriptCore/wasm/js/JSWebAssemblyStruct.h
Labels: merge-queue, JavaScriptCore

#51774 [JSC] Fix v128 global.get in const expr
  JSTests/wasm/gc/simd.js
  Source/JavaScriptCore/wasm/WasmConstExprGenerator.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#51704 Fix iOS Simulated Keyboard Events Crash (event-timing)
  Source/WebCore/page/LocalDOMWindow.cpp
Labels: merge-queue

#51716 Check for nil NSURLRequest in NetworkSessionCocoa
  LayoutTests/ipc/networksessioncocoa-empty-resource-request-expected.txt
  LayoutTests/ipc/networksessioncocoa-empty-resource-request.html
  Source/WebKit/NetworkProcess/cocoa/NetworkSessionCocoa.mm
Labels: merge-queue, New Bugs

#51743 REGRESSION(299875@main?) [iOS macOS] ASSERTION FAILED: it != m_trackIdentifiers.end()
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac/TestExpectations
  Source/WebCore/platform/graphics/avfoundation/AudioVideoRendererAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/AudioVideoRendererAVFObjC.mm
Labels: merge-queue, Media

#51543 [cocoa] Set WebMUseRemoteAudioVideoRenderer preference to testable
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/platform/graphics/MediaPlayer.cpp
  Source/WebCore/platform/graphics/cocoa/MediaPlayerPrivateWebM.mm
Labels: merge-queue, Media

#51362 Introduce an event when attaching a shadow root to an element
  LayoutTests/fast/dom/gc-dom-tree-lifetime-shadow-tree.html
  Source/WebCore/dom/Element.cpp
  Source/WebCore/dom/Element.h
  Source/WebCore/dom/Event.cpp
  Source/WebCore/dom/Event.h
  Source/WebCore/dom/EventNames.json
  Source/WebCore/dom/EventTarget.cpp
  Source/WebCore/dom/MutationObserver.cpp
  Source/WebCore/dom/MutationObserver.h
  Source/WebCore/dom/Node.h
  Source/WebCore/dom/WindowEventLoop.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/FormValidation.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/UserContentController.mm
Labels: unsafe-merge-queue, New Bugs

#51775 Add feature flag for panorama image controls
  LayoutTests/platform/visionos/TestExpectations
  Source/WebCore/html/shadow/SpatialImageControls.cpp
  Source/WebCore/html/shadow/spatialImageControls.css
Labels: merge-queue, New Bugs

#51733 Address more Safer CPP failures in UIProcess/Cocoa
  Source/WebCore/platform/network/mac/AuthenticationMac.h
  Source/WebCore/platform/network/mac/AuthenticationMac.mm
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/Shared/Cocoa/WKObject.h
  Source/WebKit/UIProcess/Cocoa/DiagnosticLoggingClient.mm
  Source/WebKit/UIProcess/Cocoa/GlobalFindInPageState.mm
  Source/WebKit/UIProcess/Cocoa/ResourceLoadDelegate.mm
  Source/WebKit/UIProcess/Cocoa/SOAuthorization/SOAuthorizationSession.mm
  Source/WebKit/UIProcess/Cocoa/WKContactPicker.mm
  Source/WebKit/UIProcess/Cocoa/WKShareSheet.mm
Labels: merge-queue, WebKit2

#51731 Address safer cpp warnings in NavigationState.mm
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/Cocoa/NavigationState.mm
Labels: merge-queue, WebKit2

#51727 [SaferCPP] Address issues in CanvasBase
  Source/WebCore/SaferCPPExpectations/UncheckedLocalVarsCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
  Source/WebCore/html/CanvasBase.cpp
Labels: merge-queue, New Bugs

#51785 [libpas] Enable MTE Retag-on-Scavenge in privileged processes
  Source/bmalloc/libpas/src/libpas/pas_mte.h
  Source/bmalloc/libpas/src/libpas/pas_mte_config.h
Labels: merge-queue, bmalloc

#51801 Unreviewed, reverting 300969@main (77271dc9c550)
  Configurations/CommonBase.xcconfig
  Source/WebCore/Configurations/AllowedSPI-legacy.toml
  Tools/TestRunnerShared/spi/UIKitSPIForTesting.h
  Tools/TestWebKitAPI/Tests/WebKit Swift/TestWebKitAPIBundle-Bridging-Header.h
  WebKitLibraries/SDKs/iphoneos26.0-additions.sdk/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore.tbd
  WebKitLibraries/SDKs/iphonesimulator26.0-additions.sdk/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore.tbd
Labels: unsafe-merge-queue, Tools / Tests

#51753 More safer CPP fixes in the UI process
  Source/WebKit/SaferCPPExpectations/NoUnretainedMemberCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UnretainedCallArgsCheckerExpectations
  Source/WebKit/UIProcess/mac/WKImmediateActionController.h
  Source/WebKit/UIProcess/mac/WKImmediateActionController.mm
  Source/WebKit/UIProcess/mac/WKTextFinderClient.mm
Labels: merge-queue, WebKit Misc.

#51800 [SaferC++] Use memory safe pointers in the Injected Bundle C API (part 1)
  Source/WebKit/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleDOMWindowExtension.cpp
  Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleRangeHandle.cpp
  Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleScriptWorld.cpp
Labels: New Bugs

#51686 [WebGPU Swift] CommandEncoder does not support GPUTexture instances in beginRenderPass
  Source/WebGPU/WebGPU.xcodeproj/project.pbxproj
  Source/WebGPU/WebGPU/CommandEncoder.mm
  Source/WebGPU/WebGPU/CommandEncoder.swift
  Source/WebGPU/WebGPU/Internal/WebGPUSwiftInternal.h
  Source/WebGPU/WebGPU/TextureOrTextureView.h
  Source/WebGPU/WebGPU/WebGPU.h
Labels: merge-queue, WebGPU

#51808 REGRESSION(300989@main): Broke Internal visionOS builds
  Source/WebCore/Modules/model-element/HTMLModelElement.cpp
Labels: unsafe-merge-queue, Tools / Tests

#51806 Update status of Etienne Segonzac to 'reviewer' in contributors.json
  metadata/contributors.json
Labels: unsafe-merge-queue, WebKit Misc.

#51656 [WebGPU Swift] resolveQuerySet workaround is missing from Swift implementation
  Source/WebGPU/WebGPU/CommandEncoder.swift
Labels: merge-queue, WebGPU

#51807 Restrict AUDIO_DECODER_REGISTRATION to machines with Sonoma 14.5 and earlier
  Source/WTF/wtf/PlatformEnableCocoa.h
Labels: merge-queue, Media

#51815 [WTF] Fix bugprone-move-forwarding-reference warnings in NativePromise.h
  Source/WTF/wtf/NativePromise.h
Labels: unsafe-merge-queue

#51786 [Build Speed] Make WebKit/LoggingClient.h less expensive to include
  Source/WebKit/Platform/LogClient.cpp
  Source/WebKit/Platform/LogClient.h
  Source/WebKit/Scripts/generate-derived-log-sources.py
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
Labels: merge-queue

#50420 Adopt AudioVideoRendererAVFObjC in MediaPlayerPrivateMediaSourceAVFObjC
  LayoutTests/imported/w3c/web-platform-tests/media-source/dedicated-worker/mediasource-worker-play-expected.txt
  Source/WebCore/SaferCPPExpectations/UnretainedLocalVarsCheckerExpectations
  Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.mm
  Source/WebCore/platform/graphics/avfoundation/objc/MediaSourcePrivateAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/objc/MediaSourcePrivateAVFObjC.mm
  Source/WebCore/platform/graphics/avfoundation/objc/SourceBufferPrivateAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/objc/SourceBufferPrivateAVFObjC.mm
  Source/WebCore/platform/graphics/cocoa/VideoMediaSampleRenderer.h
  Source/WebCore/platform/graphics/cocoa/VideoMediaSampleRenderer.mm
Labels: Media

#51754 [Temporal] Remove isoDateDifference() and use calendarDateUntil() instead
  JSTests/stress/temporal-plaindate.js
  JSTests/test262/config.yaml
  JSTests/test262/expectations.yaml
  Source/JavaScriptCore/runtime/ISO8601.cpp
  Source/JavaScriptCore/runtime/ISO8601.h
  Source/JavaScriptCore/runtime/TemporalCalendar.cpp
  Source/JavaScriptCore/runtime/TemporalCalendar.h
  Source/JavaScriptCore/runtime/TemporalCalendarPrototype.cpp
  Source/JavaScriptCore/runtime/TemporalDuration.cpp
  Source/JavaScriptCore/runtime/TemporalDuration.h
  Source/JavaScriptCore/runtime/TemporalObject.h
  Source/JavaScriptCore/runtime/TemporalPlainDate.cpp
  Source/JavaScriptCore/runtime/TemporalPlainDate.h
Labels: unsafe-merge-queue, JavaScriptCore

#51825 Unreviewed, reverting 301009@main (02e86e63291c)
  Source/WebKit/Platform/LogClient.cpp
  Source/WebKit/Platform/LogClient.h
  Source/WebKit/Scripts/generate-derived-log-sources.py
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
Labels: unsafe-merge-queue, WebCore Misc.

#51826 [libpas] Only include pas headers when LIBPAS_ENABLED redux
  Source/bmalloc/libpas/src/libpas/pas_fast_megapage_table.c
  Source/bmalloc/libpas/src/libpas/pas_mte_config.c
Labels: merge-queue, JavaScriptCore

#51824 TestContextMenuDriver should adopt -clickDriver:shouldBegin:(void(^)(_UIClickInteractionShouldBeginResult)) SPI
  Tools/TestRunnerShared/spi/UIKitSPIForTesting.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ContextMenus.mm
  Tools/TestWebKitAPI/cocoa/TestContextMenuDriver.mm
Labels: unsafe-merge-queue, New Bugs

#51798 Update SQLiteDatabase::prepareStatement() to return a std::unique_ptr instead of an std::expected
  LayoutTests/storage/websql/private-browsing-noread-nowrite-expected.txt
  Source/WebCore/Modules/indexeddb/server/SQLiteIDBBackingStore.cpp
  Source/WebCore/Modules/indexeddb/server/SQLiteIDBCursor.cpp
  Source/WebCore/Modules/push-api/PushDatabase.cpp
  Source/WebCore/Modules/webdatabase/Database.cpp
  Source/WebCore/Modules/webdatabase/SQLStatement.cpp
  Source/WebCore/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebCore/loader/ResourceMonitorPersistence.cpp
  Source/WebCore/platform/network/curl/CookieJarDB.cpp
  Source/WebCore/platform/network/curl/CookieJarDB.h
  Source/WebCore/platform/sql/SQLiteDatabase.cpp
  Source/WebCore/platform/sql/SQLiteDatabase.h
  Source/WebCore/platform/win/SearchPopupMenuDB.cpp
  Source/WebCore/platform/win/SearchPopupMenuDB.h
  Source/WebCore/workers/service/server/SWRegistrationDatabase.cpp
  Source/WebKit/NetworkProcess/Classifier/ResourceLoadStatisticsStore.cpp
  Source/WebKit/NetworkProcess/DatabaseUtilities.cpp
  Source/WebKit/NetworkProcess/PrivateClickMeasurement/PrivateClickMeasurementDatabase.cpp
  Source/WebKit/NetworkProcess/storage/SQLiteStorageArea.cpp
  Source/WebKit/UIProcess/API/glib/IconDatabase.cpp
  Source/WebKitLegacy/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
Labels: merge-queue, WebCore Misc.

#51803 Resync `webaudio` from WPT Upstream
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/k-rate-audioworklet.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/k-rate-audioworklet.https.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/nan-param-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/nan-param.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/retrospective-setTargetAtTime-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/retrospective-setTargetAtTime.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/set-target-conv-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/set-target-conv.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-audioparam.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-audioparam.https.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-disconnected-input.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-disconnected-input.https.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/simple-input-output.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/simple-input-output.https.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-convolvernode-interface/active-processing.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-convolvernode-interface/active-processing.https.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-pannernode-interface/panner-rolloff-clamping-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-pannernode-interface/panner-rolloff-clamping.html
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-waveshapernode-interface/waveshaper-copy-curve-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/webaudio/the-audio-api/the-waveshapernode-interface/waveshaper-copy-curve.html
Labels: merge-queue, Web Audio

#50792 [JSC] Improve error message for calling constructor without `new`
  JSTests/stress/calling-non-callable-constructors.js
  JSTests/stress/constructor-call-without-new.js
  JSTests/stress/constructor-kind-naked-should-not-be-applied-to-inner-functions.js
  JSTests/stress/promise-cannot-be-called.js
  LayoutTests/js/Promise-types-expected.txt
  LayoutTests/js/class-syntax-call-expected.txt
  LayoutTests/js/class-syntax-default-constructor-expected.txt
  LayoutTests/js/script-tests/Promise-types.js
  LayoutTests/js/script-tests/class-syntax-call.js
  LayoutTests/js/script-tests/class-syntax-default-constructor.js
  LayoutTests/performance-api/performance-observer-exception-expected.txt
  Source/JavaScriptCore/bytecompiler/BytecodeGenerator.cpp
Labels: merge-queue, JavaScriptCore

#51830 [LibWebRTC] Fix unsafe-buffer-usage-in-container warning in LibWebRTCSocketClient.cpp
  Source/WebKit/NetworkProcess/webrtc/LibWebRTCSocketClient.cpp
Labels: merge-queue, WebRTC

#51699 Implement a Stop the World mechanism for JSC.
  Source/JavaScriptCore/API/tests/VMManagerStopTheWorldTest.cpp
  Source/JavaScriptCore/API/tests/VMManagerStopTheWorldTest.h
  Source/JavaScriptCore/API/tests/testapi.c
  Source/JavaScriptCore/CMakeLists.txt
  Source/JavaScriptCore/JavaScriptCore.xcodeproj/project.pbxproj
  Source/JavaScriptCore/heap/MarkedBlock.cpp
  Source/JavaScriptCore/llint/LowLevelInterpreter.asm
  Source/JavaScriptCore/runtime/JSCConfig.h
  Source/JavaScriptCore/runtime/StopTheWorldCallback.h
  Source/JavaScriptCore/runtime/VM.cpp
  Source/JavaScriptCore/runtime/VM.h
  Source/JavaScriptCore/runtime/VMManager.cpp
  Source/JavaScriptCore/runtime/VMManager.h
  Source/JavaScriptCore/runtime/VMThreadContext.h
  Source/JavaScriptCore/runtime/VMTraps.cpp
  Source/JavaScriptCore/runtime/VMTraps.h
  Source/JavaScriptCore/runtime/VMTrapsInlines.h
  Source/JavaScriptCore/shell/CMakeLists.txt
  Source/JavaScriptCore/wasm/WasmCallee.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#51719 Drop WTF_ALLOW_UNSAFE_BUFFER_USAGE for wtf/StringExtras
  Source/WTF/WTF.xcodeproj/project.pbxproj
  Source/WTF/wtf/CMakeLists.txt
  Source/WTF/wtf/StdLibExtras.h
  Source/WTF/wtf/StringExtras.h
  Source/WebCore/Modules/fetch/FetchBodyConsumer.cpp
  Source/WebCore/Modules/websockets/WebSocketHandshake.cpp
  Source/WebCore/platform/network/curl/CurlMultipartHandle.cpp
  Source/WebCore/platform/win/ClipboardUtilitiesWin.cpp
  Tools/TestWebKitAPI/Tests/WTF/FileSystem.cpp
  Tools/TestWebKitAPI/Tests/WTF/IntegerToStringConversion.cpp
  Tools/TestWebKitAPI/Tests/WebCore/FileMonitor.cpp
  Tools/TestWebKitAPI/Tests/WebCore/SharedBuffer.cpp
  Tools/WebKitTestRunner/cairo/TestInvocationCairo.cpp
Labels: merge-queue

#51820 Remove text-indent support from PopupMenuStyle, no ports use it
  Source/WebCore/platform/PopupMenuStyle.h
  Source/WebCore/rendering/RenderMenuList.cpp
  Source/WebCore/rendering/RenderSearchField.cpp
  Source/WebCore/rendering/RenderTheme.h
  Source/WebKit/WebProcess/WebCoreSupport/win/WebPopupMenuWin.cpp
Labels: merge-queue, Platform

#49126 [Bindings] Optimize union IDL attribute setters by avoiding conversion to variant
  Source/WebCore/bindings/js/JSDOMConvertBase.h
  Source/WebCore/bindings/js/JSDOMConvertUnion.h
  Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
  Source/WebCore/bindings/scripts/IDLAttributes.json
  Source/WebCore/bindings/scripts/test/JS/JSTestObj.cpp
  Source/WebCore/bindings/scripts/test/TestObj.idl
  Source/WebCore/html/canvas/CanvasFillStrokeStyles.idl
  Source/WebCore/html/canvas/CanvasRenderingContext2DBase.cpp
  Source/WebCore/html/canvas/CanvasRenderingContext2DBase.h
Labels: merge-queue, Bindings

#51796 Address safer cpp warnings in JSC::Watchpoint
  Source/JavaScriptCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/JavaScriptCore/bytecode/Watchpoint.h
Labels: merge-queue, JavaScriptCore

#51848 Unreviewed visionOS build fix after 301038@main
  Source/WebCore/Modules/webxr/XRWebGLSubImage.cpp
  Source/WebCore/Modules/webxr/XRWebGLSubImage.h
Labels: unsafe-merge-queue, WebXR

#51746 Widen AppleVisualEffect bitfield
  Source/WebCore/rendering/style/StyleRareInheritedData.h
Labels: merge-queue, CSS

#51738 [GTK][WPE] OpenGL assets created by WebGL are not released when destroying the WebGLRenderingContext
  Source/WebCore/platform/graphics/PlatformDisplay.cpp
  Source/WebCore/platform/graphics/PlatformDisplay.h
  Source/WebCore/platform/graphics/angle/GraphicsContextGLANGLE.h
  Source/WebCore/platform/graphics/angle/PlatformDisplayANGLE.cpp
  Source/WebCore/platform/graphics/texmap/GraphicsContextGLTextureMapperANGLE.cpp
Labels: unsafe-merge-queue, WPE WebKit, GLib Suggested Backport - 2.50

#51831 Add preference to make MediaPlayerPrivateMediaSourceAVFObjC run in the web process.
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/platform/graphics/MediaPlayer.cpp
  Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.h
  Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.mm
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
Labels: merge-queue, Media

#51765 AX: [iOS] Date fields shouldn't send focused change notification when picker popup is presented
  LayoutTests/accessibility/ios-simulator/date-picker-focus-notification-expected.txt
  LayoutTests/accessibility/ios-simulator/date-picker-focus-notification.html
  Source/WebCore/accessibility/AXObjectCache.cpp
  Source/WebCore/accessibility/AXObjectCache.h
  Source/WebCore/html/BaseDateAndTimeInputType.cpp
  Source/WebCore/page/Page.cpp
  Source/WebCore/page/Page.h
  Source/WebKit/WebProcess/WebPage/WebPage.h
  Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm
Labels: Accessibility

#51855 Add internal flags for two existing quirks
  LayoutTests/webrtc/encoded-streams-quirks.html
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/Scripts/GenerateSettings.rb
  Source/WebCore/page/Quirks.cpp
  Source/WebCore/page/Quirks.h
Labels: merge-queue

#51818 [JSC] Avoid using t4 for cCall4
  Source/JavaScriptCore/llint/LowLevelInterpreter64.asm
Labels: unsafe-merge-queue, JavaScriptCore

#51814 [Site Isolation] Navigation from about url reuses process with different protocol
  Source/WebKit/UIProcess/WebProcessPool.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/SiteIsolation.mm
Labels: merge-queue, New Bugs

#51854 [Site Isolation] Main frame's Document.activeElement incorrectly reports iframe after focus is relinquished from a cross-origin iframe to the user agent chrome
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.h
  Source/WebKit/WebProcess/WebPage/WebPage.messages.in
  Tools/TestWebKitAPI/Tests/mac/FocusWebView.mm
Labels: unsafe-merge-queue, New Bugs

#50809 [JSC] Unify 32-bit and 64-bit BBQJIT::addF64Copysign
  Source/JavaScriptCore/assembler/MacroAssemblerX86_64.h
  Source/JavaScriptCore/assembler/X86Assembler.h
  Source/JavaScriptCore/wasm/WasmBBQJIT.cpp
  Source/JavaScriptCore/wasm/WasmBBQJIT.h
  Source/JavaScriptCore/wasm/WasmBBQJIT32_64.cpp
  Source/JavaScriptCore/wasm/WasmBBQJIT64.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#51757 [WPE][GTK] Speakers enumeration doesn't show ALSA virtual sinks
  Source/WebCore/Modules/speech/SpeechRecognitionCaptureSource.cpp
  Source/WebCore/platform/mediastream/CaptureDevice.h
  Source/WebCore/platform/mediastream/RealtimeMediaSourceCenter.cpp
  Source/WebCore/platform/mediastream/gstreamer/GStreamerAudioCaptureSource.cpp
  Source/WebCore/platform/mediastream/gstreamer/GStreamerCaptureDeviceManager.cpp
  Source/WebCore/platform/mediastream/gstreamer/GStreamerCapturer.cpp
  Source/WebCore/platform/mock/MockRealtimeMediaSourceCenter.cpp
Labels: merge-queue

#51890 Fix internal non-Mac build
  Source/WebKit/UIProcess/Extensions/WebExtensionWindow.h
Labels: unsafe-merge-queue, WebKit Misc.

#51893 ModelProcessModelPlayerManager.cpp:64:13: error: reference to stack memory associated with local variable 'modelProcessConnection' returned
  Source/WebKit/WebProcess/Model/ModelProcessModelPlayerManager.cpp
Labels: unsafe-merge-queue, WebXR

#51880 Adopt LIFETIME_BOUND for WTF::OSObjectPtr
  Source/WTF/wtf/OSObjectPtr.h
Labels: unsafe-merge-queue

#51888 Wasm catch handler ranges should be inclusive
  JSTests/wasm/stress/exception-thrown-at-end-of-catch.js
  Source/JavaScriptCore/wasm/WasmHandlerInfo.cpp
Labels: merge-queue, WebAssembly

#51802 [Swift in WebKit] The WebKit module is not compatible with Objective-C++ clients
  Source/WebKit/Configurations/WebKit.xcconfig
  Source/WebKit/Modules/MacCatalyst.modulemap
  Source/WebKit/Modules/OSX.modulemap
  Source/WebKit/Modules/iOS.modulemap
Labels: merge-queue, WebKit Misc.

#49361 [Navigation API] navigate.back doesn't work in main frame when preceded by navigate.back in child frame (part 2)
  LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-methods/disambigaute-forward-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-methods/disambigaute-traverseTo-forward-multiple-expected.txt
  Source/WebCore/loader/HistoryController.cpp
Labels: unsafe-merge-queue, New Bugs

#51715 Hide layers until activity state change is processed.
  Source/WebKit/UIProcess/DrawingAreaProxy.h
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.h
  Source/WebKit/UIProcess/RemoteLayerTree/RemoteLayerTreeDrawingAreaProxy.mm
  Source/WebKit/UIProcess/WebPageProxy.cpp
Labels: merge-queue, WebKit2

#51889 [Temporal] Remove isoDateDifference() and use calendarDateUntil() instead
  JSTests/stress/temporal-plaindate.js
  JSTests/test262/config.yaml
  JSTests/test262/expectations.yaml
  Source/JavaScriptCore/runtime/ISO8601.h
  Source/JavaScriptCore/runtime/TemporalCalendar.cpp
  Source/JavaScriptCore/runtime/TemporalCalendar.h
  Source/JavaScriptCore/runtime/TemporalCalendarPrototype.cpp
  Source/JavaScriptCore/runtime/TemporalDuration.cpp
  Source/JavaScriptCore/runtime/TemporalDuration.h
  Source/JavaScriptCore/runtime/TemporalObject.h
  Source/JavaScriptCore/runtime/TemporalPlainDate.cpp
  Source/JavaScriptCore/runtime/TemporalPlainDate.h
Labels: unsafe-merge-queue, JavaScriptCore

#51282 [JSC] Add stack overflow checks to LiteralParser::parse
  JSTests/stress/dont-crash-on-stack-overflow-JSON-parse-deeply-nested-with-reviver.js
  Source/JavaScriptCore/runtime/LiteralParser.cpp
Labels: merge-queue, JavaScriptCore

#51884 BUILD_LIBRARY_FOR_DISTRIBUTION is missing from WebCore.framework
  Source/WebCore/Configurations/WebCore.xcconfig
Labels: merge-queue, WebKit Misc.

#51865 [GTK][WPE] Make run-api-tests support Linux ports
  Tools/Scripts/webkitpy/api_tests/runner.py
  Tools/Scripts/webkitpy/port/base.py
  Tools/Scripts/webkitpy/port/glib.py
  Tools/glib/api_test_runner.py
Labels: unsafe-merge-queue, Tools / Tests

#51885 AX: The Node& variant of AXObjectCache::getOrCreate scopes a renderer CheckedPtr far larger than necessary, which can cause an unnecessary crash
  LayoutTests/accessibility/dynamic-frame-prepend-crash-expected.txt
  LayoutTests/accessibility/dynamic-frame-prepend-crash.html
  Source/WebCore/accessibility/AXObjectCache.cpp
Labels: merge-queue, Accessibility

#51841 Drop IsDeprecatedWeakRefSmartPointerException from Modules/webauthn
  Source/WebCore/Modules/webauthn/AuthenticatorCoordinator.cpp
  Source/WebCore/Modules/webauthn/AuthenticatorCoordinator.h
  Source/WebCore/Modules/webauthn/AuthenticatorCoordinatorClient.h
  Source/WebCore/page/Page.cpp
Labels: merge-queue, WebCore Misc.

#51899 Unreviewed build fix for macOS Sequoia and earlier.
  Source/WebKit/Configurations/WebKit.xcconfig
Labels: unsafe-merge-queue

#51836 [Swift in WebKit] The bmalloc module map is malformed (must include pas_lock.h)
  Source/bmalloc/Configurations/module.modulemap
  Source/bmalloc/libpas/src/libpas/pas_lock.h
Labels: merge-queue, WebKit Misc.

#51903 [TestWebKitAPI][GTK][WPE] Use the custom main() for TestJavaScriptCore
  Tools/Scripts/run-wpe-tests
  Tools/Scripts/webkitpy/port/glib.py
  Tools/TestWebKitAPI/PlatformGTK.cmake
  Tools/TestWebKitAPI/PlatformWPE.cmake
Labels: unsafe-merge-queue, Tools / Tests

#49469 Limit CVPixelBuffer instances to reasonable sizes
  Source/WebCore/platform/graphics/cv/CVUtilities.mm
Labels: merge-queue, Media

#51905 Crash in WebProcessCache::evictAtRandomIfNeeded()
  Source/WebKit/UIProcess/WebProcessCache.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/SiteIsolation.mm
Labels: unsafe-merge-queue, New Bugs

#51835 [GTK] Changing the docked inspector window width and height with mouse dragging causes jittering
  Source/WebKit/Shared/gtk/NativeWebMouseEventGtk.cpp
  Source/WebKit/Shared/gtk/WebEventFactory.cpp
  Source/WebKit/Shared/gtk/WebEventFactory.h
Labels: unsafe-merge-queue, Web Inspector, GLib Suggested Backport - 2.50

#51872 [JSC] Implement `Array.of` in C++
  JSTests/microbenchmarks/array-of-contiguous-large.js
  JSTests/microbenchmarks/array-of-contiguous.js
  JSTests/microbenchmarks/array-of-double-large.js
  JSTests/microbenchmarks/array-of-double.js
  JSTests/microbenchmarks/array-of-int32-large.js
  JSTests/stress/array-of-contiguous.js
  JSTests/stress/array-of-double.js
  JSTests/stress/array-of-int32.js
  Source/JavaScriptCore/builtins/ArrayConstructor.js
  Source/JavaScriptCore/runtime/ArrayConstructor.cpp
Labels: merge-queue, JavaScriptCore

#51562 Address safer CPP warnings in WebViewImpl.mm
  Source/WebKit/SaferCPPExpectations/RetainPtrCtorAdoptCheckerExpectations
  Source/WebKit/Shared/mac/PasteboardTypes.h
  Source/WebKit/Shared/mac/PasteboardTypes.mm
  Source/WebKit/UIProcess/mac/PageClientImplMac.mm
  Source/WebKit/UIProcess/mac/WebViewImpl.h
  Source/WebKit/UIProcess/mac/WebViewImpl.mm
Labels: merge-queue, WebKit Misc.

#51679 Address safer CPP warnings in PageClientImplMac
  Source/WebKit/UIProcess/mac/PageClientImplMac.mm
Labels: merge-queue, WebKit Misc.

#51933 SpeculationRules: Fix up the Sec-Speculation-Tags implementation.
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/cross-site-prefetch.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/cross-site-to-same-site-redirection-prefetch.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/deduped-and-sorted-tags.https_type=prefetch-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/invalid-tags.https_tag-level=rule&type=prefetch-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/invalid-tags.https_tag-level=ruleset&type=prefetch-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/no-tags.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/prefetch-eagerness-pointer-down.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/prefetch-eagerness-pointer-hover.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/same-site-to-cross-site-redirection-prefetch.https-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/valid-tags.https_tag-level=rule&type=prefetch-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/speculation-rules/speculation-tags/valid-tags.https_tag-level=ruleset&type=prefetch-expected.txt
  Source/WebCore/loader/DocumentPrefetcher.cpp
  Source/WebCore/loader/SpeculationRules.cpp
Labels: merge-queue, New Bugs

#51771 Add early return to WebKitCocoa API tests that fail in site isolation
  Tools/TestWebKitAPI/SourcesCocoa.txt
  Tools/TestWebKitAPI/TestWebKitAPI.xcodeproj/project.pbxproj
  Tools/TestWebKitAPI/Tests/WebKitCocoa/Navigation.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ProcessSwapOnNavigation.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/SiteIsolationUtilities.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/SiteIsolationUtilities.mm
Labels: merge-queue, New Bugs
