Repository WebKit/WebKit, pull requests merged in 2025-03, with the labels that each got.

#41652 Rare crash in RemoteLayerTreeDrawingAreaProxyMac::commitTransientZoom()
  Source/WebKit/UIProcess/RemoteLayerTree/mac/RemoteLayerTreeDrawingAreaProxyMac.h
  Source/WebKit/UIProcess/RemoteLayerTree/mac/RemoteLayerTreeDrawingAreaProxyMac.mm
Labels: merge-queue, Scrolling

#41504 [JSC] byteLength CheckInBounds should be eliminated
  JSTests/stress/uint8array-check-in-bounds.js
  Source/JavaScriptCore/dfg/DFGArrayMode.h
  Source/JavaScriptCore/dfg/DFGClobberize.h
  Source/JavaScriptCore/dfg/DFGConstantFoldingPhase.cpp
  Source/JavaScriptCore/dfg/DFGPlan.cpp
  Source/JavaScriptCore/dfg/DFGSSALoweringPhase.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#41681 [Gardening]: New Test (264263@main): [ macOS wk1 ] fullscreen/element-clear-during-fullscreen-crash.html is a flaky timeout
  LayoutTests/platform/mac-wk1/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#41595 [webkitscmpy] Support GitHub Release Asset Deletion
  Tools/Scripts/libraries/webkitscmpy/setup.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/remote/git_hub.py
Labels: Tools / Tests

#41349 [JSC] Optimize Array.prototype.indexOf for Dense Atom String Arrays
  JSTests/microbenchmarks/atom-string-array-index-of-found.js
  JSTests/microbenchmarks/atom-string-array-index-of-not-found.js
  JSTests/microbenchmarks/atom-string-array-split-empty-index-of-found.js
  JSTests/microbenchmarks/atom-string-array-split-empty-index-of-not-found.js
  JSTests/microbenchmarks/atom-string-array-split-space-index-of-non-rope-found.js
  JSTests/microbenchmarks/atom-string-array-split-space-index-of-non-rope-not-found.js
  JSTests/microbenchmarks/atom-string-array-split-space-index-of-rope-found.js
  JSTests/microbenchmarks/atom-string-array-split-space-index-of-rope-not-found.js
  JSTests/stress/atom-string-array.js
  Source/JavaScriptCore/bytecompiler/NodesCodegen.cpp
  Source/JavaScriptCore/dfg/DFGOperations.cpp
  Source/JavaScriptCore/dfg/DFGOperations.h
  Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp
  Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
  Source/JavaScriptCore/runtime/ArrayPrototype.cpp
  Source/JavaScriptCore/runtime/JSImmutableButterfly.h
  Source/JavaScriptCore/runtime/JSString.h
  Source/JavaScriptCore/runtime/StringPrototype.cpp
  Source/JavaScriptCore/runtime/VM.cpp
  Source/JavaScriptCore/runtime/VM.h
Labels: merge-queue, New Bugs

#41653 Enable FileSystemWritableStreamEnabled by default on Cocoa platforms
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: New Bugs

#41521 Annotate endpoints with PermissionsAPIEnabled flag
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/UIProcess/WebPermissionControllerProxy.cpp
  Source/WebKit/UIProcess/WebPermissionControllerProxy.h
  Source/WebKit/UIProcess/WebPermissionControllerProxy.messages.in
Labels: merge-queue, New Bugs

#41639 [text-wrap-style:pretty] track index of last valid state instead of breakpoint.
  LayoutTests/fast/css3-text/css3-text-wrap/text-wrap-pretty-line-break-crash-2-expected.txt
  LayoutTests/fast/css3-text/css3-text-wrap/text-wrap-pretty-line-break-crash-2.html
  LayoutTests/fast/css3-text/css3-text-wrap/text-wrap-pretty-line-break-crash-expected.txt
  LayoutTests/fast/css3-text/css3-text-wrap/text-wrap-pretty-line-break-crash.html
  Source/WebCore/layout/formattingContexts/inline/InlineContentConstrainer.cpp
  Source/WebCore/layout/formattingContexts/inline/InlineContentConstrainer.h
Labels: merge-queue, Layout and Rendering

#41683 [Gardening]: [ macOS wk1 ] media/track/track-in-band.html is a flaky timeout
  LayoutTests/platform/mac-wk1/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#41557 Annotate NetworkStorageManager endpoints with FileSystemAccessEnabled
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.messages.in
Labels: merge-queue, New Bugs

#41675 [Materials] Add support for a hosted material for media controls
  Source/WebCore/css/CSSPrimitiveValueMappings.h
  Source/WebCore/css/parser/CSSPropertyParserConsumer+AppleVisualEffect.cpp
  Source/WebCore/platform/cocoa/AppleVisualEffect.cpp
  Source/WebCore/platform/cocoa/AppleVisualEffect.h
  Source/WebKit/Platform/cocoa/WKMaterialHostingSupport.h
  Source/WebKit/Platform/cocoa/WKMaterialHostingSupport.swift
  Source/WebKit/Shared/RemoteLayerTree/RemoteLayerTreePropertyApplier.mm
  Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in
Labels: unsafe-merge-queue, New Bugs

#41551 Annotate NetworkStorageManager endpoints using CacheAPIEnabled
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.messages.in
Labels: merge-queue, New Bugs

#41663 [iOS] [UnifiedPDF] PDF documents sometimes flicker during rotation (reenable dynamic viewport size updates)
  Source/WebKit/UIProcess/API/ios/WKWebViewIOS.mm
  Source/WebKit/WebProcess/Plugins/PDF/PDFPluginBase.h
  Source/WebKit/WebProcess/Plugins/PDF/PDFPluginBase.mm
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/PDFPresentationController.mm
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.h
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.mm
  Source/WebKit/WebProcess/Plugins/PluginView.cpp
  Source/WebKit/WebProcess/Plugins/PluginView.h
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.h
  Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm
Labels: merge-queue, New Bugs

#41643 [WTF] Fix and reland 291337@main
  Source/WTF/wtf/DoublyLinkedList.h
  Source/WTF/wtf/PlatformUse.h
  Source/WTF/wtf/SequesteredAllocator.h
  Source/WTF/wtf/SequesteredImmortalHeap.cpp
  Source/WTF/wtf/SequesteredImmortalHeap.h
Labels: merge-queue, New Bugs

#29709 Enable Trusted Types in stable
  LayoutTests/imported/w3c/web-platform-tests/content-security-policy/reporting/report-clips-sample.https.html
  LayoutTests/imported/w3c/web-platform-tests/content-security-policy/securitypolicyviolation/source-file.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/WorkerGlobalScope-eval.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/block-eval-function-constructor.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/csp-block-eval.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-csp-no-tt.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-csp-tt-default-policy-mutate.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-csp-tt-default-policy.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-csp-tt-no-default-policy.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-function-constructor-untrusted-arguments-and-applying-default-policy.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-function-constructor-untrusted-arguments-and-default-policy-throwing.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-function-constructor.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-no-csp-no-tt-default-policy.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-no-csp-no-tt.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/eval-with-permissive-csp.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/trusted-types-eval-reporting-no-unsafe-eval.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/trusted-types-eval-reporting-report-only.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/trusted-types-eval-reporting.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/trusted-types-reporting.html
  LayoutTests/imported/w3c/web-platform-tests/trusted-types/tt-block-eval.html
  Source/JavaScriptCore/runtime/OptionsList.h
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: DOM

#41671 [UnifiedPDF] [iOS] Web process hangs the first time a pointing device is hovered over text annotations
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.h
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.mm
Labels: unsafe-merge-queue, PDF

#41687 [Gardening] REGRESSION(284617@main?): [ iOS arm64 ] compositing/contents-format/deep-color-backing-store.html is a constant failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, Compositing

#41537 StageMode Orbit should decelerate on release of pinch
  Source/WebKit/WebKitSwift/StageMode/WKStageMode.swift
Labels: merge-queue, WebKit Misc.

#41651 Enable UsesWebContentRestrictionsForFilter by default on iOS
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
Labels: merge-queue, New Bugs

#41612 Web Inspector: The new ServiceWorkerDebuggableProxy needs to adopt auto inspection
  Source/WTF/wtf/PlatformEnableCocoa.h
  Source/WebCore/workers/WorkerOrWorkletThread.h
  Source/WebCore/workers/WorkerRunLoop.h
  Source/WebCore/workers/service/context/ServiceWorkerDebuggable.cpp
  Source/WebCore/workers/service/context/ServiceWorkerDebuggable.h
  Source/WebCore/workers/service/context/ServiceWorkerInspectorProxy.cpp
  Source/WebCore/workers/service/context/ServiceWorkerInspectorProxy.h
  Source/WebCore/workers/service/context/ServiceWorkerThreadProxy.cpp
  Source/WebCore/workers/service/context/ServiceWorkerThreadProxy.h
  Source/WebKit/UIProcess/Cocoa/WebProcessProxyCocoa.mm
  Source/WebKit/UIProcess/WebProcessProxy.h
  Source/WebKit/UIProcess/WebProcessProxy.messages.in
  Source/WebKit/WebProcess/Inspector/ServiceWorkerDebuggableProxy.cpp
  Source/WebKit/WebProcess/Inspector/ServiceWorkerDebuggableProxy.h
  Source/WebKit/WebProcess/Storage/WebSWContextManagerConnection.cpp
  Source/WebKit/WebProcess/Storage/WebSWContextManagerConnection.h
  Source/WebKit/WebProcess/Storage/WebSWContextManagerConnection.messages.in
Labels: merge-queue, Web Inspector

#41603 Support alignment properties (align-self/justify-self) in absolute positioned layout
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-htb-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vlr-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/align-self-vrl-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-htb-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vlr-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-ltr-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-ltr-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-ltr-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-rtl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-rtl-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/justify-self-vrl-rtl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-align-self-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-align-self-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-align-self-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-justify-self-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-justify-self-vlr-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/safe-justify-self-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/stretch-intrinsic-size-htb-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/stretch-intrinsic-size-htb-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/stretch-intrinsic-size-vrl-htb-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-align/abspos/stretch-intrinsic-size-vrl-vrl-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/position-try-order-basic-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/try-tactic-alignment-expected.txt
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/style/StyleSelfAlignmentData.cpp
  Source/WebCore/rendering/style/StyleSelfAlignmentData.h
Labels: merge-queue, Layout and Rendering

#41691 Remove the use of WK_XROS_TBA until it's properly supported
  Source/WebKit/WebKitSwift/StageMode/WKStageMode.swift
Labels: unsafe-merge-queue, WebKit Misc.

#41686 REGRESSION(291236@main) Crash in PlaybackSessionManager::actionHandlersChanged()
  Source/WebKit/WebProcess/cocoa/PlaybackSessionManager.mm
Labels: merge-queue, Evangelism

#41694 [Gardening]: [Sonoma Release wk2] Multiple tests in imported/w3c/web-platform-tests/html/semantics/embedded-content/the-canvas-element are flaky failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: New Bugs

#41668 Change the initial value of dynamic-range-limit to constrained-high and add a UA style rule to continue rendering videos in full HDR
  LayoutTests/fast/css/dynamic-range-limit-default-expected.txt
  LayoutTests/fast/css/dynamic-range-limit-default.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-color-hdr/inheritance-expected.txt
  Source/WebCore/css/CSSProperties.json
  Source/WebCore/css/html.css
  Source/WebCore/css/parser/CSSParserContext.cpp
  Source/WebCore/html/HTMLMediaElement.h
  Source/WebCore/platform/graphics/MediaPlayer.h
  Source/WebCore/platform/graphics/PlatformDynamicRangeLimit.h
  Source/WebCore/rendering/style/RenderStyleInlines.h
  Source/WebCore/style/StyleBuilderConverter.h
  Tools/TestWebKitAPI/Tests/WebCore/PlatformDynamicRangeLimitTests.cpp
Labels: merge-queue, CSS

#41699 Unreviewed, fix broken pas_compiler_utils.h
  Source/WTF/wtf/SequesteredImmortalHeap.cpp
  Source/WTF/wtf/SequesteredImmortalHeap.h
  Source/bmalloc/CMakeLists.txt
  Source/bmalloc/bmalloc.xcodeproj/project.pbxproj
  Source/bmalloc/libpas/src/libpas/pas_compiler_utils.h
  Source/bmalloc/libpas/src/libpas/pas_utils_prefix.h
Labels: unsafe-merge-queue, JavaScriptCore

#41700 Unreviewed, remove pas_compiler_utils.h
  Source/bmalloc/CMakeLists.txt
  Source/bmalloc/bmalloc.xcodeproj/project.pbxproj
  Source/bmalloc/libpas/libpas.xcodeproj/project.pbxproj
  Source/bmalloc/libpas/src/libpas/pas_compiler_utils.h
  Source/bmalloc/libpas/src/libpas/pas_utils_prefix.h
Labels: unsafe-merge-queue, JavaScriptCore

#41637 Add linked-on-or-after check to skip SerializedScriptValue roundtrip
  Source/WTF/wtf/cocoa/RuntimeApplicationChecksCocoa.h
  Source/WebKit/Shared/JavaScriptEvaluationResult.mm
  Tools/TestWebKitAPI/Tests/WebKit/EvaluateJavaScript.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WKWebViewEvaluateJavaScript.mm
Labels: unsafe-merge-queue, WebKit Misc.

#41701 Grant committer status to Marais Rossouw
  metadata/contributors.json
Labels: unsafe-merge-queue, New Bugs

#41698 [JSC] Use template parameter for `trimString` function
  Source/JavaScriptCore/runtime/StringPrototype.cpp
Labels: merge-queue, JavaScriptCore

#41632 Annotate endpoints using SharedWorkerEnabled
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerConnection.cpp
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerConnection.h
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerConnection.messages.in
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.cpp
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.h
  Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.messages.in
Labels: merge-queue, New Bugs

#41554 Annotate NetworkStorageManager endpoints with IndexedDBAPIEnabled
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/NetworkProcess/storage/NetworkStorageManager.messages.in
Labels: merge-queue, New Bugs

#41704 [JSC] Use CachedCall::callWithArguments when numSubpatterns is zero
  Source/JavaScriptCore/runtime/StringPrototype.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#41703 Fix a compile warning in ElementTextPreview.mm with stable/202407232 branch of clang
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ElementTextPreview.mm
Labels: unsafe-merge-queue, New Bugs

#41709 REGRESSION(291414@main): [Win, PlayStation] WebSWContextManagerConnection.cpp(188,14): error: unused variable 'serviceWorkerIdentifier'
  Source/WebKit/WebProcess/Storage/WebSWContextManagerConnection.cpp
Labels: unsafe-merge-queue, New Bugs

#41307 Annotate ShowShareSheet endpoint with feature flag
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebKit/UIProcess/WebPageProxy.messages.in
Labels: merge-queue

#41708 Non-unified build fixes, early March edition
  Source/WebCore/platform/EventTrackingRegions.cpp
  Source/WebCore/rendering/style/StyleSelfAlignmentData.cpp
  Source/WebCore/rendering/style/StyleSelfAlignmentData.h
Labels: WebCore Misc.

#41655 [scroll-animations] WPT test scroll-animations/scroll-timelines/effect-updateTiming.html has failures
  LayoutTests/imported/w3c/web-platform-tests/scroll-animations/scroll-timelines/effect-updateTiming-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/scroll-animations/scroll-timelines/effect-updateTiming.html
Labels: unsafe-merge-queue, Animations

#41560 Address Safer cpp failures in BitmapImageDescriptor
  Source/WebCore/SaferCPPExpectations/NoUncountedMemberCheckerExpectations
  Source/WebCore/platform/graphics/BitmapImageDescriptor.cpp
  Source/WebCore/platform/graphics/BitmapImageDescriptor.h
  Source/WebCore/platform/graphics/BitmapImageSource.h
Labels: merge-queue, Layout and Rendering

#41712 [scroll-animations] `entry` and `exit` timeline ranges should be expressed in terms of other ranges
  LayoutTests/imported/w3c/web-platform-tests/scroll-animations/view-timelines/sticky/view-timeline-sticky-offscreen-6-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/scroll-animations/view-timelines/view-timeline-range-large-subject-expected.txt
  Source/WebCore/animation/ViewTimeline.cpp
Labels: unsafe-merge-queue, Animations

#41661 [JSC][GreedyRegAlloc] Memory efficiency optimizations
  Source/JavaScriptCore/b3/air/AirAllocateRegistersByGreedy.cpp
Labels: merge-queue, JavaScriptCore

#41689 Shadows on split inlines don't respect -webkit-box-decoration-break
  LayoutTests/TestExpectations
  Source/WebCore/rendering/BackgroundPainter.cpp
Labels: merge-queue, Layout and Rendering

#41679 Adopt BorderShape for rendering ridge and groove borders
  Source/WebCore/rendering/BorderPainter.cpp
  Source/WebCore/rendering/BorderPainter.h
  Source/WebCore/rendering/BorderShape.h
Labels: merge-queue, Layout and Rendering

#41624 [GPUP][macOS] Add sandbox telemetry for IOKit user client IOSurfaceAcceleratorClient
  Source/WebKit/GPUProcess/mac/com.apple.WebKit.GPUProcess.sb.in
Labels: unsafe-merge-queue, WebKit Process Model

#41320 [Site Isolation] Forward StopMediaCapture IPC to remote pages
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/SiteIsolation.mm
Labels: merge-queue, Media

#41716 Address UncountedCallArgsChecker exceptions in ViewTransitionTypeSet.cpp
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/dom/ViewTransitionTypeSet.cpp
Labels: DOM

#41650 Re-enable mutation events in Apple applications except Safari
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WTF/wtf/cocoa/RuntimeApplicationChecksCocoa.h
  Source/WTF/wtf/cocoa/RuntimeApplicationChecksCocoa.mm
  Source/WebCore/platform/ios/wak/WebCoreThread.mm
  Source/WebKit/Shared/WebPreferencesDefaultValues.cpp
  Source/WebKit/Shared/WebPreferencesDefaultValues.h
Labels: unsafe-merge-queue, New Bugs

#41690 MutationEvent interface is exposed even when mutation events are disabled
  LayoutTests/fast/dom/mutation-events-disablement-expected.txt
  LayoutTests/fast/dom/mutation-events-disablement.html
  Source/WebCore/bindings/js/WebCoreBuiltinNames.h
  Source/WebCore/dom/MutationEvent.idl
Labels: unsafe-merge-queue, New Bugs

#41680 Address safer cpp failures in WebKit/UIProcess/WebAuthentication
  Source/WebCore/Modules/webauthn/fido/Pin.cpp
  Source/WebCore/Modules/webauthn/fido/Pin.h
  Source/WebKit/SaferCPPExpectations/MemoryUnsafeCastCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedLambdaCapturesCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
  Source/WebKit/UIProcess/API/APIWebAuthenticationAssertionResponse.h
  Source/WebKit/UIProcess/API/APIWebAuthenticationPanel.cpp
  Source/WebKit/UIProcess/API/APIWebAuthenticationPanel.h
  Source/WebKit/UIProcess/WebAuthentication/Authenticator.cpp
  Source/WebKit/UIProcess/WebAuthentication/Authenticator.h
  Source/WebKit/UIProcess/WebAuthentication/AuthenticatorManager.cpp
  Source/WebKit/UIProcess/WebAuthentication/AuthenticatorManager.h
  Source/WebKit/UIProcess/WebAuthentication/AuthenticatorTransportService.h
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/CcidConnection.mm
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/CcidService.mm
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/LocalService.mm
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/NfcService.mm
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/WebAuthenticationPanelClient.mm
  Source/WebKit/UIProcess/WebAuthentication/Mock/MockNfcService.mm
  Source/WebKit/UIProcess/WebAuthentication/Virtual/VirtualAuthenticatorManager.h
  Source/WebKit/UIProcess/WebAuthentication/Virtual/VirtualService.mm
  Source/WebKit/UIProcess/WebAuthentication/fido/CtapAuthenticator.cpp
  Source/WebKit/UIProcess/WebAuthentication/fido/CtapCcidDriver.cpp
  Source/WebKit/UIProcess/WebAuthentication/fido/CtapCcidDriver.h
  Source/WebKit/UIProcess/WebAuthentication/fido/CtapNfcDriver.h
  Source/WebKit/UIProcess/WebAuthentication/fido/FidoAuthenticator.cpp
  Source/WebKit/UIProcess/WebAuthentication/fido/FidoAuthenticator.h
  Source/WebKit/UIProcess/WebAuthentication/fido/FidoService.cpp
  Source/WebKit/UIProcess/WebAuthentication/fido/FidoService.h
  Source/WebKit/UIProcess/WebAuthentication/fido/U2fAuthenticator.cpp
Labels: merge-queue, WebKit2

#41717 Address UncountedCallArgsChecker exceptions in DocumentFullscreen.cpp/h
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/dom/DocumentFullscreen.cpp
  Source/WebCore/dom/DocumentFullscreen.h
  Source/WebCore/dom/DocumentOrShadowRootFullscreen.cpp
  Source/WebCore/page/Frame.h
Labels: merge-queue, DOM

#41573 [Site Isolation] Remote page is sometimes not injected in to FrameProcess
  Source/WebKit/UIProcess/BrowsingContextGroup.cpp
Labels: merge-queue, WebKit Process Model

#41641 AX: Immediately queue changes to AXProperty::TextRuns as part of the next tree snapshot so we have the right tree state in response to text markers generated from typing in an editable field
  LayoutTests/accessibility-isolated-tree/TestExpectations
  LayoutTests/accessibility/mac/input-type-change-crash-expected.txt
  LayoutTests/accessibility/mac/text-marker-from-typing-notification-expected.txt
  LayoutTests/accessibility/mac/text-marker-from-typing-notification.html
  LayoutTests/platform/mac-wk1/TestExpectations
  Source/WebCore/accessibility/AXObjectCache.cpp
  Source/WebCore/accessibility/AXTextMarker.cpp
  Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperBase.mm
  Tools/WebKitTestRunner/InjectedBundle/cocoa/AccessibilityCommonCocoa.mm
Labels: merge-queue, Accessibility

#41684 AX: AXTextMarker::offsetFromRoot repeatedly calls lineID() on a non-text-run marker, which is very expensive
  Source/WebCore/accessibility/AXCoreObject.h
  Source/WebCore/accessibility/AXLogger.cpp
  Source/WebCore/accessibility/AXTextMarker.cpp
  Source/WebCore/accessibility/AccessibilityNodeObject.cpp
  Source/WebCore/accessibility/AccessibilityNodeObject.h
  Source/WebCore/accessibility/AccessibilityObject.h
  Source/WebCore/accessibility/cocoa/AXTextMarkerCocoa.mm
  Source/WebCore/accessibility/isolatedtree/AXIsolatedObject.cpp
  Source/WebCore/accessibility/isolatedtree/AXIsolatedObject.h
  Source/WebCore/accessibility/isolatedtree/AXIsolatedTree.h
Labels: merge-queue, Accessibility

#41723 [Safer CPP] Unskip BitmapImageDescriptor.cpp as it is now passing
  Source/WebCore/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
Labels: unsafe-merge-queue, Tools / Tests

#41613 [css-anchor-position-1] Implement parsing `position-visibility`
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-computed-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-computed.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-computed.tentative-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-parsing-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-parsing.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-parsing.tentative-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/parsing/position-visibility-parsing.tentative.html
  LayoutTests/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/accumulation-per-property-002-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/addition-per-property-002-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/interpolation-per-property-002-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/property-list.js
  LayoutTests/platform/glib/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt
  LayoutTests/platform/ios/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt
  LayoutTests/platform/ipad/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt
  LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt
  LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/accumulation-per-property-002-expected.txt
  LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/addition-per-property-002-expected.txt
  LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/web-animations/animation-model/animation-types/interpolation-per-property-002-expected.txt
  Source/WebCore/css/CSSPrimitiveValueMappings.h
  Source/WebCore/css/CSSProperties.json
  Source/WebCore/css/CSSValueKeywords.in
  Source/WebCore/css/ComputedStyleExtractor.cpp
  Source/WebCore/css/parser/CSSPropertyParserConsumer+Anchor.cpp
  Source/WebCore/css/parser/CSSPropertyParserConsumer+Anchor.h
  Source/WebCore/rendering/style/RenderStyle.cpp
  Source/WebCore/rendering/style/RenderStyle.h
  Source/WebCore/rendering/style/RenderStyleConstants.cpp
  Source/WebCore/rendering/style/RenderStyleConstants.h
  Source/WebCore/rendering/style/RenderStyleInlines.h
  Source/WebCore/rendering/style/RenderStyleSetters.h
  Source/WebCore/rendering/style/StyleRareNonInheritedData.cpp
  Source/WebCore/rendering/style/StyleRareNonInheritedData.h
  Source/WebCore/style/StyleBuilderConverter.h
Labels: merge-queue, CSS

#41658 Address more Safer CPP failures in Proxy classes in the WebKit/ folder
  Source/WebKit/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
  Source/WebKit/UIProcess/Inspector/InspectorTargetProxy.cpp
  Source/WebKit/UIProcess/RemotePageProxy.cpp
  Source/WebKit/UIProcess/WebOpenPanelResultListenerProxy.cpp
  Source/WebKit/WebProcess/FileAPI/BlobRegistryProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteNativeImageBackendProxy.h
  Source/WebKit/WebProcess/GPU/graphics/RemoteResourceCacheProxy.cpp
  Source/WebKit/WebProcess/GPU/graphics/RemoteResourceCacheProxy.h
  Source/WebKit/WebProcess/WebPage/WebURLSchemeHandlerProxy.cpp
  Source/WebKit/WebProcess/WebPage/WebURLSchemeTaskProxy.cpp
  Source/WebKit/WebProcess/WebPage/WebURLSchemeTaskProxy.h
  Source/WebKit/WebProcess/WebProcess.cpp
  Source/WebKit/WebProcess/WebProcess.h
  Source/WebKit/WebProcess/cocoa/RemoteRealtimeMediaSourceProxy.cpp
  Source/WebKit/WebProcess/cocoa/RemoteRealtimeMediaSourceProxy.h
Labels: merge-queue, WebKit2

#41685 Fix AX sandbox violation
  Source/WebKit/WebProcess/com.apple.WebProcess.sb.in
Labels: unsafe-merge-queue, WebKit Process Model

#41656 Launch Services application information is sometimes not set
  Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.h
  Source/WebKit/NetworkProcess/mac/NetworkConnectionToWebProcessMac.mm
  Source/WebKit/WebProcess/WebProcess.cpp
  Source/WebKit/WebProcess/WebProcess.h
  Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
Labels: WebKit Process Model

#41720 Reintroduce animation listener to transform property of model
  Source/WebKit/WebKitSwift/StageMode/WKStageMode.swift
Labels: New Bugs

#41725 Fix run-benchmark default profile type
  Tools/Scripts/webkitpy/benchmark_runner/run_benchmark.py
Labels: unsafe-merge-queue, New Bugs, skip-ews

#41682 [SwiftUI] Update `WebPage.DialogPresenting` to latest interface
  Source/WebKit/UIProcess/API/Swift/WKUIDelegateAdapter.swift
  Source/WebKit/UIProcess/API/Swift/WebPage+DialogPresenting.swift
  Source/WebKit/UIProcess/API/Swift/WebPage.swift
  Tools/SwiftBrowser/Source/SwiftBrowser.swift
  Tools/SwiftBrowser/Source/ViewModel/BrowserViewModel.swift
  Tools/SwiftBrowser/Source/ViewModel/DialogPresenter.swift
  Tools/SwiftBrowser/Source/ViewModel/NavigationDecider.swift
  Tools/SwiftBrowser/Source/Views/ContentView.swift
  Tools/TestWebKitAPI/Tests/WebKit Swift/URLSchemeHandlerTests.swift
Labels: New Bugs

#41721 Fix UncountedCallArgsChecker & UncheckedCallArgsChecker warnings in ViewTransition.cpp
  Source/WebCore/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncheckedLocalVarsCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/css/CSSViewTransitionRule.h
  Source/WebCore/dom/ViewTransition.cpp
  Source/WebCore/dom/ViewTransition.h
Labels: unsafe-merge-queue, DOM

#41727 Tweak js heap growth
  Source/JavaScriptCore/runtime/OptionsList.h
Labels: unsafe-merge-queue, New Bugs

#41730 REGRESSION(291033@main): Broke visionOS layout tests
  LayoutTests/platform/visionos/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#41726 Remove the unused RenderStyle::getRoundedInnerBorderFor()
  Source/WebCore/rendering/style/RenderStyle.cpp
  Source/WebCore/rendering/style/RenderStyle.h
Labels: merge-queue, Layout and Rendering

#41731 Unreviewed, address unexpected safer cpp failures in BitmapImageDescriptor.cpp
  Source/WebCore/platform/graphics/BitmapImageDescriptor.cpp
Labels: merge-queue, WebCore Misc.

#41729 [JSC] Remove unnecessary casting for `vmCall` in lowering to B3
  Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
Labels: JavaScriptCore

#41724 [JSC] Relax megamorphic IC condition for 2 digits integers
  Source/JavaScriptCore/bytecode/InlineCacheCompiler.h
  Source/JavaScriptCore/jit/JITOperations.cpp
  Source/JavaScriptCore/runtime/StringPrototype.cpp
  Source/JavaScriptCore/runtime/Structure.h
Labels: unsafe-merge-queue, JavaScriptCore

#41735 [GStreamer] ASSERTs when handling flush events
  LayoutTests/platform/glib/TestExpectations
Labels: unsafe-merge-queue, Platform, skip-ews

#41737 [GStreamer] ASSERTs when handling flush events
  LayoutTests/platform/glib/TestExpectations
  LayoutTests/platform/wpe/TestExpectations
Labels: unsafe-merge-queue, Platform, skip-ews

#41742 Versioning.
  Configurations/Version.xcconfig
Labels: skip-ews

#41741 Unreviewed, address unexpected safer cpp failures in BitmapImageDescriptor.cpp
  Source/WebCore/platform/graphics/BitmapImageDescriptor.cpp
Labels: unsafe-merge-queue, WebCore Misc.

#41746 REGRESSION(291247@main): Crash in JSC::MarkedBlock::vm under WebCore::Element::attachShadow if ScopedCustomElementRegistryEnabled is off
  LayoutTests/fast/shadow-dom/scoped-custom-element-registry-disabled-expected.txt
  LayoutTests/fast/shadow-dom/scoped-custom-element-registry-disabled.html
  Source/WebCore/dom/Element.cpp
Labels: unsafe-merge-queue, New Bugs

#41734 [fullscreen] Stop nesting event loop tasks in requestFullscreen
  Source/WebCore/dom/DocumentFullscreen.cpp
Labels: unsafe-merge-queue, DOM

#41751 [macOS] Add support for bottom and right obscured content insets
  LayoutTests/tiled-drawing/scrolling/scroll-with-bottom-right-content-inset-expected.html
  LayoutTests/tiled-drawing/scrolling/scroll-with-bottom-right-content-inset.html
  Source/WebCore/platform/ScrollView.cpp
Labels: merge-queue, New Bugs

#41757 Remove unused constructor from RenderMedia
  Source/WebCore/rendering/RenderMedia.cpp
  Source/WebCore/rendering/RenderMedia.h
Labels: Media

#41509 Spatial Video does not show Immersive or View Spatial button when muted or lacks audio track
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/dom/DocumentFullscreen.cpp
  Source/WebCore/platform/cocoa/VideoPresentationModel.h
  Source/WebCore/platform/cocoa/VideoPresentationModelVideoElement.h
  Source/WebCore/platform/cocoa/VideoPresentationModelVideoElement.mm
  Source/WebCore/platform/ios/VideoPresentationInterfaceIOS.h
  Source/WebCore/platform/ios/WebVideoFullscreenControllerAVKit.mm
  Source/WebKit/UIProcess/API/ios/WKWebViewIOS.h
  Source/WebKit/UIProcess/API/ios/WKWebViewIOS.mm
  Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.h
  Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.messages.in
  Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.mm
  Source/WebKit/UIProcess/PageClient.h
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/UIProcess/ios/PageClientImplIOS.h
  Source/WebKit/UIProcess/ios/PageClientImplIOS.mm
  Source/WebKit/UIProcess/ios/fullscreen/WKFullScreenViewController.h
  Source/WebKit/UIProcess/ios/fullscreen/WKFullScreenViewController.mm
  Source/WebKit/UIProcess/ios/fullscreen/WKFullScreenWindowControllerIOS.h
  Source/WebKit/UIProcess/ios/fullscreen/WKFullScreenWindowControllerIOS.mm
  Source/WebKit/WebProcess/cocoa/VideoPresentationManager.h
  Source/WebKit/WebProcess/cocoa/VideoPresentationManager.mm
Labels: merge-queue, Media

#41616 [CoordinatedGraphics] Remove m_isValid from CoordinatedPlatformLayerBufferProxy
  Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedPlatformLayerBufferProxy.cpp
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedPlatformLayerBufferProxy.h
Labels: unsafe-merge-queue, Platform

#41615 [CoordinatedGraphics] Simplify contents scale handling
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStore.cpp
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStore.h
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStoreProxy.cpp
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStoreProxy.h
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStoreTile.cpp
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedBackingStoreTile.h
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedPlatformLayer.cpp
Labels: unsafe-merge-queue, WebKitGTK

#41707 Reset the resumeTime and accumulated time on svg.setCurrentTime
  LayoutTests/svg/animations/getCurrentTime-pause-unpause-setCurrentTime-expected.txt
  LayoutTests/svg/animations/getCurrentTime-pause-unpause-setCurrentTime.html
  Source/WebCore/svg/animation/SMILTimeContainer.cpp
  Source/WebCore/svg/animation/SMILTimeContainer.h
Labels: unsafe-merge-queue, SVG

#41722 REGRESSION(291444@main): [GTK] Fix the GTK3 build
  Source/WebKit/WebProcess/InjectedBundle/API/gtk/DOM/WebKitDOMDOMWindow.cpp
Labels: unsafe-merge-queue, WebKitGTK

#40966 [JSC][armv7] Verify MacroAssemblerARMv7::branch32 usage in debug builds
  Source/JavaScriptCore/assembler/MacroAssemblerARMv7.h
  Source/JavaScriptCore/bytecode/InlineCacheCompiler.cpp
  Source/JavaScriptCore/wasm/WasmBBQJIT.cpp
Labels: merge-queue, JavaScriptCore

#41621 [GStreamer] fast/mediastream/mediastreamtrack-configurationchange.html triggers flaky critical warnings
  Source/WebCore/platform/mediastream/gstreamer/GStreamerMockDeviceProvider.cpp
Labels: merge-queue, Platform

#41760 [TFC] Remove 'relative' length from Table Layout
  Source/WebCore/layout/formattingContexts/table/TableLayout.cpp
Labels: merge-queue, Layout and Rendering

#41764 Add logging to RTCRtpSender::replaceTrack
  Source/WebCore/Modules/mediastream/RTCRtpSender.cpp
Labels: merge-queue

#41012 [GStreamer][MSE] Support text tracks in MSE
  LayoutTests/media/media-source/content/counting-video-vttsimple-manifest.json
  LayoutTests/media/media-source/content/counting-video-vttsimple.mp4
  LayoutTests/media/media-source/media-source-vttsimple-expected.txt
  LayoutTests/media/media-source/media-source-vttsimple.html
  Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
  Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.h
Labels: merge-queue

#41749 [macOS] Vertical scrollbar is misplaced when a nonzero left content inset is set
  LayoutTests/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
  LayoutTests/resources/ui-helper.js
  LayoutTests/scrollbars/mac/top-left-content-insets-scrollbar-position-expected.txt
  LayoutTests/scrollbars/mac/top-left-content-insets-scrollbar-position.html
  LayoutTests/tiled-drawing/top-left-content-insets.html
  Source/WebCore/platform/ScrollView.cpp
  Source/WebCore/testing/Internals.cpp
  Source/WebCore/testing/Internals.h
  Source/WebCore/testing/Internals.idl
  Source/WebKit/UIProcess/API/Cocoa/WKWebViewPrivateForTesting.h
  Source/WebKit/UIProcess/API/Cocoa/WKWebViewTesting.mm
  Source/WebKit/UIProcess/API/ios/WKWebViewPrivateForTestingIOS.h
  Source/WebKit/UIProcess/API/ios/WKWebViewTestingIOS.mm
  Tools/WebKitTestRunner/cocoa/UIScriptControllerCocoa.h
  Tools/WebKitTestRunner/cocoa/UIScriptControllerCocoa.mm
  Tools/WebKitTestRunner/ios/UIScriptControllerIOS.h
  Tools/WebKitTestRunner/ios/UIScriptControllerIOS.mm
Labels: merge-queue, New Bugs

#40493 Add Page Visibility API iframe Site Isolation Test
  LayoutTests/http/tests/site-isolation/page-visibility-onvisibilitychange-in-iframe-expected.txt
  LayoutTests/http/tests/site-isolation/page-visibility-onvisibilitychange-in-iframe.html
  LayoutTests/http/tests/site-isolation/resources/page-visibility-iframe-send-onvisibility-change-back.html
  LayoutTests/platform/ios/TestExpectations
Labels: merge-queue, New Bugs

#32158 Remove `svgDocument` interface from `HTMLFrameElement` to align with other browsers
  LayoutTests/platform/mac/svg/custom/frame-getSVGDocument-expected.png
  LayoutTests/svg/custom/frame-getSVGDocument-expected.txt
  LayoutTests/svg/custom/frame-getSVGDocument.html
  LayoutTests/svg/custom/interface-getSVGDocument-expected.txt
  LayoutTests/svg/custom/interface-getSVGDocument.html
  Source/WebCore/html/HTMLEmbedElement.idl
  Source/WebCore/html/HTMLFrameElement.idl
  Source/WebCore/html/HTMLObjectElement.idl
Labels: merge-queue, DOM

#41515 WebCodecs decoder frames format is always I420
  LayoutTests/http/wpt/webcodecs/vp9-p2-decoder-expected.txt
  LayoutTests/http/wpt/webcodecs/vp9-p2-decoder.html
  Source/WebCore/Modules/webcodecs/WebCodecsVideoDecoder.cpp
  Source/WebCore/Modules/webcodecs/WebCodecsVideoFrame.cpp
  Source/WebCore/Modules/webcodecs/WebCodecsVideoFrame.h
  Source/WebCore/platform/VideoPixelFormat.cpp
  Source/WebCore/platform/VideoPixelFormat.h
Labels: merge-queue, Media

#41748 Address Safer CPP failures in UniqueIDBDatabase.cpp
  Source/WebCore/Modules/indexeddb/server/ServerOpenDBRequest.h
  Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabase.cpp
  Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabaseConnection.cpp
  Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabaseConnection.h
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
Labels: unsafe-merge-queue, WebCore Misc.

#41745 Address Safer CPP failures in UniqueIDBDatabaseTransaction.cpp
  Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabaseTransaction.cpp
  Source/WebCore/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebCore/SaferCPPExpectations/UncountedLambdaCapturesCheckerExpectations
Labels: unsafe-merge-queue, WebCore Misc.

#41767 [web-animations] setting an animation's effect via the bindings should not prevent the `animation-timeline` CSS property from setting the animation's timeline
  LayoutTests/imported/w3c/web-platform-tests/css/css-animations/CSSAnimation-effect.tentative.html
Labels: Animations

#41771 Fix CredentialUpdateShim build issue
  Source/WebKit/Configurations/WebKit.xcconfig
  Source/WebKit/Configurations/WebKitSwift.xcconfig
  Source/WebKit/DerivedSources-output.xcfilelist
  Source/WebKit/DerivedSources.make
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
Labels: merge-queue, New Bugs

#41781 Remove outdated protector pattern in `DocumentFullscreen::dispatchPendingEvents()`
  Source/WebCore/dom/DocumentFullscreen.cpp
  Source/WebCore/page/Page.cpp
Labels: unsafe-merge-queue, DOM

#41785 Build fix after 291504
  Source/WebKit/Configurations/WebKit.xcconfig
  Source/WebKit/Configurations/WebKitSwift.xcconfig
  Source/WebKit/DerivedSources-output.xcfilelist
  Source/WebKit/DerivedSources.make
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
Labels: New Bugs

#40002 [Gardening] REGRESSION (287736@main?): [ iOS ] fast/mediastream/microphone-interruption-and-audio-session.html is constantly failing.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, WebRTC

#41752 [JSC] Use parseRecursively for eval preprocess
  Source/JavaScriptCore/interpreter/Interpreter.cpp
  Source/JavaScriptCore/runtime/JSGlobalObjectFunctions.cpp
  Source/JavaScriptCore/runtime/LiteralParser.cpp
  Source/JavaScriptCore/runtime/LiteralParser.h
Labels: unsafe-merge-queue, JavaScriptCore

#41733 Address more Safer CPP warnings in WebKit/
  Source/WebCore/loader/archive/cf/LegacyWebArchive.cpp
  Source/WebCore/loader/archive/cf/LegacyWebArchive.h
  Source/WebKit/Platform/cocoa/WebPrivacyHelpers.mm
  Source/WebKit/SaferCPPExpectations/UncheckedCallArgsCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedCallArgsCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedLambdaCapturesCheckerExpectations
  Source/WebKit/SaferCPPExpectations/UncountedLocalVarsCheckerExpectations
  Source/WebKit/UIProcess/Automation/SimulatedInputDispatcher.cpp
  Source/WebKit/UIProcess/Automation/WebAutomationSession.cpp
  Source/WebKit/UIProcess/Automation/WebAutomationSession.h
  Source/WebKit/UIProcess/BrowsingContextGroup.cpp
  Source/WebKit/UIProcess/Cocoa/SOAuthorization/SOAuthorizationSession.mm
  Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionURLSchemeHandlerCocoa.mm
  Source/WebKit/UIProcess/FrameProcess.cpp
  Source/WebKit/UIProcess/SpeechRecognitionPermissionManager.cpp
  Source/WebKit/UIProcess/UserMediaProcessManager.cpp
  Source/WebKit/UIProcess/WebPreferences.cpp
  Source/WebKit/UIProcess/WebPreferences.h
  Source/WebKit/UIProcess/WebProcessActivityState.cpp
  Source/WebKit/UIProcess/WebProcessActivityState.h
  Source/WebKit/UIProcess/WebProcessCache.cpp
  Source/WebKit/UIProcess/WebURLSchemeHandler.cpp
  Source/WebKit/UIProcess/WebURLSchemeTask.cpp
  Source/WebKit/UIProcess/WebURLSchemeTask.h
  Source/WebKit/UIProcess/WebsiteData/WebDeviceOrientationAndMotionAccessController.cpp
  Source/WebKit/UIProcess/mac/WebContextMenuProxyMac.mm
  Source/WebKit/WebProcess/Extensions/API/Cocoa/WebExtensionAPIRuntimeCocoa.mm
  Source/WebKit/WebProcess/Extensions/API/WebExtensionAPIRuntime.h
  Source/WebKit/WebProcess/GPU/webrtc/SampleBufferDisplayLayer.cpp
  Source/WebKit/WebProcess/Inspector/WebInspectorInternal.cpp
  Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp
  Source/WebKit/WebProcess/Network/WebSocketChannel.cpp
  Source/WebKit/WebProcess/Network/webrtc/LibWebRTCNetwork.cpp
  Source/WebKit/WebProcess/Network/webrtc/LibWebRTCNetworkManager.cpp
  Source/WebKit/WebProcess/Plugins/PDF/PDFPluginBase.mm
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.h
  Source/WebKit/WebProcess/Plugins/PDF/UnifiedPDF/UnifiedPDFPlugin.mm
  Source/WebKit/WebProcess/Storage/WebSWClientConnection.cpp
  Source/WebKit/WebProcess/WebCoreSupport/WebSpeechSynthesisClient.cpp
  Source/WebKit/WebProcess/WebPage/ViewUpdateDispatcher.cpp
  Source/WebKit/WebProcess/WebPage/mac/TiledCoreAnimationDrawingArea.mm
  Source/WebKit/WebProcess/WebStorage/StorageAreaMap.cpp
  Source/WebKit/WebProcess/cocoa/VideoPresentationManager.mm
  Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
Labels: merge-queue, WebKit2

#41762 Remove `m_shouldDumpAllFrameScrollPositions` from the injected bundle
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.cpp
  Tools/WebKitTestRunner/InjectedBundle/TestRunner.h
  Tools/WebKitTestRunner/TestInvocation.cpp
  Tools/WebKitTestRunner/TestInvocation.h
Labels: unsafe-merge-queue, Tools / Tests

#41548 Introduce xpc_string_get_wtfstring() for bounds safety and efficiency
  Source/WTF/wtf/spi/darwin/XPCSPI.h
  Source/WebKit/Shared/EntryPointUtilities/Cocoa/XPCService/XPCServiceMain.mm
  Tools/Scripts/webkitpy/style/checkers/cpp.py
  Tools/Scripts/webkitpy/style/checkers/cpp_unittest.py
Labels: unsafe-merge-queue, WebKit Misc.

#41790 [Gardening] [ iOS Release ] fast/viewport/ios/device-width-viewport-after-changing-view-scale.html is a flaky failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#41770 Remove duplicate `floats` tests in favor of WPT after 290059@main
  LayoutTests/css2.1/20110323/floats-wrap-top-below-001l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-001r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-002l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-002r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-003l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-003r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-001l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-001l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-001r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-001r.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-002l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-002l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-002r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-002r.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-003l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-003l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-003r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-bfc-003r.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-001l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-001l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-001r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-001r.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-002l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-002l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-002r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-002r.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-003l-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-003l.htm
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-003r-expected.html
  LayoutTests/css2.1/20110323/floats-wrap-top-below-inline-003r.htm
  LayoutTests/css2.1/20110323/floats-zero-height-wrap-001-expected.html
  LayoutTests/css2.1/20110323/floats-zero-height-wrap-001.htm
  LayoutTests/css2.1/20110323/floats-zero-height-wrap-002-expected.html
  LayoutTests/css2.1/20110323/floats-zero-height-wrap-002.htm
Labels: merge-queue, CSS

#41450 Add SP3 subtest support to run-benchmark
  Tools/Scripts/webkitpy/benchmark_runner/benchmark_runner.py
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/jetstream2.1.plan
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/jetstream2.2.plan
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/motionmark1.2.1.plan
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/motionmark1.3.1.plan
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/motionmark1.3.plan
  Tools/Scripts/webkitpy/benchmark_runner/data/plans/speedometer3.plan
  Tools/Scripts/webkitpy/benchmark_runner/webdriver_benchmark_runner.py
  Tools/Scripts/webkitpy/benchmark_runner/webserver_benchmark_runner.py
Labels: merge-queue, New Bugs, skip-ews

#41791 Unreviewed non-unified source build fix 2025-03 (part 1)
  Source/WebCore/workers/service/InstallEvent.cpp
Labels: New Bugs

#41784 Crash under XPCServiceInitializerDelegate::getClientSDKAlignedBehaviors()
  Source/WebKit/Shared/EntryPointUtilities/Cocoa/XPCService/XPCServiceEntryPoint.mm
  Source/WebKit/UIProcess/Launcher/cocoa/ProcessLauncherCocoa.mm
Labels: merge-queue, WebKit2

#41780 REGRESSION(291449@main): [MacOS Debug] Two tests are constant crashes in http/wpt/webauthn/public-key-credential (failure in EWS)
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/CcidConnection.h
  Source/WebKit/UIProcess/WebAuthentication/Cocoa/CcidConnection.mm
Labels: merge-queue, New Bugs

#41536 REGRESSION(290300@main): SaveAsPDF crashes if site-isolation is enabled
  LayoutTests/platform/mac-wk2/TestExpectations
  Source/WebCore/platform/graphics/ImageBuffer.h
  Source/WebCore/platform/graphics/ImageBufferDisplayListBackend.cpp
  Source/WebCore/platform/graphics/ImageBufferDisplayListBackend.h
  Source/WebCore/platform/graphics/displaylists/DisplayListDrawingContext.cpp
  Source/WebCore/platform/graphics/displaylists/DisplayListDrawingContext.h
  Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.cpp
  Tools/TestWebKitAPI/Tests/WebKitCocoa/DrawingToPDF.mm
Labels: merge-queue, New Bugs

#41800 [Gardening] [ iOS Release ] imported/blink/fast/text/international-iteration-simple-text.html is a flaky failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, Text

#41796 Remove `Messages::WebPage::HideFindIndicator`
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.h
  Source/WebKit/WebProcess/WebPage/WebPage.messages.in
Labels: unsafe-merge-queue, WebKit Misc.

#41804 [Gardening] REGRESSION(291130@main?): [ iOS ] imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-006.html is a constant failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, CSS

#41750 [WebGPU] Index buffer validation is incorrect in indirect path on Intel Macs
  LayoutTests/fast/webgpu/regression/repro_1382-expected.txt
  LayoutTests/fast/webgpu/regression/repro_1382.html
  Source/WebGPU/WebGPU/Buffer.h
  Source/WebGPU/WebGPU/Buffer.mm
  Source/WebGPU/WebGPU/Device.mm
  Source/WebGPU/WebGPU/RenderPassEncoder.mm
Labels: merge-queue, WebGPU

#41794 REGRESSION(291033@main): Broke visionOS layout tests
  Source/WebKit/UIProcess/ios/WKContentView.mm
Labels: merge-queue

#41799 [JSC] Disable PROTECTED_JIT
  Source/WTF/wtf/PlatformUse.h
Labels: unsafe-merge-queue, JavaScriptCore

#41810 [Gardening] REGRESSION(iOS 18): [ iOS ] imported/w3c/web-platform-tests/html/semantics/disabled-elements/event-propagate-disabled-keyboard.tentative.html is a constant failure.
  LayoutTests/platform/ios/TestExpectations
Labels: New Bugs

#40436 [webkitbugspy] git-webkit fails with AttributeError if a tracked bug is not found when cc-ing
  Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py
Labels: unsafe-merge-queue, Tools / Tests

#41774 Crash under WebDiagnosticLoggingClient::logDiagnosticMessage()
  Source/WebKit/WebProcess/WebCoreSupport/WebDiagnosticLoggingClient.cpp
  Source/WebKit/WebProcess/WebCoreSupport/WebDiagnosticLoggingClient.h
Labels: merge-queue, WebKit2

#41815 [Gardening] REGRESSION(284785@main): [ iOS ] imported/w3c/web-platform-tests/navigation-api/navigation-methods/return-value/back-204-205-download.html is a flaky failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, New Bugs

#41816 EWS REGRESSION (Sonoma): [ macOS wk2 release ] fast/text/canvas-color-fonts/stroke-gradient-COLR.html is a consistent image failure (failure in EWS)
  LayoutTests/fast/text/canvas-color-fonts/stroke-gradient-COLR.html
Labels: unsafe-merge-queue, New Bugs

#41817 [iOS] fast/forms/ios/focus-input-in-fixed.html often crashes
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, Tools / Tests

#41819 [Gardening] [ iOS ] imported/w3c/web-platform-tests/webrtc-stats/hardware-capability-stats.https.html is a flaky failure.
  LayoutTests/platform/ios/TestExpectations
Labels: unsafe-merge-queue, WebRTC

#41818 REGRESSION(291398@main): ASSERTION FAILED: expected.asNumber() == result.asNumber() in JSC::EncodedJSValue JSC::arrayProtoFuncIndexOf(JSGlobalObject *, CallFrame *)
  Source/JavaScriptCore/bytecompiler/NodesCodegen.cpp
  Source/JavaScriptCore/runtime/StringPrototype.cpp
  Source/JavaScriptCore/runtime/WeakGCMap.h
Labels: unsafe-merge-queue, JavaScriptCore

#41782 [WebGPU] External texture reads do not take into account size differences between different planes
  LayoutTests/fast/webgpu/regression/repro_288962-expected.png
  LayoutTests/fast/webgpu/regression/repro_288962-expected.txt
  LayoutTests/fast/webgpu/regression/repro_288962.html
  Source/WebGPU/WGSL/Metal/MetalFunctionWriter.cpp
Labels: merge-queue, WebGPU

#41811 Fix run-benchmark subtests
  Tools/Scripts/webkitpy/benchmark_runner/benchmark_runner.py
Labels: unsafe-merge-queue, New Bugs

#41803 [JSC] Fix SequesteredArenaMalloc when compiling synchronously
  Source/JavaScriptCore/jit/JIT.cpp
  Source/JavaScriptCore/jit/JITWorklist.cpp
Labels: merge-queue, JavaScriptCore

#41822 Fix PlayStation build following 291507@main
  Source/WebCore/dom/DocumentFullscreen.cpp
Labels: New Bugs

#41786 Rare crash in LocalFrameView::handleWheelEventForScrolling()
  Source/WebCore/page/LocalFrameView.cpp
Labels: merge-queue, Scrolling

#41812 Put Trusted Types behind a LOA check
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WTF/wtf/cocoa/RuntimeApplicationChecksCocoa.h
  Source/WebKit/Shared/WebPreferencesDefaultValues.cpp
  Source/WebKit/Shared/WebPreferencesDefaultValues.h
Labels: unsafe-merge-queue, DOM

#41747 RenderObject::isOutOfFlowPositioned can be read before it gets set.
  LayoutTests/TestExpectations
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/RenderBox.h
  Source/WebCore/rendering/RenderElement.cpp
  Source/WebCore/rendering/RenderElement.h
  Source/WebCore/rendering/RenderFragmentedFlow.cpp
  Source/WebCore/rendering/RenderFragmentedFlow.h
  Source/WebCore/rendering/RenderLayerModelObject.cpp
  Source/WebCore/rendering/RenderObject.cpp
  Source/WebCore/rendering/style/RenderStyleConstants.cpp
  Source/WebCore/rendering/style/RenderStyleConstants.h
  Source/WebCore/rendering/updating/RenderTreeUpdater.cpp
Labels: merge-queue, Layout and Rendering

#41702 [SwiftUI] Refactor file structure for better separation of implementation from interface
  Source/WebKit/UIProcess/API/Cocoa/WKWebViewConfiguration+Extras.swift
  Source/WebKit/UIProcess/API/Cocoa/WKWebpagePreferences+Extras.swift
  Source/WebKit/UIProcess/API/Swift/URLSchemeHandler.swift
  Source/WebKit/UIProcess/API/Swift/WebPage+Configuration.swift
  Source/WebKit/UIProcess/API/Swift/WebPage+NavigationPreferences.swift
  Source/WebKit/UIProcess/API/Swift/WebPage.swift
  Source/WebKit/UIProcess/Cocoa/Foundation+Extras.swift
  Source/WebKit/UIProcess/Cocoa/WKDownloadDelegateAdapter.swift
  Source/WebKit/UIProcess/Cocoa/WKNavigationDelegateAdapter.swift
  Source/WebKit/UIProcess/Cocoa/WKScrollGeometryAdapter.swift
  Source/WebKit/UIProcess/Cocoa/WKUIDelegateAdapter.swift
  Source/WebKit/UIProcess/Cocoa/WKURLSchemeHandlerAdapter.swift
  Source/WebKit/UIProcess/Cocoa/WebPageWebView.swift
  Source/WebKit/WebKit.xcodeproj/project.pbxproj
  Source/WebKit/_WebKit_SwiftUI/API/View+WebViewModifiers.swift
  Source/WebKit/_WebKit_SwiftUI/API/WebPage+SwiftUI.swift
  Source/WebKit/_WebKit_SwiftUI/API/WebPageNavigationAction+SwiftUI.swift
  Source/WebKit/_WebKit_SwiftUI/API/WebView.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/CocoaWebViewAdapter.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/EnvironmentValues+Extras.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/Foundation+Extras.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/PlatformTextSearching.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/SwiftUI+Extras.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/ViewModifierContexts.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/ViewModifiers.swift
  Source/WebKit/_WebKit_SwiftUI/Implementation/WebViewRepresentable.swift
Labels: New Bugs

#41801 AX: Remote SVGs can share renderers, breaking the accessibility tree
  LayoutTests/accessibility/ax-thread-text-apis/svg-duplicated-expected.txt
  LayoutTests/accessibility/ax-thread-text-apis/svg-duplicated.html
  Source/WebCore/accessibility/AccessibilityRenderObject.cpp
  Source/WebCore/accessibility/AccessibilitySVGRoot.h
Labels: merge-queue, Accessibility

#41826 [macOS] Add method for determining if accessibility setting "Differentiate without color" is enabled
  Source/WebCore/platform/Theme.h
  Source/WebCore/platform/mac/ThemeMac.h
  Source/WebCore/platform/mac/ThemeMac.mm
Labels: New Bugs

#41830 Unreviewed, fix WeakGCMap::add for already cleared entry
  Source/JavaScriptCore/bytecompiler/NodesCodegen.cpp
  Source/JavaScriptCore/runtime/StringPrototype.cpp
  Source/JavaScriptCore/runtime/WeakGCMap.h
Labels: unsafe-merge-queue, JavaScriptCore

#41776 [JSC] Continue test coverage of the graph coloring register allocator
  Tools/Scripts/run-jsc-stress-tests
Labels: unsafe-merge-queue, JavaScriptCore

#41820 [iOS] Context menu items for quick note and copy link with highlight are missing images
  Source/WebKit/Platform/mac/MenuUtilities.mm
  Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm
Labels: unsafe-merge-queue, New Bugs

#41768 ReadableStream cancel method not reliably called in Service Worker
  Source/WebCore/Modules/fetch/FetchBodyConsumer.cpp
  Source/WebCore/Modules/fetch/FetchBodyConsumer.h
  Source/WebCore/Modules/streams/ReadableStreamSink.h
  Tools/TestWebKitAPI/Tests/WebKitCocoa/ServiceWorkerBasic.mm
Labels: merge-queue, Service Workers

#41754 Integrate position-area and self-alignment properties (align-self/justify-self)
  LayoutTests/TestExpectations
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scroll-position-try-014-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/auto-margins-position-area-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/last-successful-basic-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/last-successful-change-fallbacks-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/last-successful-change-try-rule-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/last-successful-intermediate-ignored-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/position-area-align-justify-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/position-area-align-justify-wm-dir-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/position-area-in-position-try-expected.txt
  LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/position-area-scrolling-003.tentative-expected.txt
  Source/WebCore/rendering/RenderBox.cpp
  Source/WebCore/rendering/style/PositionArea.cpp
  Source/WebCore/rendering/style/PositionArea.h
Labels: merge-queue, Layout and Rendering

#41719 Pause silent push timer in webpushd for inspected workers
  LayoutTests/http/wpt/service-workers/push-console-messages-no-showNotification.https-expected.txt
  LayoutTests/http/wpt/service-workers/push-console-messages-showNotification-late.https-expected.txt
  Source/WebCore/workers/service/context/ServiceWorkerThread.cpp
  Source/WebKit/NetworkProcess/Notifications/NetworkNotificationManager.cpp
  Source/WebKit/NetworkProcess/Notifications/NetworkNotificationManager.h
  Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerToContextConnection.cpp
  Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerToContextConnection.h
  Source/WebKit/webpushd/PushClientConnection.h
  Source/WebKit/webpushd/PushClientConnection.messages.in
  Source/WebKit/webpushd/PushClientConnection.mm
  Source/WebKit/webpushd/WebPushDaemon.h
  Source/WebKit/webpushd/WebPushDaemon.mm
  Tools/TestWebKitAPI/Tests/WebKitCocoa/WebPushDaemon.mm
Labels: merge-queue, WebKit Misc.

#41808 REGRESSION(262954@main): [GTK] Attempts access to disengaged optional with caret blinking disabled
  Source/WebCore/platform/SimpleCaretAnimator.cpp
Labels: unsafe-merge-queue, WebKitGTK, GLib Suggested Backport - 2.46, GLib Suggested Backport - 2.48

#41839 [JSC] Array#includes / Array#indexOf inlined code should check empty value
  JSTests/stress/array-includes-empty.js
  Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp
  Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
Labels: unsafe-merge-queue, JavaScriptCore

#41779 [WebGPU] Ensure staticThreadgroupMemoryLength does not exceed device capabilities
  LayoutTests/fast/webgpu/nocrash/fuzz-145583179-expected.txt
  LayoutTests/fast/webgpu/nocrash/fuzz-145583179.html
  Source/WebGPU/WGSL/GlobalVariableRewriter.cpp
  Source/WebGPU/WGSL/Types.cpp
  Source/WebGPU/WGSL/WGSLShaderModule.cpp
  Source/WebGPU/WGSL/WGSLShaderModule.h
Labels: merge-queue, WebGPU

#41787 Use ref-counting forwarding for `DocumentFullscreen`
  Source/WTF/wtf/LoggerHelper.h
  Source/WebCore/css/SelectorCheckerTestFunctions.h
  Source/WebCore/dom/Document.cpp
  Source/WebCore/dom/Document.h
  Source/WebCore/dom/DocumentFullscreen.cpp
  Source/WebCore/dom/DocumentFullscreen.h
  Source/WebCore/dom/DocumentOrShadowRootFullscreen.cpp
  Source/WebCore/html/HTMLMediaElement.cpp
  Source/WebCore/html/MediaElementSession.cpp
  Source/WebCore/page/EventHandler.cpp
  Source/WebCore/page/LocalFrameView.cpp
  Source/WebCore/page/Page.cpp
  Source/WebCore/page/ScreenOrientation.cpp
  Source/WebCore/page/ios/ContentChangeObserver.cpp
  Source/WebCore/rendering/RenderLayerBacking.cpp
  Source/WebCore/rendering/RenderLayerCompositor.cpp
  Source/WebCore/style/StyleAdjuster.cpp
  Source/WebCore/style/UserAgentStyle.cpp
  Source/WebKit/WebProcess/WebCoreSupport/WebLocalFrameLoaderClient.cpp
  Source/WebKitLegacy/mac/WebCoreSupport/WebChromeClient.mm
  Source/WebKitLegacy/mac/WebView/WebView.mm
Labels: unsafe-merge-queue, DOM

#41844 "Response served by service worker has redirections" may appear with NVIDIA GeForce NOW
  LayoutTests/http/wpt/service-workers/redirect-flag-navigation-cache-worker.js
  LayoutTests/http/wpt/service-workers/redirect-flag-navigation-cache.https-expected.txt
  LayoutTests/http/wpt/service-workers/redirect-flag-navigation-cache.https.html
  LayoutTests/http/wpt/service-workers/resources/cached-after-redirection.html
  LayoutTests/http/wpt/service-workers/resources/cached-after-redirection.html.headers
  LayoutTests/http/wpt/service-workers/resources/redirect-to-cached-after-redirection.py
  Source/WebCore/workers/service/FetchEvent.cpp
  Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerNavigationPreloader.cpp
Labels: merge-queue, Service Workers

#41783 [Modern Media Controls] String "Source" is not localized in the 'Show Media Stats' pane
  Source/WebCore/en.lproj/modern-media-controls-localized-strings.js
Labels: merge-queue, Media

#41840 [JSC] Remove unnecessary std::forward in ensureValue
  Source/JavaScriptCore/runtime/WeakGCMap.h
Labels: unsafe-merge-queue, New Bugs

#41837 [tvOS] Enable support for dark mode CSS features
  Source/WTF/wtf/PlatformEnableCocoa.h
Labels: unsafe-merge-queue, New Bugs

#41841 [JSC] Extract MicrotaskQueue
  Source/JavaScriptCore/CMakeLists.txt
  Source/JavaScriptCore/JavaScriptCore.xcodeproj/project.pbxproj
  Source/JavaScriptCore/Sources.txt
  Source/JavaScriptCore/runtime/MicrotaskQueue.cpp
  Source/JavaScriptCore/runtime/MicrotaskQueue.h
  Source/JavaScriptCore/runtime/VM.cpp
  Source/JavaScriptCore/runtime/VM.h
  Tools/TestWebKitAPI/TestWebKitAPI.xcodeproj/project.pbxproj
Labels: unsafe-merge-queue, JavaScriptCore

#41851 [Gardening] REGRESSION(290385@main - 290390@main?): [ wk2 arm64 ] imported/w3c/web-platform-tests/dom/nodes/remove-from-shadow-host-and-adopt-into-iframe.html is a flaky timeout.
  LayoutTests/platform/ios/TestExpectations
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, DOM

#41850 `webkitscmpy` should use the latest version of `webkitbugspy`
  Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py
Labels: Tools / Tests

#41854 [Gardening]: New Test (261136@main): [ macOS wk2 ] http/wpt/background-fetch/background-fetch-abort.window.html is a flaky failure
  LayoutTests/platform/mac-wk2/TestExpectations
Labels: unsafe-merge-queue, New Bugs
